properties([
        [
                $class  : 'BuildDiscarderProperty',
                strategy: [
                        $class               : 'LogRotator',
                        artifactDaysToKeepStr: '20', artifactNumToKeepStr: '2',
                        daysToKeepStr        : '20', numToKeepStr: '8'
                ]
        ]
])


pipeline {
    agent any

    stages {
        stage('Download code') {
            steps {
                git branch: env.BRANCH_NAME,
                credentialsId: '00371305-231a-41e5-94b6-4a7070208d7d',
                url: 'https://bitbucket.org:ekoolikott/koolikott.git'
            }
        }
        stage('Run tests') {
            steps {
                wrap([$class: 'Xvfb']) {
                    sh 'cd ui-tests && ./mvnw clean verify'
                }
            }
        }
    }
}
