SET foreign_key_checks = 0;

INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (1, 'ERROR_LOGIN_FAILED_EKOOL', 'Sisselogimine ebaõnnestus. eKoolis oled registreeritud kasutaja, kelle infost puudub isikukood. Logi sisse eKooli, salvesta sealse konto infosse oma isikukood ja tule siis e-Koolikotti tagasi. E-Koolikotti saad sisse logida ka ID-kaardi ja mID-ga.');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'ERROR_LOGIN_FAILED_EKOOL', 'Login failed. You are a registered user of eKool whose info is missing social security number. Login to eKool, save your social security number in you profile and return to e-Koolikott. You can also login to e-Koolikott with ID-card and mID.');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (2, 'ERROR_LOGIN_FAILED_EKOOL', 'Sisselogimine ebaõnnestus. eKoolis oled registreeritud kasutaja, kelle infost puudub isikukood. Logi sisse eKooli, salvesta sealse konto infosse oma isikukood ja tule siis e-Koolikotti tagasi. E-Koolikotti saad sisse logida ka ID-kaardi ja mID-ga.');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (1, 'ERROR_LOGIN_FAILED_STUUDIUM', 'Sisselogimine ebaõnnestus. Stuudiumis oled registreeritud kasutaja, kelle infost puudub isikukood. Logi sisse Stuudiumisse, salvesta sealse konto infosse oma isikukood ja tule siis e-Koolikotti tagasi. E-Koolikotti saad sisse logida ka ID-kaardi ja mID-ga.');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'ERROR_LOGIN_FAILED_STUUDIUM', 'Login failed. You are a registered user of Stuudium whose info is missing social security number. Login to Stuudium, save your social security number in you profile and return to e-Koolikott. You can also login to e-Koolikott with ID-card and mID.');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (2, 'ERROR_LOGIN_FAILED_STUUDIUM', 'Sisselogimine ebaõnnestus. Stuudiumis oled registreeritud kasutaja, kelle infost puudub isikukood. Logi sisse Stuudiumisse, salvesta sealse konto infosse oma isikukood ja tule siis e-Koolikotti tagasi. E-Koolikotti saad sisse logida ka ID-kaardi ja mID-ga.');

SET foreign_key_checks = 1;
