SET foreign_key_checks = 0;

INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_NO','Ei');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_NO','No');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_NO','Ei');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_YES','Jah');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_YES','Yes');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_YES','Jah');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_OTHER_ISSUE','Muu');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_OTHER_ISSUE','Other');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_OTHER_ISSUE','Muu');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_REQUEST_SENT','Päring saadetud');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_REQUEST_SENT','Request sent');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_REQUEST_SENT','Päring saadetud');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_REQUEST_FAILED','Päringu saatmine ebaõnnestus');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_REQUEST_FAILED','Request send failed');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_REQUEST_FAILED','Päringu saatmine ebaõnnestus');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_ASK_QUESTION','Esita küsimus');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_ASK_QUESTION','Ask a question');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_ASK_QUESTION','Esita küsimus');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_HELP','Kas vajad abi?');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_HELP','Do you need help?');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_HELP','Kas vajad abi?');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_CHOOSE_TOPIC_INTRO','Vali teema, mille osas soovid küsida');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_CHOOSE_TOPIC_INTRO','Choose a topic you require help with');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_CHOOSE_TOPIC_INTRO','Vali teema, mille osas soovid küsida');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_CHOOSE_TOPIC','Vali teema');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_CHOOSE_TOPIC','Choose topic');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_CHOOSE_TOPIC','Vali teema');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_TOPIC_IS_MANDATORY','Teema on kohustuslik');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_TOPIC_IS_MANDATORY','Topic is mandatory');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_TOPIC_IS_MANDATORY','Teema on kohustuslik');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_NAME','Nimi');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_NAME','Name');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_NAME','Nimi');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_EMAIL','E-mail');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_EMAIL','E-mail');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_EMAIL','E-mail');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_NAME_IS_MANDATORY','Nimi on kohustuslik');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_NAME_IS_MANDATORY','Name is mandatory');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_NAME_IS_MANDATORY','Nimi on kohustuslik');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_EMAIL_IS_MANDATORY','E-mail on kohustuslik');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_EMAIL_IS_MANDATORY','E-mail is mandatory');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_EMAIL_IS_MANDATORY','E-mail on kohustuslik');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_MESSAGE','Sisu');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_MESSAGE','Message');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_MESSAGE','Sisu');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_MESSAGE_IS_MANDATORY','Sisu on kohustuslik');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_MESSAGE_IS_MANDATORY','Message is mandatory');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_MESSAGE_IS_MANDATORY','Sisu on kohustuslik');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_SEND','Saada');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_SEND','Send');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_SEND','Saada');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_BACK','Tagasi');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_BACK','Back');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_BACK','Tagasi');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_WRONG_EMAIL_FORMAT','Kontrolli e-posti aadressi');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_WRONG_EMAIL_FORMAT','Cheack e-mail address');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_WRONG_EMAIL_FORMAT','Kontrolli e-posti aadressi');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_CANCEL','Loobu');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_CANCEL','Cancel');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_CANCEL','Loobu');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_CONTINUE','Edasi');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_CONTINUE','Next');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_CONTINUE','Edasi');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_HAS_USER_MANUAL','Meil on olemas selle teema kohta videojuhend. Kas soovid sellega tutvuda?');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_HAS_USER_MANUAL','We have video about this topic. Do you wish to watch it?');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_HAS_USER_MANUAL','Meil on olemas selle teema kohta videojuhend. Kas soovid sellega tutvuda?');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_SPECIFY_QUESTION','Palun täpsusta oma küsimus ja jäta meile oma andmed, et saaksime sinuga ühendust võtta');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_SPECIFY_QUESTION','Please specify you question and leave us you info so we could contact you');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_SPECIFY_QUESTION','Palun täpsusta oma küsimus ja jäta meile oma andmed, et saaksime sinuga ühendust võtta');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_WILL_SEND_RESPONSE','Vastuse saadame ühe tööpäeva jooksul teie e-posti aadressile');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_WILL_SEND_RESPONSE','We will send a response in one work day to your given e-mail address');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_WILL_SEND_RESPONSE','Vastuse saadame ühe tööpäeva jooksul teie e-posti aadressile');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (1,'CUSTOMER_SUPPORT_CLOSE','Sulge');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (3,'CUSTOMER_SUPPORT_CLOSE','Close');
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES (2,'CUSTOMER_SUPPORT_CLOSE','Sulge');


SET foreign_key_checks = 1;