SET foreign_key_checks = 0;

call update_translations('SUBTOPIC_JALAKÄIJA_OHUTU_LIIKLEMINE', 'Jalakäija ohutu liiklemine', 'Pedestrian traffic safety', 'Jalakäija ohutu liiklemine');
call update_translations('SUBTOPIC_IGAPÄEVAELU_ÕPPIMINE_TÖÖ', 'Igapäevaelu õppimine töö', 'Everydaylife learning work', 'Igapäevaelu õppimine töö');
call update_translations('SUBTOPIC_GLOBAALSED_KESKKONNAPROBLEEMID_JA_NENDE_MÕJU_ERI_REGIOONIDELE', 'Globaalsed keskkonnaprobleemid ja nende mõju eri regiooonidele', 'Global environment problems and their impact to different regions', 'Globaalsed keskkonnaprobleemid ja nende mõju eri regiooonidele');
call update_translations('SUBTOPIC_GRAMMATIKA', 'Grammatika', 'Grammar', 'Grammatika');
call update_translations('SUBTOPIC_KAARDI_MATEMAATILINE_ALUS', 'Kaardi matemaatiline alus', 'Mathematical basis of chart', 'Kaardi matemaatiline alus');
call update_translations('SUBTOPIC_LUGEMISE_EESMÄRGISTAMINE', 'Lugemise eesmärgistamine', 'Reading targeting', 'Lugemise eesmärgistamine');
call update_translations('SUBTOPIC_PEREKOND_JA_SUGULASED', 'Perekond ja sugulased', 'Family and relatives', 'Perekond ja sugulased');
call update_translations('TOPIC_KEHALISE_KASVATUSE_ALASED_TEADMISED', 'Kehalise kasvatuse alased teadmised', 'Knowledge of physical education', 'Kehalise kasvatuse alased teadmised');
call update_translations('SUBTOPIC_MUUTUSED_LOODUSES', 'Muutused looduses', 'Changes in nature', 'Muutused looduses');
call update_translations('SUBTOPIC_HARIDUS_JA_TÖÖ', 'Haridus ja töö', 'Education and work', 'Haridus ja töö');
call update_translations('SUBTOPIC_LOETUD_TEOSE_ÜHISARUTELU', 'Loetud teose ühisarutelu', 'Discussion of read book', 'Loetud teose ühisarutelu');
call update_translations('SUBTOPIC_ESITAMISE_EESMÄRGISTAMINE', 'Esitamise eesmärgistamine', 'Submission targeting', 'Esitamise eesmärgistamine');
call update_translations('SUBTOPIC_EHITISED', 'Ehitised', 'Buildings', 'Ehitised');
call update_translations('SUBTOPIC_KODUKOHT_EESTI', 'Kodukoht Eesti', 'Homeland Estonia', 'Kodukoht Eesti');
call update_translations('SUBTOPIC_EESTI_RAHVA_TÄHTPÄEVAD', 'Eesti rahva tähtpäevad', 'Estonian anniversaries', 'Eesti rahva tähtpäevad');
call update_translations('SUBTOPIC_TRANSPORDIVAHENDID', 'Transpordivahendid', 'Means of transport', 'Transpordivahendid');
call update_translations('SUBTOPIC_PIIBLILOOD', 'Piiblilood', 'Bible stories', 'Piiblilood');
call update_translations('TOPIC_KUULAMINE', 'Kuulamine', 'Listening', 'Kuulamine');
call update_translations('SUBTOPIC_SEIKLUSJUTT_JA_AJALOOLINE_JUTUSTUS', 'Seiklusjutt ja ajalooline jutustus', 'Adventure and historical story ', 'Seiklusjutt ja ajalooline jutustus');
call update_translations('SUBTOPIC_RAHVASTIKUPROTSESSIDE_MÕJU_ÜHISKONNA_ARENGULE', 'Rahvastikuprotsesside mõju ühiskonna arengule', 'Impact of demographic processes on social development', 'Rahvastikuprotsesside mõju ühiskonna arengule');
call update_translations('SUBTOPIC_OHUTUS', 'Ohutus', 'Safety', 'Ohutus');
call update_translations('TOPIC_LIIKUMISMÄNGUD', 'Liiklusmängud', 'Traffic games', 'Liiklusmängud');
call update_translations('SUBTOPIC_LUGEMISTEHNIKA', 'Lugemistehnika', 'Reading technique', 'Lugemistehnika');
call update_translations('TOPIC_TANTS_JA_RÜTMIKA', 'Tants ja rütmika', 'Dance and rhythm', 'Tants ja rütmika');
call update_translations('SUBTOPIC_KUJUNDLIK_MÕTLEMINE', 'Kujundlik mõtlemine', 'Abstract thinking', 'Kujundlik mõtlemine');
call update_translations('SUBTOPIC_KERGETÖÖSTUS', 'Kergetööstus', 'Light industry', 'Kergetööstus');
call update_translations('SUBTOPIC_INIMKEHA', 'Inimkeha', 'Human body', 'Inimkeha');
call update_translations('SUBTOPIC_JÄÄTMED', 'Jäätmed', 'Wastes', 'Jäätmed');
call update_translations('SUBTOPIC_EPITEET_JA_VÕRDLUS', 'Epiteet ja võrdlus', 'Epithet and comparison', 'Epiteet ja võrdlus');
call update_translations('SUBTOPIC_ERINEVAD_MEEDIAD', 'Erinevad meediad', 'Different medias', 'Erinevad meediad');
call update_translations('SUBTOPIC_LAPSED_MUJAL_MAAILMAS', 'Lapsed mujal maailmas', 'Children in the world', 'Lapsed mujal maailmas');
call update_translations('SUBTOPIC_LASTEAED', 'Lasteaed', 'Kindergarten', 'Lasteaed');
call update_translations('TOPIC_KUJUNDAMINE', 'Kujundamine', 'Design', 'Kujundamine');
call update_translations('SUBTOPIC_MUISTENDID', 'Muistendid', 'Legends', 'Muistendid');
call update_translations('SUBTOPIC_RIIM', 'Riim', 'Rhyme', 'Riim');
call update_translations('TOPIC_TEHISKESKKOND', 'Tehiskeskkond', 'Artificial environment', 'Tehiskeskkond');
call update_translations('SUBTOPIC_TEKSTI_KAVASTAMINE', 'Teksti kavastamine', 'Planning of text', 'Teksti kavastamine');
call update_translations('SUBTOPIC_TEKSTI_TEEMA_JA_PEAMÕTE', 'Teksti teema ja peamõte', 'Point of text and main idea', 'Teksti teema ja peamõte');
call update_translations('SUBJECT_ROOTSI_KEEL', 'Rootsi keel', 'Swedish', 'Rootsi keel');
call update_translations('SUBTOPIC_INIMENE_JA_ÜHISKOND', 'Inimene ja ühiskond', 'Human and society', 'Inimene ja ühiskond');
call update_translations('SUBTOPIC_ESITUSTEHNIKAD', 'Esitustehnikad', 'Perfomance techniques', 'Esitustehnikad');
call update_translations('SUBTOPIC_KÕRVA,_KUULMIS-_JA_TASAKAALUMEEL', 'Kõrva, kuulmis- ja tasakaalumeel', 'Hearing and balance sensation', 'Kõrva, kuulmis- ja tasakaalumeel');
call update_translations('SUBTOPIC_INIMESE_MÕJU_LOODUSELE', 'Inimese mõju loodusele', 'Human impact to nature', 'Inimese mõju loodusele');
call update_translations('SUBTOPIC_KAUBANDUSE_JA_TARBIMISEGA_SEOTUD_KONFLIKTID', 'Kaubanduse ja tarbimise seotud konfliktid', 'Trade and consumption related conflicts', 'Kaubanduse ja tarbimise seotud konfliktid');
call update_translations('SUBTOPIC_LOODUSRESSURSSIDE_KASUTAMINE_JA_SELLE_MÕJU_KESKKONNALE', 'Loodusressursside kasutamine ja selle mõju keskkonnale', 'Use of nature resources and their impact to environment', 'Loodusressursside kasutamine ja selle mõju keskkonnale');
call update_translations('SUBTOPIC_KODUTEHNIKA', 'Kodutehnika', 'Home technics', 'Kodutehnika');
call update_translations('TOPIC_KUJUTAMINE_JA_VÄLJENDAMINE', 'Kujutamine ja väljendamine', 'Imagination and expression', 'Kujutamine ja väljendamine');
call update_translations('SUBTOPIC_TEGELASTE_PROBLEEMID_JA_SUHTED', 'Tegelaste probleemid ja suhted', 'Characters problems and relations', 'Tegelaste probleemid ja suhted');
call update_translations('SUBTOPIC_MEISTERDAMINE', 'Meisterdamine', 'Crafting', 'Meisterdamine');
call update_translations('SUBTOPIC_TEISED_RAHVUSED_EESTIS', 'Teised rahvused eestis', 'Other nations in Estonia', 'Teised rahvused eestis');
call update_translations('TOPIC_ERINEVAD_SPORDIALAD', 'Erinevad spordialad', 'Different sports', 'Erinevad spordialad');
call update_translations('SUBTOPIC_MINA', 'Mina', 'Me','Mina');
call update_translations('TOPIC_TEHNILISED_OSKUSED', 'Tehnilised oskused','Technical skills','Tehnilised oskused');
call update_translations('SUBTOPIC_HÄÄLDAMINE', 'Hääldamine', 'Pronunciation', 'Hääldamine');
call update_translations('SUBTOPIC_KULTUUR_JA_LOOMING', 'Kultuur ja looming', 'Culture and creation', 'Kultuur ja looming');
call update_translations('SUBTOPIC_KOMPOSITSIOONIST_LÄHTUDES', 'Kompositsioonist lähtudes', 'Originate from composition', 'Kompositsioonist lähtudes');
call update_translations('SUBTOPIC_KODUKOHA_LOODUS', 'Kodukoha loodus', 'Home place nature', 'Kodukoha loodus');
call update_translations('SUBTOPIC_KODUMAA', 'Kodumaa', 'Homeland', 'Kodumaa');
call update_translations('TOPIC_VESTLUSTEEMAD', 'Vestlusteemad', 'Topics of discussion', 'Vestlusteemad');
call update_translations('SUBJECT_SOOME_KEEL', 'Soome keel', 'Finnish', 'Soome keel');
call update_translations('SUBTOPIC_KESKKOND_JA_TEHNOLOOGIA', 'Keskkond ja tehnoloogia', 'Environment and technology', 'Keskkond ja tehnoloogia');
call update_translations('SUBTOPIC_GISI_ANALÜÜSID', 'Gis-i analüüsid', 'Gis analysis', 'Gis-i analüüsid');
call update_translations('SUBTOPIC_ERINEVUSED_REGIOONIDE_JA_RIIKIDE_VAHEL', 'Erinevused regioonide ja riikide vahel', 'Differencies between regions and countries', 'Erinevused regioonide ja riikide vahel');
call update_translations('SUBTOPIC_SÜNDMUSED', 'Sündmused', 'Events', 'Sündmused');
call update_translations('SUBTOPIC_RAHVASTE_MÜÜDID', 'Rahvaste tüübid', 'Types of nations', 'Rahvaste tüübid');
call update_translations('SUBTOPIC_TERVISE_VÄÄRTUSTAMINE', 'Tervise väärtustamine', 'Health valuation', 'Tervise väärtustamine');
call update_translations('TOPIC_SOTSIAALNE_KESKKOND', 'Sotsiaalne keskkond', 'Social environment', 'Sotsiaalne keskkond');
call update_translations('TOPIC_MUUSIKALIS_RÜTMILINE_LIIKUMINE', 'Muusikalis rütmiline liikumine', 'Musical rhythmic movement', 'Muusikalis rütmiline liikumine');
call update_translations('TOPIC_LOODUSKESKKOND', 'Looduskeskkond', 'Natural environment', 'Looduskeskkond');
call update_translations('SUBTOPIC_VÄÄRTUSED_JA_KÄITUMISREEGLID', 'Väärtused ja käitumisreeglid', 'Values and rules of behaviour', 'Väärtused ja käitumisreeglid');
call update_translations('TOPIC_SUURUSED_JA_MÕÕTMINE', 'Suurused ja mõõtmine', 'Measures and measuring', 'Suurused ja mõõtmine');
call update_translations('SUBTOPIC_TURVAVARUSTUS', 'Turvavarustus', 'Safety equipment', 'Turvavarustus');
call update_translations('TOPIC_KEELEKASUTUS', 'Keelekasutus', 'Use of language', 'Keelekasutus');
call update_translations('SUBTOPIC_OMALOOMING', 'Omalooming', 'Selfcreation', 'Omalooming');
call update_translations('SUBTOPIC_SÕNAVARA_RIKASTAMINE', 'Sõnavara rikastamine', 'Enriching vocabulary', 'Sõnavara rikastamine');
call update_translations('SUBTOPIC_TEKSTILÄHEDASELT', 'Tekstilähedaselt', 'Close to text', 'Tekstilähedaselt');
call update_translations('SUBTOPIC_TEKSTI_KUI_TERVIKU_MÕISTMINE', 'Teksti kui terviku mõistmine', 'Understanding the text as a whole', 'Teksti kui terviku mõistmine');
call update_translations('SUBTOPIC_VANASÕNAD_JA_KÕNEKÄÄNUD', 'Vanasõnad ja kõnekäänud', 'Proverbs', 'Vanasõnad ja kõnekäänud');
call update_translations('SUBTOPIC_KODU_JA_LÄHIÜMBRUS', 'Kodu ja lähiümbrus', 'Home and surroundings', 'Kodu ja lähiümbrus');
call update_translations('SUBTOPIC_GISI_MÕISTE,_KOMPONENDID_JA_KASUTUSVALDKONNAD', 'Gisi mõiste komponendid ja kasutusvaldkonnad', 'GIS components and field of use', 'Gisi mõiste komponendid ja kasutusvaldkonnad');
call update_translations('TOPIC_GEOMEETRILISED_KUJUNDID', 'Geomeetrilised kujundid', 'Geometric shapes', 'Geomeetrilised kujundid');
call update_translations('TOPIC_HULGAD_LOENDAMINE_JA_ARVUD_ARVUTAMINE', 'Hulgad,loendamine ja arvutamine', 'Sets,counting and calculation', 'Hulgad,loendamine ja arvutamine');
call update_translations('SUBTOPIC_TEEMAKAARDI_KOOSTAMINE', 'Teemakaardi koostamine', 'Compilation of thematic map', 'Teemakaardi koostamine');
call update_translations('TOPIC_KUNSTITEOSE_VAATLEMINE_JA_VESTLUS', 'Kunstiteose vaatlemine ja vestlus', 'Observation of art and conversation', 'Kunstiteose vaatlemine ja vestlus');
call update_translations('TOPIC_KÕNELEMINE', 'Kõnelemine', 'Speaking', 'Kõnelemine');
call update_translations('TOPIC_EESTI_KULTUURI_TUTVUSTAMINE', 'Eesti kultuuri tutvustus', 'Introduction of Estonian culture', 'Eesti kultuuri tutvustus');
call update_translations('SUBTOPIC_MUINASJUTUD', 'Muinasjutud', 'Fairytales', 'Muinasjutud');
call update_translations('SUBTOPIC_RIIGID_JA_NENDE_KULTUUR', 'Riigid ja nende kultuur', 'Countries and their culture', 'Riigid ja nende kultuur');
call update_translations('TOPIC_LUGEMINE_JA_KIRJUTAMINE_LASTEKIRJANDUS', 'Lugemine ja kirjutamine lastekirjandus', 'Reading and  writing children literature', 'Lugemine ja kirjutamine lastekirjandus');
call update_translations('SUBTOPIC_EESTI_JA_MAAILM', 'Eesti ja maailm', 'Estonia and world', 'Eesti ja maailm');
call update_translations('SUBTOPIC_KIRJANDUSTEOSE_LEIDMINE', 'Kirjandusteose leidmine', 'Finding literature', 'Kirjandusteose leidmine');
call update_translations('SUBTOPIC_VIRTUAALKESKKOND', 'Virtuaalkeskkond', 'Virtual environment', 'Virtuaalkeskkond');
call update_translations('SUBTOPIC_ROLLIMÄNG', 'Rollimäng', 'Role play', 'Rollimäng');
call update_translations('SUBTOPIC_OHUALLIKAD_JA_OHUTU_KÄITUMINE', 'Ohuallikad ja ohutu käitumine', 'Sources of danger and safe behaviour', 'Ohuallikad ja ohutu käitumine');
call update_translations('TOPIC_SUHTLEMINE_JUTUSTAMINE_JA_KUULAMINE', 'Suhtlemine, jutustamine ja kuulamine', 'Communication,narration and listening', 'Suhtlemine, jutustamine ja kuulamine');
call update_translations('SUBTOPIC_MINA_JA_TEISED', 'Mina ja teised', 'Me and others', 'Mina ja teised');
call update_translations('TOPIC_PÕHILIIKUMISED', 'Põhiliikumised', 'Main movements', 'Põhiliikumised');


call update_translations('DOMAIN_TERVISHOID', 'Tervishoid', 'Healthcare', 'Tervishoid');
call update_translations('KERGETÖÖSTUS', 'Kergetööstus', 'Light industry', 'Kergetööstus');
call update_translations('DOMAIN_PÕLLUMAJANDUS_METSANDUS_JA_KALANDUS', 'Põllumajandus,metsandus ja kalandus', 'Agriculture,forestry and fishery', 'Põllumajandus,metsandus ja kalandus');
call update_translations('SUBTOPIC_HÄÄLIKUSÜSTEEM_JA_ASTMEVAHELDUS', 'Häälikusüsteem ja astmevaheldus', 'Phonetics', 'Häälikusüsteem ja astmevaheldus');
call update_translations('DOMAIN_RIIGIKAITSE', 'Riigkaitse', 'National defence', 'Riigkaitse');
call update_translations('SUBTOPIC_KEELEKASUTUSE_VALDKONNAD', 'Keelekasutuse valdkonnad', 'Areas of language use', 'Keelekasutuse valdkonnad');
call update_translations('SUBTOPIC_ÜTE', 'Üte', 'Üte', 'Üte');
call update_translations('DOMAIN_SISEKAITSE', 'Sisekaitse', 'Internal defence', 'Sisekaitse');
call update_translations('DOMAIN_TEHNIKA_TOOTMINE_JA_TEHNOLOOGIA', 'Tehnika tootmine ja tehnoloogia', 'Production and technology', 'Tehnika tootmine ja tehnoloogia');
call update_translations('SUBTOPIC_KEELE_ÜLESANDED,_MÄRGISÜSTEEM', 'Keele ülesanded, märgisüsteem', 'Language purpose and signsystem', 'Keele ülesanded, märgisüsteem');
call update_translations('SUBTOPIC_KÕRV,_KUULMIS-_JA_TASAKAALUMEEL', 'Kõrv,kuulmis- ja tasakaalumeel', 'Ear,hearing and balance sensation', 'Kõrv,kuulmis- ja tasakaalumeel');

delete from Translation where translationKey = 'SUBTOPIC_��TE';


SET foreign_key_checks = 1;
