-- EstCore Taxon mapping

INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1, 1, 'preschoolEducation');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (2, 2, 'basicEducation');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (3, 3, 'secondaryEducation');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (4, 4, 'vocationalEducation');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (100, 100, 'Mina ja keskkond');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (101, 101, 'Keel ja kõne');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (102, 102, 'Eesti keel kui teine keel');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (103, 103, 'Matemaatika');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (104, 104, 'Kunst');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (105, 105, 'Muusika');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (106, 106, 'Liikumine');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (107, 107, 'Language and literature');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (108, 108, 'Foreign language');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (109, 109, 'Mathematics');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (110, 110, 'Natural sciences');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (111, 111, 'Social studies');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (112, 112, 'Arts');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (113, 113, 'Technology');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (114, 114, 'Physical education');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (115, 115, 'Electives');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (116, 116, 'Cross-curricular themes');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (117, 117, 'Key competences');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (118, 118, 'Language and literature');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (119, 119, 'Foreign language');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (120, 120, 'Mathematics');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (121, 121, 'Natural sciences');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (122, 122, 'Social studies');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (123, 123, 'Arts');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (124, 124, 'Physical education');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (125, 125, 'Electives');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (126, 126, 'Cross-curricular themes');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (127, 127, 'Key competences');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (129, 129, 'Computer Science');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1000, 1000, 'Estonian');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1001, 1001, 'Russian');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1002, 1002, 'Literature');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1003, 1003, 'Estonian');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1004, 1004, 'English');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1005, 1005, 'French');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1006, 1006, 'German');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1007, 1007, 'Russian');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1008, 1008, 'Swedish');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1009, 1009, 'Finnish');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1010, 1010, 'Latin');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1011, 1011, 'Chinese');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1012, 1012, 'Japanese');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1013, 1013, 'Other');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1014, 1014, 'Mathematics');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1015, 1015, 'Science');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1016, 1016, 'Biology');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1017, 1017, 'Geography');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1018, 1018, 'Physics');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1019, 1019, 'Chemistry');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1020, 1020, 'Human studies');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1021, 1021, 'History');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1022, 1022, 'Civics and citizenship');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1023, 1023, 'Art');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1024, 1024, 'Music');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1025, 1025, 'Technology');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1026, 1026, 'Handicraft');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1027, 1027, 'Home economics');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1028, 1028, 'Physical education');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1029, 1029, 'Religious studies');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1030, 1030, 'Informatics');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1031, 1031, 'Career studies');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1032, 1032, 'Economics and business studies');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1033, 1033, 'Other');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1034, 1034, 'Lifelong learning and career planning');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1035, 1035, 'Environment and sustainable development');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1036, 1036, 'Civic initiative and entrepreneurship');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1037, 1037, 'Cultural identity');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1038, 1038, 'Information environment');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1039, 1039, 'Technology and innovation');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1040, 1040, 'Health and safety');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1041, 1041, 'Values and moral');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1042, 1042, 'Cultural and value competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1043, 1043, 'Social and citizenship competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1044, 1044, 'Self management competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1045, 1045, 'Learning to learn competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1046, 1046, 'Communication competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1047, 1047, 'Mathematics natural sciences and technology competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1048, 1048, 'Entrepreneurship competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1049, 1049, 'Digital competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1050, 1050, 'Estonian');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1051, 1051, 'Russian');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1052, 1052, 'Literature');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1053, 1053, 'Estonian');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1054, 1054, 'English');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1055, 1055, 'French');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1056, 1056, 'German');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1057, 1057, 'Russian');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1058, 1058, 'Swedish');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1059, 1059, 'Finnish');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1060, 1060, 'Latin');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1061, 1061, 'Chinese');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1062, 1062, 'Japanese');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1063, 1063, 'Other');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1064, 1064, 'Mathematics');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1065, 1065, 'Science');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1066, 1066, 'Biology');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1067, 1067, 'Geography');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1068, 1068, 'Physics');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1069, 1069, 'Chemistry');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1070, 1070, 'Human studies');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1071, 1071, 'History');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1072, 1072, 'Civics and citizenship');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1073, 1073, 'Art');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1074, 1074, 'Music');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1078, 1078, 'Physical education');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1079, 1079, 'Religious studies');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1080, 1080, 'Informatics');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1081, 1081, 'Career studies');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1082, 1082, 'Economics and business studies');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1083, 1083, 'Media studies');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1084, 1084, 'National defence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1085, 1085, 'Basics of inquiry');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1086, 1086, 'Philosophy');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1087, 1087, 'Other');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1088, 1088, 'Lifelong learning and career planning');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1089, 1089, 'Environment and sustainable development');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1090, 1090, 'Civic initiative and entrepreneurship');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1091, 1091, 'Cultural identity');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1092, 1092, 'Information environment');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1093, 1093, 'Technology and innovation');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1094, 1094, 'Health and safety');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1095, 1095, 'Values and moral');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1096, 1096, 'Cultural and value competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1097, 1097, 'Social and citizenship competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1098, 1098, 'Self management competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1099, 1099, 'Learning to learn competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1100, 1100, 'Communication competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1101, 1101, 'Mathematics natural sciences and technology competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1102, 1102, 'Entrepreneurship competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (1103, 1103, 'Digital competence');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (10000, 10000, 'Ajaloo algõpetus');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (10001, 10001, 'Eesti ajalugu');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (10100, 10100, 'Preschool Topic1');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (10101, 10101, 'Preschool Topic2');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (10200, 10200, 'Secondary Education Topic1');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (10201, 10201, 'Secondary Education Topic2');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (15000, 15000, 'Ajaarvamine');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (15001, 15001, 'Ajalooallikad');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (15002, 15002, 'Eluolu');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (15003, 15003, 'Ajaloosündmused ja ajaloolised isikud');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (15010, 15010, 'Muinasaeg');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (15011, 15011, 'Tähtsamad arheloogilised kultuurid');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (15012, 15012, 'Eesti ühiskonf muinasaja lõpul');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (15013, 15013, 'Keskaeg');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (15020, 15020, 'Subtopic for Preschool Topic1');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (15030, 15030, 'Subtopic for Secondary Education_Topic1');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (20000, 20000, 'Computers and Networks');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (20100, 20100, 'Majanduse alused');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (20101, 20101, 'Ettevõtluse alused');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (20102, 20102, 'Õiguse alused');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (20103, 20103, 'IT õigus');
INSERT INTO EstCoreTaxonMapping (id, taxon, name) VALUES (20104, 20104, 'Kommunikatsioon');

-- Waramu Taxon mapping - for testing purposes

INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1, 1, 'PRESCHOOLEDUCATION');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (2, 2, 'COMPULSORYEDUCATION');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (3, 3, 'SECONDARYEDUCATION');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (4, 4, 'VOCATIONALEDUCATION');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (100, 100, 'Me_and_the_environment');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (101, 101, 'Language_and_speech');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (102, 102, 'Estonian');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (103, 103, 'Mathematics');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (104, 104, 'Arts');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (105, 105, 'Music');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (106, 106, 'Movement');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (107, 107, 'Language_and_literature');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (108, 108, 'Foreign_language');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (109, 109, 'Mathematics');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (110, 110, 'Natural_sciences');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (111, 111, 'Social_studies');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (112, 112, 'Arts');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (113, 113, 'Technology');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (114, 114, 'Physical_education');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (115, 115, 'Electives');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (116, 116, 'Cross-curricular_themes');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (117, 117, 'Key_competences');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (118, 118, 'Language_and_literature');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (119, 119, 'Foreign_language');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (120, 120, 'Mathematics');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (121, 121, 'Natural_sciences');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (122, 122, 'Social_studies');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (123, 123, 'Arts');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (124, 124, 'Physical_education');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (125, 125, 'Electives');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (126, 126, 'Cross-curricular_themes');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (127, 127, 'Key_competences');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (129, 129, 'Computer_science');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1000, 1000, 'Estonian');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1001, 1001, 'Russian');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1002, 1002, 'Literature');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1003, 1003, 'Estonian');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1004, 1004, 'English');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1005, 1005, 'French');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1006, 1006, 'German');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1007, 1007, 'Russian');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1008, 1008, 'Swedish');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1009, 1009, 'Finnish');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1010, 1010, 'Latin');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1011, 1011, 'Chinese');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1012, 1012, 'Japanese');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1013, 1013, 'Other');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1014, 1014, 'Mathematics');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1015, 1015, 'Science');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1016, 1016, 'Biology');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1017, 1017, 'Geography');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1018, 1018, 'Physics');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1019, 1019, 'Chemistry');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1020, 1020, 'Human_studies');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1021, 1021, 'History');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1022, 1022, 'Civics_and_citizenship');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1023, 1023, 'Art');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1024, 1024, 'Music');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1025, 1025, 'Technology');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1026, 1026, 'Handicraft');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1027, 1027, 'Home_economics');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1028, 1028, 'Physical_education');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1029, 1029, 'Religious_studies');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1030, 1030, 'Informatics');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1031, 1031, 'Career_studies');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1032, 1032, 'Economics_and_business_studies');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1033, 1033, 'Other');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1034, 1034, 'Lifelong_learning_and_career_planning');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1035, 1035, 'Environment_and_sustainable_development');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1036, 1036, 'Civic_initiative_and_entrepreneurship');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1037, 1037, 'Cultural_identity');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1038, 1038, 'Information_environment');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1039, 1039, 'Technology_and_innovation');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1040, 1040, 'Health_and_safety');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1041, 1041, 'Values_and_moral');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1042, 1042, 'Cultural_and_value_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1043, 1043, 'Social_and_citizenship_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1044, 1044, 'Self_management_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1045, 1045, 'Learning_to_learn_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1046, 1046, 'Communication_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1047, 1047, 'Mathematics_natural_sciences_and_technology_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1048, 1048, 'Entrepreneurship_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1049, 1049, 'Digital_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1050, 1050, 'Estonian');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1051, 1051, 'Russian');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1052, 1052, 'Literature');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1053, 1053, 'Estonian');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1054, 1054, 'English');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1055, 1055, 'French');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1056, 1056, 'German');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1057, 1057, 'Russian');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1058, 1058, 'Swedish');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1059, 1059, 'Finnish');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1060, 1060, 'Latin');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1061, 1061, 'Chinese');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1062, 1062, 'Japanese');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1063, 1063, 'Other');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1064, 1064, 'Mathematics');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1065, 1065, 'Science');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1066, 1066, 'Biology');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1067, 1067, 'Geography');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1068, 1068, 'Physics');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1069, 1069, 'Chemistry');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1070, 1070, 'Human_studies');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1071, 1071, 'History');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1072, 1072, 'Civics_and_citizenship');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1073, 1073, 'Art');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1074, 1074, 'Music');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1078, 1078, 'Physical_education');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1079, 1079, 'Religious_studies');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1080, 1080, 'Informatics');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1081, 1081, 'Career_studies');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1082, 1082, 'Economics_and_business_studies');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1083, 1083, 'Media_studies');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1084, 1084, 'National_defence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1085, 1085, 'Basics_of_inquiry');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1086, 1086, 'Philosophy');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1087, 1087, 'Other');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1088, 1088, 'Lifelong_learning_and_career_planning');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1089, 1089, 'Environment_and_sustainable_development');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1090, 1090, 'Civic_initiative_and_entrepreneurship');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1091, 1091, 'Cultural_identity');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1092, 1092, 'Information_environment');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1093, 1093, 'Technology_and_innovation');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1094, 1094, 'Health_and_safety');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1095, 1095, 'Values_and_moral');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1096, 1096, 'Cultural_and_value_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1097, 1097, 'Social_and_citizenship_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1098, 1098, 'Self_management_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1099, 1099, 'Learning_to_learn_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1100, 1100, 'Communication_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1101, 1101, 'Mathematics_natural_sciences_and_technology_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1102, 1102, 'Entrepreneurship_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (1103, 1103, 'Digital_competence');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (10000, 10000, 'Basic_history');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (10001, 10001, 'Estonian_history');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (10100, 10100, 'Preschool_Topic1');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (10101, 10101, 'Preschool_Topic2');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (10200, 10200, 'Secondary_Education_Topic1');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (10201, 10201, 'Secondary_Education_Topic2');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (15000, 15000, 'Ajaarvamine');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (15001, 15001, 'Ajalooallikad');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (15002, 15002, 'Eluolu');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (15003, 15003, 'Ajaloosündmused_ja_ajaloolised_isikud');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (15010, 15010, 'Muinasaeg');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (15011, 15011, 'Tähtsamad_arheloogilised_kultuurid');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (15012, 15012, 'Eesti_ühiskonf_muinasaja_lõpul');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (15013, 15013, 'Keskaeg');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (20000, 20000, 'Computers_and_Networks');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (20100, 20100, 'Majanduse_alused');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (20101, 20101, 'Ettevõtluse_alused');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (20102, 20102, 'Õiguse_alused');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (20103, 20103, 'IT_õigus');
INSERT INTO WaramuTaxonMapping (id, taxon, name) VALUES (20104, 20104, 'Kommunikatsioon');

