-- Estonian translations
insert into Translation(translationGroup, translationKey, translation) values (1, 'LOGIN', 'Logi sisse');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MATERIAL_VIEW_SUBJECT', 'Teema');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MATERIAL_VIEW_RESOURCE_TYPE', 'Tüüp');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MATERIAL_VIEW_EDUCATIONAL_CONTEXT', 'Vanuserühmadele');
insert into Translation(translationGroup, translationKey, translation) values (1, 'UPDATED', 'Uuendatud');
insert into Translation(translationGroup, translationKey, translation) values (1, 'CREATED', 'Loodud');
insert into Translation(translationGroup, translationKey, translation) values (1, 'REPOSITORY_NUMBER', 'Repositooriumi number');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MATERIAL_VIEW_LICENSE_TYPE', 'Litsentsi tüüp');
insert into Translation(translationGroup, translationKey, translation) values (1, 'AUDIO', 'Audio');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DATA', 'Andmed');
insert into Translation(translationGroup, translationKey, translation) values (1, 'IMAGE', 'Pilt');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TEXT', 'Tekst');
insert into Translation(translationGroup, translationKey, translation) values (1, 'VIDEO', 'Video');
insert into Translation(translationGroup, translationKey, translation) values (1, 'APPLICATION', 'Rakendus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ASSESSEMENT', 'Hinnang');
insert into Translation(translationGroup, translationKey, translation) values (1, 'BROADCAST', 'Saade');
insert into Translation(translationGroup, translationKey, translation) values (1, 'CASESTUDY', 'Juhtumiuuring');
insert into Translation(translationGroup, translationKey, translation) values (1, 'COURSE', 'Kursus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DEMONSTRATION', 'Näide');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DRILLANDPRACTICE', 'Drilli ja harjuta');
insert into Translation(translationGroup, translationKey, translation) values (1, 'EDUCATIONALGAME', 'Hariv mäng');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ENQUIRYORIENTEDACTIVITY', 'Mõtlema panev tegevus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'EXPERIMENT', 'Katse');
insert into Translation(translationGroup, translationKey, translation) values (1, 'EXPLORATION', 'Avastamine');
insert into Translation(translationGroup, translationKey, translation) values (1, 'GLOSSARY', 'Sõnastik');
insert into Translation(translationGroup, translationKey, translation) values (1, 'GUIDE', 'Juhend');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LESSONPLAN', 'Tunniplaan');
insert into Translation(translationGroup, translationKey, translation) values (1, 'OPENACTIVITY', 'Avatud tegevus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'OTHER', 'Muu');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PRESENTATION', 'Ettekanne');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PROJECT', 'Projekt');
insert into Translation(translationGroup, translationKey, translation) values (1, 'REFERENCE', 'Viide');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ROLEPLAY', 'Rollimäng');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SIMULATION', 'Simulatsioon');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TEXTBOOK', 'Õpik');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TOOL', 'Tööriist');
insert into Translation(translationGroup, translationKey, translation) values (1, 'WEBSITE', 'Veebileht');
insert into Translation(translationGroup, translationKey, translation) values (1, 'BOOKMARKSHARINGPLATFORM', 'Järjehoidja jagamise platvorm');
insert into Translation(translationGroup, translationKey, translation) values (1, 'IMAGESHARINGPLATFORM', 'Pildi jagamise platvorm');
insert into Translation(translationGroup, translationKey, translation) values (1, 'REFERENCESHARINGPLATFORM', 'Viite jagamise platvorm');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SOUNDSHARINGPLATFORM', 'Heli jagamise platvorm');
insert into Translation(translationGroup, translationKey, translation) values (1, 'VIDEOSHARINGPLATFORM', 'Video jagamise platvorm');
insert into Translation(translationGroup, translationKey, translation) values (1, 'WEBLOG', 'veebilogi');
insert into Translation(translationGroup, translationKey, translation) values (1, 'WIKI', 'viki');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PRESCHOOL', 'Eelkool');
insert into Translation(translationGroup, translationKey, translation) values (1, 'COMPULSORYEDUCATION', 'Kohustuslik haridus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'VOCATIONALEDUCATION', 'Kutseharidus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'HIGHEREDUCATION', 'Kõrgharidus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'CONTINUINGEDUCATION', 'Täiendõpe');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PROFESSIONALDEVELOPMENT', 'Erialana areng');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SPECIALEDUCATION', 'Eripdagoogika');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MATERIAL_VIEW_LINK_TO_MATERIAL', 'Ava õppematerjal');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PUBLISHER', 'Kirjastaja');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PUBLISHERS', 'Kirjastajad');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SEARCH', 'Otsi');
insert into Translation(translationGroup, translationKey, translation) values (1, 'UNKNOWN', 'Teadmata');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ABOUT_PAGE_LINK_TITLE', 'Mis see on?');
insert into Translation(translationGroup, translationKey, translation) values (1, 'HELP_PAGE_LINK_TITLE', 'Kuidas eKoolikotti kasutada?');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LANDING_PAGE_TITLE_NEWEST', 'Uusimad');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_ALLRIGHTSRESERVED', 'Kõik õigused kaitstud');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_CCBY', 'CC BY');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_CCBYSA', 'CC BY-SA');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_CCBYND', 'CC BY-ND');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_CCBYNC', 'CC BY-NC');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_CCBYNCSA', 'CC BY-NC-SA');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_CCBYNCND', 'CC BY-NC-ND');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_OTHER', 'Muu');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MATERIAL_VIEW_KEYWORDS', 'Võtmesõnad');


