-- Estonian translations
INSERT INTO Translation(translationGroup, translationKey, translation) VALUES 
(1,'ABOUT_PAGE_LINK_TITLE','Mis on e-Koolikott?'),
(1,'ADDED','Lisatud'),
(1,'ADD_COMMENT_BUTTON','Saada'),
(1,'ADD_COMMENT_TITLE','Lisa kommentaar'),
(1,'ADD_MATERIAL','Lisa materjal'),
(1,'ADD_PORTFOLIO','Lisa kogumik'),
(1,'ADD_PORTFOLIO_PRESS_ENTER','Lisa märksõna ja vajuta Enter'),
(1,'ADD_PORTFOLIO_REMOVE_TAG','Eemalda märksõna'),
(1,'ADD_PORTFOLIO_REMOVE_TAG_HINT','Märksõna eemaldamiseks vajuta x-ile'),
(1,'ADD_PORTFOLIO_TAGS','Märksõnad'),
(1,'ALERT_CONFIRM_NEGATIVE','Ei'),
(1,'ALERT_CONFIRM_POSITIVE','Jah'),
(1,'APPLICATION','Rakendus'),
(1,'ASSESSMENT','Hindamisvahend'),
(1,'AUDIO','Heli'),
(1,'AUTHORS','Autorid'),
(1,'BASICEDUCATION','Põhiharidus'),
(1,'BOOKMARKSHARINGPLATFORM','Järjehoidjakogu'),
(1,'BROADCAST','Saade'),
(1,'BUTTON_ADD','Lisa'),
(1,'BUTTON_CANCEL','Katkesta'),
(1,'BUTTON_CREATE_MATERIAL','Lisa materjal'),
(1,'BUTTON_CREATE_PORTFOLIO','Loo kogumik'),
(1,'BUTTON_EDIT_PORTFOLIO','Salvesta'),
(1,'BUTTON_NEXT_STEP','Järgmine samm'),
(1,'BUTTON_NOTIFY','Teavita'),
(1,'BUTTON_PREVIOUS_STEP','Eelmine samm'),
(1,'BUTTON_REMOVE','Kustuta'),
(1,'BUTTON_REPORT','Anna teada'),
(1,'CASESTUDY','Juhtum'),
(1,'COMMENT','Kommentaar'),
(1,'COMMENTS_TITLE','Kommentaarid'),
(1,'CONTINUINGEDUCATION','Elukestev õpe'),
(1,'COPYRIGHT_FOOTER','© 2016 Kõik õigused kaitstud. Haridus- ja Teadusministeerium'),
(1,'COPY_PORTFOLIO','Kopeeri kogumik'),
(1,'COPY_URL','Kopeeri link'),
(1,'COURSE','Kursus'),
(1,'CREATED','Loodud'),
(1,'CREATOR','Lisaja'),
(1,'CROSS_CURRICULAR_THEME_CIVIC_INITIATIVE_AND_ENTREPRENEURSHIP','Kodanikualgatus ja ettevõtlikkus'),
(1,'CROSS_CURRICULAR_THEME_CULTURAL_IDENTITY','Kultuuriline identiteet'),
(1,'CROSS_CURRICULAR_THEME_ENVIRONMENT_AND_SUSTAINABLE_DEVELOPMENT','Keskkond ja jätkusuutlik areng'),
(1,'CROSS_CURRICULAR_THEME_HEALTH_AND_SAFETY','Tervis ja ohutus'),
(1,'CROSS_CURRICULAR_THEME_INFORMATION_ENVIRONMENT','Teabekeskkond'),
(1,'CROSS_CURRICULAR_THEME_LIFELONG_LEARNING_AND_CAREER_PLANNING','Elukestev õpe ja karjääri planeerimine'),
(1,'CROSS_CURRICULAR_THEME_TECHNOLOGY_AND_INNOVATION','Tehnoloogia ja innovatsioon'),
(1,'CROSS_CURRICULAR_THEME_VALUES_AND_MORAL','Väärtused ja kõlblus'),
(1,'DATA','Andmestik'),
(1,'DEMONSTRATION','Demo'),
(1,'DETAILED_SEARCH_ALL','Kogu õppevara'),
(1,'DETAILED_SEARCH_AUTHOR','Autor'),
(1,'DETAILED_SEARCH_CLEAR','Tühista valikud'),
(1,'DETAILED_SEARCH_CLIL','Lõimitud aine- ja keeleõpe'),
(1,'DETAILED_SEARCH_CROSS_CURRICULAR_THEME','Läbivad teemad'),
(1,'DETAILED_SEARCH_DESCRIPTION','Kirjeldus'),
(1,'DETAILED_SEARCH_INCLUDE_PAID','Tasulised materjalid'),
(1,'DETAILED_SEARCH_ISSUE_DATE_FROM','Välja antud'),
(1,'DETAILED_SEARCH_ISSUE_DATE_OR_LATER',' või hiljem.'),
(1,'DETAILED_SEARCH_KEY_COMPETENCE','Üldpädevused'),
(1,'DETAILED_SEARCH_MAIN','Põhiväli'),
(1,'DETAILED_SEARCH_MATERIALS','Vaid õppematerjalid'),
(1,'DETAILED_SEARCH_OFF','Ei'),
(1,'DETAILED_SEARCH_ON','Jah'),
(1,'DETAILED_SEARCH_ONLY_BOOKS','Ainult õppekirjandus'),
(1,'DETAILED_SEARCH_OPEN','Täpne otsing'),
(1,'DETAILED_SEARCH_PORTFOLIOS','Vaid kogumikud'),
(1,'DETAILED_SEARCH_SPECIAL_EDUCATION','Lihtsustatud õppekava'),
(1,'DETAILED_SEARCH_SPECIAL_EDUCATIONAL_NEED','Hariduslik erivajadus'),
(1,'DETAILED_SEARCH_SUBMIT','Otsi'),
(1,'DETAILED_SEARCH_TARGET_GROUP','Vanus'),
(1,'DETAILED_SEARCH_TITLE','Pealkiri'),
(1,'DETAIL_VIEW_EDUCATIONAL_CONTEXT','Haridus'),
(1,'DETAIL_VIEW_SUBJECT','Õppeaine'),
(1,'DETAIL_VIEW_TAGS','Võtmesõnad'),
(1,'DOMAIN_ARTS','Kunst'),
(1,'DOMAIN_COMPUTER_SCIENCE','Informaatika'),
(1,'DOMAIN_CROSS-CURRICULAR_THEMES','Läbivad teemad'),
(1,'DOMAIN_ELECTIVES','Valikõppeained'),
(1,'DOMAIN_FOREIGN_LANGUAGE','Võõrkeel'),
(1,'DOMAIN_KEY_COMPETENCES','Üldpädevused'),
(1,'DOMAIN_LANGUAGE_AND_LITERATURE','Keel ja kirjandus'),
(1,'DOMAIN_LANGUAGE_AND_SPEECH','Keel ja kõne'),
(1,'DOMAIN_MATHEMATICS','Matemaatika'),
(1,'DOMAIN_NATURAL_SCIENCES','Loodusained'),
(1,'DOMAIN_PHYSICAL_EDUCATION','Kehaline kasvatus'),
(1,'DOMAIN_SOCIAL_STUDIES','Sotsiaalained'),
(1,'DOMAIN_TECHNOLOGY','Tehnoloogia'),
(1,'DRILLANDPRACTICE','Harjutus'),
(1,'EDIT_PORTFOLIO','Muuda kogumikku'),
(1,'EDUCATIONALGAME','Mäng'),
(1,'ENQUIRYORIENTEDACTIVITY','Uurimus'),
(1,'ERROR_GETTING_USER_FAILED','Kasutajat ei leitud'),
(1,'ERROR_LOGIN_FAILED','Sisenemine ebaõnnestus'),
(1,'ERROR_MATERIAL_NOT_FOUND','Materjali ei leitud'),
(1,'ERROR_PORTFOLIO_NOT_FOUND','Kogumikku ei leitud'),
(1,'EXPERIMENT','Katse'),
(1,'EXPLORATION','Avastuslik'),
(1,'GLOSSARY','Sõnastik'),
(1,'GUIDE','Juhis'),
(1,'HELP_PAGE_LINK_TITLE','Kuidas e-Koolikotti kasutada?'),
(1,'HIGHEREDUCATION','Kõrgharidus'),
(1,'IMAGE','Pilt'),
(1,'IMAGESHARINGPLATFORM','Pildiait'),
(1,'KEY_COMPETENCE_COMMUNICATION_COMPETENCE','Suhtluspädevus'),
(1,'KEY_COMPETENCE_CULTURAL_AND_VALUE_COMPETENCE','Kultuuri- ja väärtuspädevus'),
(1,'KEY_COMPETENCE_DIGITAL_COMPETENCE','Digipädevus'),
(1,'KEY_COMPETENCE_ENTREPRENEURSHIP_COMPETENCE','Ettevõtlikkuspädevus'),
(1,'KEY_COMPETENCE_LEARNING_TO_LEARN_COMPETENCE','Õpipädevus'),
(1,'KEY_COMPETENCE_MATHEMATICS_NATURAL_SCIENCES_AND_TECHNOLOGY_COMPETENCE','Matemaatika-, loodusteaduste- ja tehnoloogiaalane pädevus'),
(1,'KEY_COMPETENCE_SELF_MANAGEMENT_COMPETENCE','Enesemääratluspädevus'),
(1,'KEY_COMPETENCE_SOCIAL_AND_CITIZENSHIP_COMPETENCE','Sotsiaalne ja kodanikupädevus'),
(1,'LANDING_PAGE_TITLE_NEWEST','Uuemad'),
(1,'LANDING_PAGE_TITLE_POPULAR','Populaarsemad'),
(1,'LANGUAGE','Keel'),
(1,'LANGUAGE_ENG','Inglise'),
(1,'LANGUAGE_EST','Eesti'),
(1,'LANGUAGE_RUS','Vene'),
(1,'LESSONPLAN','Tunnikava'),
(1,'LICENSETYPE_ALLRIGHTSRESERVED','Kõik õigused kaitstud'),
(1,'LICENSETYPE_CCBY','CC BY'),
(1,'LICENSETYPE_CCBYNC','CC BY-NC'),
(1,'LICENSETYPE_CCBYNCND','CC BY-NC-ND'),
(1,'LICENSETYPE_CCBYNCSA','CC BY-NC-SA'),
(1,'LICENSETYPE_CCBYND','CC BY-ND'),
(1,'LICENSETYPE_CCBYSA','CC BY-SA'),
(1,'LICENSETYPE_OTHER','Muu'),
(1,'LOGIN','Sisene'),
(1,'LOGIN_CHOOSE_LOGIN_METHOD','Vali sisenemise viis'),
(1,'LOGIN_FACEBOOK','Facebook'),
(1,'LOGIN_GOOGLE','Google'),
(1,'LOGIN_IDCARD','ID-kaart'),
(1,'LOGIN_MOBILEID','Mobiil-ID'),
(1,'LOGIN_MOBILEID_CODE','Sinu kood on'),
(1,'LOGIN_SMS','Kontrollige, et SMSi teel saabunud kontrollkood ühtiks arvutiekraanil näidatuga.'),
(1,'LOGIN_TAAT','TAAT'),
(1,'LOGOUT','Välju'),
(1,'MATERIAL_ADDITIONAL_DATA','Lisaandmed'),
(1,'MATERIAL_ADD_TAG','Lisa märksõna'),
(1,'MATERIAL_AUTHOR_NAME','Autori eesnimi'),
(1,'MATERIAL_AUTHOR_SURNAME','Autori perekonnanimi'),
(1,'MATERIAL_CONFIRM_DELETE_DIALOG_CONTENT','Kas oled kindel, et soovid kustutada selle materjali?'),
(1,'MATERIAL_CONFIRM_DELETE_DIALOG_TITLE','Kustuta materjal'),
(1,'MATERIAL_CROSS_CURRICULAR_THEMES','Läbivad teemad'),
(1,'MATERIAL_DELETE','Kustuta materjal'),
(1,'MATERIAL_DELETED','Materjal kustutatud'),
(1,'MATERIAL_DESCRIPTION','Kirjeldus'),
(1,'MATERIAL_DISLIKED','Ei soovita materjali'),
(1,'MATERIAL_HOW_TO_SAVE_TAG','Märksõna sisestamiseks vajuta enterit'),
(1,'MATERIAL_KEY_COMPETENCES','Üldpädevused'),
(1,'MATERIAL_LIKED','Soovitan materjali'),
(1,'MATERIAL_PAID','Tasuline'),
(1,'MATERIAL_PHOTO','Materjali pilt'),
(1,'PHOTO_PREVIEW','Eelvaade'),
(1,'MATERIAL_PHOTO_UPLOAD_HELP','Lohista pilt siia või vali pilt arvutist'),
(1,'MATERIAL_PUBLISHER','Väljaandja'),
(1,'MATERIAL_REMOVE_TAG','Eemalda märksõna'),
(1,'MATERIAL_REMOVE_TAG_HINT','Vajuta x märksõna kustutamiseks'),
(1,'MATERIAL_SEARCH_CROSS_CURRICULAR_THEME','Otsi läbivaid teemasid'),
(1,'MATERIAL_SEARCH_KEY_COMPETENCE','Otsi üldpädevusi'),
(1,'MATERIAL_TAB_ADDITIONAL_DATA','Lisaandmed'),
(1,'MATERIAL_TAB_ADD_TAXON','Lisa liigitus'),
(1,'MATERIAL_TAB_CHOOSE_LICENSE','Vali litsentsi tüüp'),
(1,'MATERIAL_TAB_MAIN_DATA','Põhiandmed'),
(1,'MATERIAL_TAB_NEW_AUTHOR','Lisa veel autoreid'),
(1,'MATERIAL_TAB_NEW_TITLE_AND_DESC','Lisa pealkiri ja kirjeldus uues keeles'),
(1,'MATERIAL_TAB_PICTURE','Pilt'),
(1,'MATERIAL_TAB_PRESS_ENTER_TO_ADD_TAG','Lisa märksõna ja vajuta Enter'),
(1,'MATERIAL_TAB_REMOVE','Eemalda'),
(1,'MATERIAL_TAB_REMOVE_TAXON','Eemalda liigitus'),
(1,'MATERIAL_TAB_TAXON','Liigitus'),
(1,'MATERIAL_TAB_TYPE','Tüüp'),
(1,'MATERIAL_TAB_URL','link'),
(1,'MATERIAL_TAGS','Märksõnad'),
(1,'MATERIAL_TAXON','Liigitus'),
(1,'MATERIAL_TITLE','Pealkiri'),
(1,'MATERIAL_TITLE_DESCRIPTION','Pealkiri ja kirjeldus'),
(1,'MATERIAL_TITLE_IS_MANDATORY','Materjali pealkiri on kohustuslik'),
(1,'MATERIAL_URL','Materjali link'),
(1,'MATERIAL_URL_IS_INVALID','Materjali link ei vasta formaadile'),
(1,'MATERIAL_URL_IS_MANDATORY','Materjali link on kohustuslik'),
(1,'MATERIAL_VIEW_LICENSE_TYPE','Litsentsi tüüp'),
(1,'MATERIAL_VIEW_LINK_TO_MATERIAL','Ava õppematerjal'),
(1,'MATERIAL_VIEW_RESOURCE_TYPE','Tüüp'),
(1,'MATERIAL_LINK','Link'),
(1,'MATERIAL_ISSUE_DATE','Väljaandmise kp'),
(1,'MATERIAL_SPECIAL_EDUCATION', 'Lihtsustatud õppekava'),
(1,'MESSAGE_ERROR_PERSONAL_CODE_INVALID','Isikukood ei ole korrektne'),
(1,'MESSAGE_ERROR_PERSONAL_CODE_REQUIRED','Isikukood on nõutud'),
(1,'MESSAGE_ERROR_PHONE_NUMBER_NOT_ESTONIAN','Telefoninumber peab algama Eesti koodiga'),
(1,'MESSAGE_ERROR_PHONE_NUMBER_REQUIRED','Telefoninumber on nõutud'),
(1,'MYPROFILE_PAGE_TITLE_MATERIALS','Minu lisatud materjalid'),
(1,'MYPROFILE_PAGE_TITLE_MY_DATA','Minu andmed'),
(1,'MYPROFILE_PAGE_TITLE_PORTFOLIOS','Minu kogumikud'),
(1,'MY_PROFILE','Minu asjad'),
(1,'OPENACTIVITY','Avatud õpitegevus'),
(1,'ORIGINAL_CREATOR','Originaalne lisaja'),
(1,'OTHER','Muu'),
(1,'PERSONAL_CODE','Isikukood'),
(1,'PORTFOLIO_ADD_CHAPTER','Lisa peatükk'),
(1,'PORTFOLIO_ADD_MATERIAL','Lisa materjal(id) sellese peatükki'),
(1,'PORTFOLIO_ADD_MATERIAL_SUCCESS','Materjal(id) edukalt lisatud'),
(1,'PORTFOLIO_ADD_SUBCHAPTER','Lisa alampeatükk'),
(1,'PORTFOLIO_ATTACHED_MATERIALS','Lisatud materjalid'),
(1,'PORTFOLIO_AUTOSAVED','Kogumik automaatselt salvestatud'),
(1,'PORTFOLIO_CHAPTERS','Kogumiku peatükid'),
(1,'PORTFOLIO_CHAPTER_CONTENT','Peatüki sisu'),
(1,'PORTFOLIO_CONFIRM_DELETE_DIALOG_CONTENT','Kas oled kindel, et soovid kustutada selle portfoolio?'),
(1,'PORTFOLIO_CONFIRM_DELETE_DIALOG_NO','Ei'),
(1,'PORTFOLIO_CONFIRM_DELETE_DIALOG_TITLE','Kustuta kogumik'),
(1,'PORTFOLIO_CONFIRM_DELETE_DIALOG_YES','Jah, kustuta kogumik'),
(1,'PORTFOLIO_CREATE_NEW_MATERIAL_URL','E-koolikoti välise materiali aadress'),
(1,'PORTFOLIO_DEFAULT_NEW_CHAPTER_TITLE','Uus peatükk'),
(1,'PORTFOLIO_DEFAULT_NEW_SUBCHAPTER_TITLE','Uus alampeatükk'),
(1,'PORTFOLIO_DELETE','Kustuta kogumik'),
(1,'PORTFOLIO_DELETED','Kogumik kustutatud'),
(1,'PORTFOLIO_DELETE_CHAPTER','Kustuta'),
(1,'PORTFOLIO_DELETE_CHAPTER_CONFIRM_MESSAGE','Peatüki kustutamist ei ole võimalik tagasi võtta'),
(1,'PORTFOLIO_DELETE_CHAPTER_CONFIRM_TITLE','Kas oled kindel?'),
(1,'PORTFOLIO_DELETE_SUB_CHAPTER','Kustuta'),
(1,'PORTFOLIO_DELETE_SUB_CHAPTER_CONFIRM_MESSAGE','Alampeatüki kustutamist ei ole võimalik tagasi võtta'),
(1,'PORTFOLIO_DELETE_SUB_CHAPTER_CONFIRM_TITLE','Kas oled kindel?'),
(1,'PORTFOLIO_DISLIKED','Ei soovita kogumikku'),
(1,'PORTFOLIO_EDIT_METADATA','Muuda andmeid'),
(1,'PORTFOLIO_ENTER_CHAPTER_TITLE','Sisesta peatüki pealkiri'),
(1,'PORTFOLIO_ENTER_SUB_CHAPTER_TITLE','Sisesta alampeatüki pealkiri'),
(1,'PORTFOLIO_HAS_BEEN_MADE_PUBLIC','Kõik muutused on nüüd avalikult nähtavad'),
(1,'PORTFOLIO_LIKED','Soovitan kogumikku'),
(1,'PORTFOLIO_MAKE_PRIVATE','Kas soovid muuta kogumiku privaatseks?'),
(1,'PORTFOLIO_METADATA_TOOLBAR_LABEL','Lisa kogumiku põhiandmed'),
(1,'PORTFOLIO_NO','Ei'),
(1,'PORTFOLIO_PHOTO_PREVIEW','Eelvaade'),
(1,'PORTFOLIO_PHOTO_UPLOAD_HELP','Lohista pilt siia või vali pilt arvutist vajutades siia'),
(1,'PORTFOLIO_SAVE','Salvesta kogumik'),
(1,'PORTFOLIO_SAVED','Kogumik salvestatud'),
(1,'PORTFOLIO_SEND_LINK','Saada link'),
(1,'PORTFOLIO_SUB_CHAPTER_CONTENT','Alampeatüki sisu'),
(1,'PORTFOLIO_SUMMARY','Kokkuvõte'),
(1,'PORTFOLIO_TITLE','Pealkiri'),
(1,'PORTFOLIO_TITLE_IS_MANDATORY','Kogumiku pealkiri on kohustuslik'),
(1,'PORTFOLIO_VISIBILITY_MAKE_NOT_LISTED','Jaga ainult lingiga'),
(1,'PORTFOLIO_VISIBILITY_MAKE_PRIVATE','Tee privaatseks'),
(1,'PORTFOLIO_VISIBILITY_MAKE_PUBLIC','Tee avalikuks'),
(1,'PORTFOLIO_VISIBILITY_NOT_LISTED','Ainult lingiga'),
(1,'PORTFOLIO_VISIBILITY_PRIVATE','Privaatne'),
(1,'PORTFOLIO_VISIBILITY_PUBLIC','Avalik'),
(1,'PORTFOLIO_WARNING','Vastasel juhul on kõigile koheselt nähtavad tehtud muudatused.'),
(1,'PORTFOLIO_YES','Jah, Tee kogumik privaatseks'),
(1,'PRESCHOOLEDUCATION','Alusharidus'),
(1,'PRESENTATION','Esitlus'),
(1,'PROFILE_PAGE_TITLE_MATERIALS','Materjalid'),
(1,'PROFILE_PAGE_TITLE_PORTFOLIOS','Kogumikud'),
(1,'PROJECT','Projekt'),
(1,'PUBLISHER','Kirjastaja'),
(1,'PUBLISHERS','Kirjastajad'),
(1,'RATING_DISLIKE','Ei soovita'),
(1,'RATING_DISLIKE_REMOVED','Mittesoovitus eemaldatud'),
(1,'RATING_LIKE','Soovitan'),
(1,'RATING_LIKE_REMOVED','Soovitus eemaldatud'),
(1,'RECOMMEND','Lisa soovituste nimekirja'),
(1,'RECOMMEND_REMOVE','Eemalda soovituste nimekirjast'),
(1,'REFERENCE','Teabeallikas'),
(1,'REFERENCESHARINGPLATFORM','Lingikogu'),
(1,'REPORT_BROKEN_LINK','Teavita katkisest materjalist'),
(1,'REPORT_BROKEN_LINK_CONTENT','Administraatorile saadetakse teavitus katkise materjali kohta.'),
(1,'REPORT_BROKEN_LINK_TITLE','Kas soovid teavitada katkisest materjalist?'),
(1,'REPORT_IMPROPER','Teavita ebasobivast sisust'),
(1,'REPORT_NOT_IMPROPER','Märgi sisu sobivaks'),
(1,'REPORT_IMPROPER_CONTENT','Administraatorile saadetakse teavitus ebasobiva sisu kohta.'),
(1,'REPORT_IMPROPER_TITLE','Kas soovid teavitada ebasobivast sisust?'),
(1,'REPOSITORY_NUMBER','Repositooriumi number'),
(1,'ROLEPLAY','Rollimäng'),
(1,'SEARCH','Otsi'),
(1,'SEARCH_RESULT_1_RESULT_PART_1','Otsingule leidus '),
(1,'SEARCH_RESULT_1_RESULT_PART_2',' vaste.'),
(1,'SEARCH_RESULT_NEXT','Järgmine'),
(1,'SEARCH_RESULT_NO_RESULT','Ühtegi vastet ei leitud.'),
(1,'SEARCH_RESULT_PART_1','Otsingule leidus '),
(1,'SEARCH_RESULT_PART_2',' vastet.'),
(1,'SEARCH_RESULT_PREVIOUS','Eelmine'),
(1,'SEARCH_RESULTS','Otsingu tulemused'),
(1,'SEARCH_LOADING','Laen veel tulemusi...'),
(1,'SECONDARYEDUCATION','Keskharidus'),
(1,'SIMULATION','Simulatsioon'),
(1,'SOUNDSHARINGPLATFORM','Heliait'),
(1,'SPECIALEDUCATION','Lihtsustatud õppekava'),
(1,'SUBJECT_ART','Kunst'),
(1,'SUBJECT_BASICS_OF_INQUIRY','Uurimistöö alused'),
(1,'SUBJECT_BIOLOGY','Bioloogia'),
(1,'SUBJECT_CAREER_STUDIES','Karjääriõpetus'),
(1,'SUBJECT_CHEMISTRY','Keemia'),
(1,'SUBJECT_CHINESE','Hiina keel'),
(1,'SUBJECT_CIVICS_AND_CITIZENSHIP','Ühiskonnaõpetus'),
(1,'SUBJECT_CIVIC_INITIATIVE_AND_ENTREPRENEURSHIP','Kodanikualgatus ja ettevõtlikkus'),
(1,'SUBJECT_COMMUNICATION_COMPETENCE','Suhtluspädevus'),
(1,'SUBJECT_CULTURAL_AND_VALUE_COMPETENCE','Kultuuri- ja väärtuspädevus'),
(1,'SUBJECT_CULTURAL_IDENTITY','Kultuuriline identiteet'),
(1,'SUBJECT_DIGITAL_COMPETENCE','Digipädevus'),
(1,'SUBJECT_ECONOMICS_AND_BUSINESS_STUDIES','Majandus- ja ettevõtlusõpe'),
(1,'SUBJECT_EDUCATIONAL_TECHNOLOGY','Haridustehnoloogia'),
(1,'SUBJECT_ENGLISH','Inglise keel'),
(1,'SUBJECT_ENTREPRENEURSHIP_COMPETENCE','Ettevõtlikkuspädevus'),
(1,'SUBJECT_ENVIRONMENT_AND_SUSTAINABLE_DEVELOPMENT','Keskkond ja säästev areng'),
(1,'SUBJECT_ESTONIAN','Eesti keel'),
(1,'SUBJECT_FINNISH','Soome keel'),
(1,'SUBJECT_FRENCH','Prantsuse keel'),
(1,'SUBJECT_GEOGRAPHY','Geograafia'),
(1,'SUBJECT_GERMAN','Saksa keel'),
(1,'SUBJECT_HANDICRAFT','Käsitöö'),
(1,'SUBJECT_HEALTH_AND_SAFETY','Tervis ja ohutus'),
(1,'SUBJECT_HISTORY','Ajalugu'),
(1,'SUBJECT_HOME_ECONOMICS','Kodundus'),
(1,'SUBJECT_HUMAN_STUDIES','Inimeseõpetus'),
(1,'SUBJECT_INFORMATICS','Informaatika'),
(1,'SUBJECT_INFORMATION_ENVIRONMENT','Teabekeskkond'),
(1,'SUBJECT_JAPANESE','Jaapani keel'),
(1,'SUBJECT_LATIN','Ladina keel'),
(1,'SUBJECT_LEARNING_TO_LEARN_COMPETENCE','Õpipädevus'),
(1,'SUBJECT_LIFELONG_LEARNING_AND_CAREER_PLANNING','Elukestev õpe ja karjääriplaneerimine'),
(1,'SUBJECT_LITERATURE','Kirjandus'),
(1,'SUBJECT_MATHEMATICS','Matemaatika'),
(1,'SUBJECT_MATHEMATICS_NATURAL_SCIENCES_AND_TECHNOLOGY_COMPETENCE','Matemaatika-, loodusteaduste- ja tehnoloogiaalane pädevus'),
(1,'SUBJECT_MEDIA_STUDIES','Meediaõpetus'),
(1,'SUBJECT_MUSIC','Muusika'),
(1,'SUBJECT_NATIONAL_DEFENCE','Riigikaitse'),
(1,'SUBJECT_OTHER','Muu'),
(1,'SUBJECT_PHILOSOPHY','Filosoofia'),
(1,'SUBJECT_PHYSICAL_EDUCATION','Kehaline kasvatus'),
(1,'SUBJECT_PHYSICS','Füüsika'),
(1,'SUBJECT_RELIGIOUS_STUDIES','Usundiõpetus'),
(1,'SUBJECT_RUSSIAN','Vene keel'),
(1,'SUBJECT_SCIENCE','Loodusõpetus'),
(1,'SUBJECT_SELF_MANAGEMENT_COMPETENCE','Enesemääratluspädevus'),
(1,'SUBJECT_SOCIAL_AND_CITIZENSHIP_COMPETENCE','Sotsiaalne ja kodanikupädevus'),
(1,'SUBJECT_SWEDISH','Rootsi keel'),
(1,'SUBJECT_TECHNOLOGY','Tehnoloogiaõpetus'),
(1,'SUBJECT_TECHNOLOGY_AND_INNOVATION','Tehnoloogia ja innovatsioon'),
(1,'SUBJECT_VALUES_AND_MORAL','Väärtused ja moraal'),
(1,'TABLE_OF_CONTENTS','Sisukord'),
(1,'TARGET_GROUP_GRADE1','1. klass'),
(1,'TARGET_GROUP_GRADE2','2. klass'),
(1,'TARGET_GROUP_GRADE3','3. klass'),
(1,'TARGET_GROUP_GRADE4','4. klass'),
(1,'TARGET_GROUP_GRADE5','5. klass'),
(1,'TARGET_GROUP_GRADE6','6. klass'),
(1,'TARGET_GROUP_GRADE7','7. klass'),
(1,'TARGET_GROUP_GRADE8','8. klass'),
(1,'TARGET_GROUP_GRADE9','9. klass'),
(1,'TARGET_GROUP_GYMNASIUM','Gümnaasium'),
(1,'TARGET_GROUP_LEVEL1','I kooliaste'),
(1,'TARGET_GROUP_LEVEL2','II kooliaste'),
(1,'TARGET_GROUP_LEVEL3','III kooliaste'),
(1,'TARGET_GROUP_PRESCHOOL','Koolieelne õppeasutus'),
(1,'TARGET_GROUP_SIX_SEVEN','6-7'),
(1,'TARGET_GROUP_ZERO_FIVE','0-5'),
(1,'TAXON_PATH_DOMAIN','Valdkond'),
(1,'TAXON_PATH_DOMAIN_AND_SUBJECT','Ainevaldkond'),
(1,'TAXON_PATH_MODULE','Moodul'),
(1,'TAXON_PATH_SPECIALIZATION','Eriala'),
(1,'TAXON_PATH_SUBTOPIC','Alateema'),
(1,'TAXON_PATH_TOPIC','Teema'),
(1,'TEACHEREDUCATION','Õpetajaharidus'),
(1,'TEXT','Tekst'),
(1,'TEXTBOOK','Õpik'),
(1,'TOOL','Töövahend'),
(1,'TOPIC_BASIC_HISTORY','Ajaloo algõpetus'),
(1,'TOPIC_ESTONIAN_HISTORY','Eesti ajalugu'),
(1,'UNKNOWN','Teadmata'),
(1,'UPDATED','Uuendatud'),
(1,'VIDEO','Video'),
(1,'VIDEOSHARINGPLATFORM','Videoait'),
(1,'VIEW_COUNT','Vaatamisi'),
(1,'VOCATIONALEDUCATION','Kutseharidus'),
(1,'WEBLOG','Blogi'),
(1,'WEBSITE','Veebileht'),
(1,'WIKI','viki'),
(1,'HEADER_TOOLTIP_GO_TO_LANDING_PAGE','Suundu avalehele'),
(1,'HEADER_TOOLTIP_OPEN_DETAILED_SEARCH','Ava täpne otsing'),
(1,'HEADER_TOOLTIP_CLOSE_DETAILED_SEARCH','Sulge täpne otsing'),
(1,'HEADER_TOOLTIP_SELECT_LANGUAGE','Vali keel'),
(1,'HEADER_TOOLTIP_ENTER','Sisene'),
(1,'HEADER_TOOLTIP_PROFILE','Profiil'),
(1,'HEADER_TOOLTIP_CHANGE_VISIBILITY','Muuda nähtavust'),
(1,'DASHBOARD','Töölaud'),
(1,'DASHBOARD_IMRPOPER_MATERIALS','Ebasobivad materjalid'),
(1,'DASHBOARD_IMRPOPER_PORTFOLIOS','Ebasobivad kogumikud'),
(1,'DASHBOARD_DELETED_MATERIALS','Kustutatud materjalid'),
(1,'DASHBOARD_DELETED_PORTFOLIOS','Kustutatud kogumikud'),
(1,'TITLE','Pealkiri'),
(1,'SUBMITTED_AT','Raporteeritud'),
(1,'SUBMITTED_BY','Raporteeris'),
(1,'BUTTON_OPEN','Ava'),
(1,'BUTTON_RESTORE','Taasta'),
(1,'GIVE_FEEDBACK_LINK','Anna tagasisidet e-Koolikoti kohta'),
(1,'RECOMMENDATIONS','Soovitused'),
(1,'LOAD_MORE_COMMENTS','Veel kommentaare'),
(1,'SELECT_CROSS_CURRICULAR_THEME','Kõik'),
(1,'SELECT_KEY_COMPETENCE','Kõik'),
(1,'SELECT_DOMAIN','Kõik'),
(1,'SELECT_SUBJECT','Kõik'),
(1,'SELECT_DOMAIN_AND_SUBJECT','Kõik'),
(1,'SELECT_SPECIALIZATION','Kõik'),
(1,'SELECT_MODULE','Kõik'),
(1,'SELECT_TOPIC','Kõik'),
(1,'SELECT_SUBTOPIC','Kõik'),
(1,'DOMAIN_ESTONIAN','Eesti keel'),
(1,'DOMAIN_MOVEMENT','Liikumine'),
(1,'DOMAIN_ME_AND_THE_ENVIRONMENT','Mina ja keskkond'),
(1,'DOMAIN_MUSIC','Muusika'),
(1,'TOPIC_PRESCHOOL_TOPIC1','Eelkooli teema 1'),
(1,'TOPIC_PRESCHOOL_TOPIC2','Eelkooli teema 2'),
(1,'SUBTOPIC_MUINASAEG','Muinasaeg'),
(1,'SUBTOPIC_EESTI_ÜHISKONF_MUINASAJA_LÕPUL','Eesti ühiskond muinasaja lõpul'),
(1,'SUBTOPIC_KESKAEG','Keskaeg'),
(1,'SUBTOPIC_TÄHTSAMAD_ARHELOOGILISED_KULTUURID','Tähtsamad arheoloogilised kultuurid'),
(1,'SUBTOPIC_AJALOOSÜNDMUSED_JA_AJALOOLISED_ISIKUD','Ajaloosündmused ja ajaloolised isikud'),
(1,'SUBTOPIC_ELUOLU','Eluolu'),
(1,'SUBTOPIC_AJAARVAMINE','Ajaarvamine'),
(1,'SUBTOPIC_AJALOOALLIKAD','Ajalooallikad'),
(1,'TOPIC_SECONDARY_EDUCATION_TOPIC1','Keskhariduse teema 1'),
(1,'TOPIC_SECONDARY_EDUCATION_TOPIC2','Keskhariduse teema 2'),
(1,'SUBTOPIC_SUBTOPIC_FOR_SECONDARY_EDUCATION_TOPIC1','Keskhariduse alamteema 1'),
(1,'SPECIALIZATION_COMPUTERS_AND_NETWORKS','Arvutid ja arvutivõrgud'),
(1,'MODULE_ETTEVÕTLUSE_ALUSED','Ettevõtluse alused'),
(1,'MODULE_MAJANDUSE_ALUSED','Majanduse alused'),
(1,'MODULE_ÕIGUSE_ALUSED','Õiguse alused'),
(1,'MODULE_IT_ÕIGUS','IT õigus'),
(1,'MODULE_KOMMUNIKATSIOON','Kommunikatsioon'),
(1,'TOPIC_VOCATIONAL_EDUCATION_TOPIC1','Kutsehariduse teema 1'),
(1,'SUBTOPIC_SUBTOPIC_FOR_VOCATIONAL_EDUCATION','Kutsehariduse alateema');
