-- Russian translations
insert into Translation(translationGroup, translationKey, translation) values (2, 'LOGIN', 'Войти');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_VIEW_SUBJECT', 'Тема');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_VIEW_RESOURCE_TYPE', 'Тип');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_VIEW_EDUCATIONAL_CONTEXT', 'Возрастные группы');
insert into Translation(translationGroup, translationKey, translation) values (2, 'UPDATED', 'Новый');
insert into Translation(translationGroup, translationKey, translation) values (2, 'ADDED', 'Добавленной');
insert into Translation(translationGroup, translationKey, translation) values (2, 'CREATED', 'Созданный');
insert into Translation(translationGroup, translationKey, translation) values (2, 'REPOSITORY_NUMBER', 'Количество хранилище');
insert into Translation(translationGroup, translationKey, translation) values (2, 'ALL_RIGHTS_RESERVED', 'Все права защищены');
insert into Translation(translationgroup, translationkey, translation) values (2, 'AUDIO', 'аудио');
insert into Translation(translationgroup, translationkey, translation) values (2, 'DATA', 'данные');
insert into Translation(translationgroup, translationkey, translation) values (2, 'IMAGE', 'имидж');
insert into Translation(translationgroup, translationkey, translation) values (2, 'TEXT', 'текст');
insert into Translation(translationgroup, translationkey, translation) values (2, 'VIDEO', 'видео');
insert into Translation(translationgroup, translationkey, translation) values (2, 'APPLICATION', 'применение');
insert into Translation(translationgroup, translationkey, translation) values (2, 'ASSESSEMENT', 'оценка');
insert into Translation(translationgroup, translationkey, translation) values (2, 'BROADCAST', 'рассылка');
insert into Translation(translationgroup, translationkey, translation) values (2, 'CASESTUDY', 'пример');
insert into Translation(translationgroup, translationkey, translation) values (2, 'COURSE', 'курс');
insert into Translation(translationgroup, translationkey, translation) values (2, 'DEMONSTRATION', 'демонстрация');
insert into Translation(translationgroup, translationkey, translation) values (2, 'DRILLANDPRACTICE', 'сверла и практика');
insert into Translation(translationgroup, translationkey, translation) values (2, 'EDUCATIONALGAME', 'обучающая игра');
insert into Translation(translationgroup, translationkey, translation) values (2, 'ENQUIRYORIENTEDACTIVITY', 'запрос значимая деятельность');
insert into Translation(translationgroup, translationkey, translation) values (2, 'EXPERIMENT', 'эксперимент');
insert into Translation(translationgroup, translationkey, translation) values (2, 'EXPLORATION', 'разведка');
insert into Translation(translationgroup, translationkey, translation) values (2, 'GLOSSARY', 'словарь');
insert into Translation(translationgroup, translationkey, translation) values (2, 'GUIDE', 'руководство');
insert into Translation(translationgroup, translationkey, translation) values (2, 'LESSONPLAN', 'план урока');
insert into Translation(translationgroup, translationkey, translation) values (2, 'OPENACTIVITY', 'открытое деятельность');
insert into Translation(translationgroup, translationkey, translation) values (2, 'OTHER', 'другие');
insert into Translation(translationgroup, translationkey, translation) values (2, 'PRESENTATION', 'презентация');
insert into Translation(translationgroup, translationkey, translation) values (2, 'PROJECT', 'проект');
insert into Translation(translationgroup, translationkey, translation) values (2, 'REFERENCE', 'справка');
insert into Translation(translationgroup, translationkey, translation) values (2, 'ROLEPLAY', 'ролевые игры');
insert into Translation(translationgroup, translationkey, translation) values (2, 'SIMULATION', 'моделирование');
insert into Translation(translationgroup, translationkey, translation) values (2, 'TEXTBOOK', 'учебник');
insert into Translation(translationgroup, translationkey, translation) values (2, 'TOOL', 'инструмент');
insert into Translation(translationgroup, translationkey, translation) values (2, 'WEBSITE', 'сайт');
insert into Translation(translationgroup, translationkey, translation) values (2, 'BOOKMARKSHARINGPLATFORM', 'закладки платформы для обмена');
insert into Translation(translationgroup, translationkey, translation) values (2, 'IMAGESHARINGPLATFORM', 'имидж платформы для обмена');
insert into Translation(translationgroup, translationkey, translation) values (2, 'REFERENCESHARINGPLATFORM', 'справка платформа по обмену');
insert into Translation(translationgroup, translationkey, translation) values (2, 'SOUNDSHARINGPLATFORM', 'звук платформы для обмена');
insert into Translation(translationgroup, translationkey, translation) values (2, 'VIDEOSHARINGPLATFORM', 'видеопортал платформа');
insert into Translation(translationgroup, translationkey, translation) values (2, 'WEBLOG', 'сайт вход');
insert into Translation(translationgroup, translationkey, translation) values (2, 'WIKI', 'энциклопедия');
insert into Translation(translationGroup, translationKey, translation) values (2, 'PRESCHOOL', 'ДОШКОЛЬНОЕ');
insert into Translation(translationGroup, translationKey, translation) values (2, 'COMPULSORYEDUCATION', 'обязательное обучение');
insert into Translation(translationGroup, translationKey, translation) values (2, 'VOCATIONALEDUCATION', 'профессионального образования');
insert into Translation(translationGroup, translationKey, translation) values (2, 'HIGHEREDUCATION', 'высшее образование');
insert into Translation(translationGroup, translationKey, translation) values (2, 'CONTINUINGEDUCATION', 'Непрерывное образование');
insert into Translation(translationGroup, translationKey, translation) values (2, 'PROFESSIONALDEVELOPMENT', 'профессиональное развитие');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SPECIALEDUCATION', 'специальное образование');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_VIEW_LINK_TO_MATERIAL', 'Открытый материал');
insert into Translation(translationGroup, translationKey, translation) values (2, 'PUBLISHER', 'Издатель');
insert into Translation(translationGroup, translationKey, translation) values (2, 'PUBLISHERS', 'Издатели');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH', 'Поиск');
insert into Translation(translationGroup, translationKey, translation) values (2, 'UNKNOWN', 'Неизвестный');
insert into Translation(translationGroup, translationKey, translation) values (2, 'ABOUT', 'Что eKoolikott?');
insert into Translation(translationGroup, translationKey, translation) values (2, 'HELP', 'Как использовать eKoolikott');
insert into Translation(translationGroup, translationKey, translation) values (2, 'NEWEST', 'Новые');




