-- Russian translations
insert into Translation(translationGroup, translationKey, translation) values (2, 'LOGIN', 'Войти');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LOGOUT', 'Выйти');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_VIEW_SUBJECT', 'Тема');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_VIEW_RESOURCE_TYPE', 'Тип');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_VIEW_EDUCATIONAL_CONTEXT', 'Возрастные группы');
insert into Translation(translationGroup, translationKey, translation) values (2, 'UPDATED', 'Новый');
insert into Translation(translationGroup, translationKey, translation) values (2, 'CREATED', 'Созданный');
insert into Translation(translationGroup, translationKey, translation) values (2, 'REPOSITORY_NUMBER', 'Количество хранилище');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_VIEW_LICENSE_TYPE', 'Тип лицензии');
insert into Translation(translationgroup, translationkey, translation) values (2, 'AUDIO', 'аудио');
insert into Translation(translationgroup, translationkey, translation) values (2, 'DATA', 'данные');
insert into Translation(translationgroup, translationkey, translation) values (2, 'IMAGE', 'имидж');
insert into Translation(translationgroup, translationkey, translation) values (2, 'TEXT', 'текст');
insert into Translation(translationgroup, translationkey, translation) values (2, 'VIDEO', 'видео');
insert into Translation(translationgroup, translationkey, translation) values (2, 'APPLICATION', 'применение');
insert into Translation(translationgroup, translationkey, translation) values (2, 'ASSESSEMENT', 'оценка');
insert into Translation(translationgroup, translationkey, translation) values (2, 'BROADCAST', 'рассылка');
insert into Translation(translationgroup, translationkey, translation) values (2, 'CASESTUDY', 'пример');
insert into Translation(translationgroup, translationkey, translation) values (2, 'COURSE', 'курс');
insert into Translation(translationgroup, translationkey, translation) values (2, 'DEMONSTRATION', 'демонстрация');
insert into Translation(translationgroup, translationkey, translation) values (2, 'DRILLANDPRACTICE', 'сверла и практика');
insert into Translation(translationgroup, translationkey, translation) values (2, 'EDUCATIONALGAME', 'обучающая игра');
insert into Translation(translationgroup, translationkey, translation) values (2, 'ENQUIRYORIENTEDACTIVITY', 'запрос значимая деятельность');
insert into Translation(translationgroup, translationkey, translation) values (2, 'EXPERIMENT', 'эксперимент');
insert into Translation(translationgroup, translationkey, translation) values (2, 'EXPLORATION', 'разведка');
insert into Translation(translationgroup, translationkey, translation) values (2, 'GLOSSARY', 'словарь');
insert into Translation(translationgroup, translationkey, translation) values (2, 'GUIDE', 'руководство');
insert into Translation(translationgroup, translationkey, translation) values (2, 'LESSONPLAN', 'план урока');
insert into Translation(translationgroup, translationkey, translation) values (2, 'OPENACTIVITY', 'открытое деятельность');
insert into Translation(translationgroup, translationkey, translation) values (2, 'OTHER', 'другие');
insert into Translation(translationgroup, translationkey, translation) values (2, 'PRESENTATION', 'презентация');
insert into Translation(translationgroup, translationkey, translation) values (2, 'PROJECT', 'проект');
insert into Translation(translationgroup, translationkey, translation) values (2, 'REFERENCE', 'справка');
insert into Translation(translationgroup, translationkey, translation) values (2, 'ROLEPLAY', 'ролевые игры');
insert into Translation(translationgroup, translationkey, translation) values (2, 'SIMULATION', 'моделирование');
insert into Translation(translationgroup, translationkey, translation) values (2, 'TEXTBOOK', 'учебник');
insert into Translation(translationgroup, translationkey, translation) values (2, 'TOOL', 'инструмент');
insert into Translation(translationgroup, translationkey, translation) values (2, 'WEBSITE', 'сайт');
insert into Translation(translationgroup, translationkey, translation) values (2, 'BOOKMARKSHARINGPLATFORM', 'закладки платформы для обмена');
insert into Translation(translationgroup, translationkey, translation) values (2, 'IMAGESHARINGPLATFORM', 'имидж платформы для обмена');
insert into Translation(translationgroup, translationkey, translation) values (2, 'REFERENCESHARINGPLATFORM', 'справка платформа по обмену');
insert into Translation(translationgroup, translationkey, translation) values (2, 'SOUNDSHARINGPLATFORM', 'звук платформы для обмена');
insert into Translation(translationgroup, translationkey, translation) values (2, 'VIDEOSHARINGPLATFORM', 'видеопортал платформа');
insert into Translation(translationgroup, translationkey, translation) values (2, 'WEBLOG', 'сайт вход');
insert into Translation(translationgroup, translationkey, translation) values (2, 'WIKI', 'энциклопедия');
insert into Translation(translationGroup, translationKey, translation) values (2, 'PRESCHOOLEDUCATION', 'Дошкольное образование');
insert into Translation(translationGroup, translationKey, translation) values (2, 'GENERALEDUCATION', 'Общее образование');
insert into Translation(translationGroup, translationKey, translation) values (2, 'HIGHEREDUCATION', 'высшее образование');
insert into Translation(translationGroup, translationKey, translation) values (2, 'VOCATIONALEDUCATION', 'профессионального образования');
insert into Translation(translationGroup, translationKey, translation) values (2, 'CONTINUINGEDUCATION', 'Непрерывное образование');
insert into Translation(translationGroup, translationKey, translation) values (2, 'TEACHEREDUCATION', 'Педагогическое образование');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SPECIALEDUCATION', 'специальное образование');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_VIEW_LINK_TO_MATERIAL', 'Открытый материал');
insert into Translation(translationGroup, translationKey, translation) values (2, 'PUBLISHER', 'Издатель');
insert into Translation(translationGroup, translationKey, translation) values (2, 'PUBLISHERS', 'Издатели');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH', 'Поиск');
insert into Translation(translationGroup, translationKey, translation) values (2, 'UNKNOWN', 'Неизвестный');
insert into Translation(translationGroup, translationKey, translation) values (2, 'ABOUT_PAGE_LINK_TITLE', 'Что eKoolikott?');
insert into Translation(translationGroup, translationKey, translation) values (2, 'HELP_PAGE_LINK_TITLE', 'Как использовать eKoolikott');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LANDING_PAGE_TITLE_NEWEST', 'Новые');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LICENSETYPE_ALLRIGHTSRESERVED', 'Все права защищены');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LICENSETYPE_CCBY', 'CC BY');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LICENSETYPE_CCBYSA', 'CC BY-SA');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LICENSETYPE_CCBYND', 'CC BY-ND');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LICENSETYPE_CCBYNC', 'CC BY-NC');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LICENSETYPE_CCBYNCSA', 'CC BY-NC-SA');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LICENSETYPE_CCBYNCND', 'CC BY-NC-ND');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LICENSETYPE_OTHER', 'Другой');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_VIEW_TAGS', 'Ключевые слова');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_RESULT_NO_RESULT', 'Результатов не найдено при поиске ');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_RESULT_PART_1', 'Поиск ');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_RESULT_PART_2', ' найдено ');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_RESULT_PART_3', ' результата.');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_RESULT_1_RESULT_PART_1', 'При поиске ');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_RESULT_1_RESULT_PART_2', ' найденное количество результатов: ');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_RESULT_1_RESULT_PART_3', '.');
insert into Translation(translationGroup, translationKey, translation) values (2, 'COPYRIGHT_FOOTER', '© 2016 Все права защищены. Министерство образования и науки');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_RESULT_PREVIOUS', 'Предыдущая');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_RESULT_NEXT', 'Следующий');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_FILTER_SUBJECT_LABEL', 'Тема');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_FILTER_SUBJECT_PLACEHOLDER', 'Выберите или поиск...');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_FILTER_RESOURCE_TYPE_LABEL', 'Тип');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_FILTER_RESOURCE_TYPE_PLACEHOLDER', 'Выберите или поиск...');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_FILTER_EDUCATIONAL_CONTEXT_LABEL', 'Обучающие контекст');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_FILTER_EDUCATIONAL_CONTEXT_PLACEHOLDER', 'Выберите или поиск...');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_FILTER_LICENSE_TYPE_LABEL', 'Тип лицензии');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_FILTER_LICENSE_TYPE_PLACEHOLDER', 'Выберите или поиск...');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_FILTER_BUTTON_FILTER', 'Сортировать');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_FILTER_BUTTON_RESET', 'Сброс');
insert into Translation(translationGroup, translationKey, translation) values (2, 'SEARCH_FILTER_TITLE', 'Фильтр');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MYPROFILE_PAGE_TITLE_COMPILATIONS', 'Мои сборники');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MYPROFILE_PAGE_TITLE_MATERIALS', 'Мои материалы');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MYPROFILE_PAGE_TITLE_MY_DATA', 'Мой данные');
insert into Translation(translationGroup, translationKey, translation) values (2, 'PROFILE_PAGE_TITLE_COMPILATIONS', 'Сборники');
insert into Translation(translationGroup, translationKey, translation) values (2, 'PROFILE_PAGE_TITLE_MATERIALS', 'Материалы');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LOGIN_CHOOSE_LOGIN_METHOD', 'Выберите метод входа');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LOGIN_FACEBOOK', 'Facebook');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LOGIN_GOOGLE', 'Google');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LOGIN_TAAT', 'TAAT');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LOGIN_IDCARD', 'ID-карта');
insert into Translation(translationGroup, translationKey, translation) values (2, 'LOGIN_MOBILEID', 'Mobiil-ID');
insert into Translation(translationGroup, translationKey, translation) values (2, 'ERROR_LOGIN_FAILED', 'Ошибка входа');
insert into Translation(translationGroup, translationKey, translation) values (2, 'ERROR_MATERIAL_NOT_FOUND', 'Материал не найден');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_PAID', 'Платное');

-- Material Subject translations
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_ESTONIAN', 'Эстонский');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_RUSSIAN', 'Русский');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_LITERATURE', 'Литература');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_ESTONIAN_AS_SECOND_LANGUAGE', 'Эстонский (второй язык)');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_ENGLISH_AS_SECOND_LANGUAGE', 'Английский (второй язык)');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_FRENCH_AS_SECOND_LANGUAGE', 'Французский (второй язык)');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_GERMAN_AS_SECOND_LANGUAGE', 'Немецкий (второй язык)');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_RUSSIAN_AS_SECOND_LANGUAGE', 'Русский  (второй язык)');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_SWEDISH_AS_SECOND_LANGUAGE', 'Шведский (второй язык)');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_FINNISH_AS_SECOND_LANGUAGE', 'Финский (второй язык)');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_LATIN_AS_SECOND_LANGUAGE', 'Латинский (второй язык)');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_CHINESE_AS_SECOND_LANGUAGE', 'Китайский (второй язык)');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_JAPANESE_AS_SECOND_LANGUAGE', 'Японский (второй язык)');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_MATHEMATICS', 'Математика');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_SCIENCE', 'Наука');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_BIOLOGY', 'Биология');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_GEOGRAPHY', 'География');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_PHYSICS', 'Физика');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_CHEMISTRY', 'Химия');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_HUMAN_STUDIES', 'Исследования человека');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_HISTORY', 'История');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_CIVICS_AND_CITIZENSHIP', 'Основы гражданственности и гражданства');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_ART', 'Искусство');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_MUSIC', 'Музыка');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_TECHNOLOGY', 'Технология');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_HANDICRAFT', 'Кустарные');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_HOME_ECONOMICS', 'Домашняя экономика');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_EDUCATIONAL_TECHNOLOGY', 'Образовательные технологии');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_PHYSICAL_EDUCATION', 'Физкультура');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_RELIGIOUS_STUDIES', 'Религиоведение');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_INFORMATICS', 'Информатика');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_CAREER_STUDIES', 'Исследования карьеры');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_ECONOMICS_AND_BUSINESS_STUDIES', 'Экономика и бизнес-исследований');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_MEDIA_STUDIES', 'Исследования СМИ');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_NATIONAL_DEFENCE', 'Национальная защита');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_BASICS_OF_INQUIRY', 'Основы расследования');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_PHILOSOPHY', 'Философия');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_LIFELONG_LEARNING_AND_CAREER_PLANNING', 'Непрерывное обучение и планирование карьеры');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_ENVIRONMENT_AND_SUSTAINABLE_DEVELOPMENT', 'Окружающая среда и устойчивое развитие');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_CIVIC_INITIATIVE_AND_ENTREPRENEURSHIP', 'Гражданская инициатива и предпринимательство');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_CULTURAL_IDENTITY', 'Культурные особенности');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_INFORMATION_ENVIRONMENT', 'Информационная среда');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_TECHNOLOGY_AND_INNOVATION', 'Технология и инновации');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_HEALTH_AND_SAFETY', 'Здоровье и безопасность');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_VALUES_AND_MORAL', 'Ценности и нравственное');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_CULTURAL_AND_VALUE_COMPETENCE', 'Культурное и значение компетенции');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_SOCIAL_AND_CITIZENSHIP_COMPETENCE', 'Социальная компетентность и гражданство');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_SELF_MANAGEMENT_COMPETENCE', 'Компетенция Самоуправление');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_LEARNING_TO_LEARN_COMPETENCE', 'Умение учиться компетенции');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_COMMUNICATION_COMPETENCE', 'Связь компетенции');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_MATHEMATICS_NATURAL_SCIENCES_AND_TECHNOLOGY_COMPETENCE', 'Математика, естественные науки и технологии компетентность');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_ENTREPRENEURSHIP_COMPETENCE', 'Предпринимательство компетенции');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_DIGITAL_COMPETENCE', 'Цифровой компетенции');
insert into Translation(translationGroup, translationKey, translation) values (2, 'MATERIAL_SUBJECT_OTHER', 'Другое');
