-- English translations
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN', 'Login');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGOUT', 'Log out');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAIL_VIEW_SUBJECT', 'Subject');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_VIEW_RESOURCE_TYPE', 'Type');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAIL_VIEW_EDUCATIONAL_CONTEXT', 'Educational context');
insert into Translation(translationGroup, translationKey, translation) values (3, 'UPDATED', 'Updated');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CREATED', 'Created');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REPOSITORY_NUMBER', 'Repository number');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_VIEW_LICENSE_TYPE', 'License type');
insert into Translation(translationGroup, translationKey, translation) values (3, 'AUDIO', 'Audio');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DATA', 'Data');
insert into Translation(translationGroup, translationKey, translation) values (3, 'IMAGE', 'Image');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TEXT', 'Text');
insert into Translation(translationGroup, translationKey, translation) values (3, 'VIDEO', 'Video');
insert into Translation(translationGroup, translationKey, translation) values (3, 'APPLICATION', 'Application');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ASSESSEMENT', 'Assessment');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BROADCAST', 'Broadcast');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CASESTUDY', 'Casestudy');
insert into Translation(translationGroup, translationKey, translation) values (3, 'COURSE', 'Course');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DEMONSTRATION', 'Demonstration');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DRILLANDPRACTICE', 'Drill and practice');
insert into Translation(translationGroup, translationKey, translation) values (3, 'EDUCATIONALGAME', 'Educational game');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ENQUIRYORIENTEDACTIVITY', 'Enquiry oriented game');
insert into Translation(translationGroup, translationKey, translation) values (3, 'EXPERIMENT', 'Experiment');
insert into Translation(translationGroup, translationKey, translation) values (3, 'EXPLORATION', 'Exploration');
insert into Translation(translationGroup, translationKey, translation) values (3, 'GLOSSARY', 'Glossary');
insert into Translation(translationGroup, translationKey, translation) values (3, 'GUIDE', 'Guide');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LESSONPLAN', 'Lessonplan');
insert into Translation(translationGroup, translationKey, translation) values (3, 'OPENACTIVITY', 'Open activity');
insert into Translation(translationGroup, translationKey, translation) values (3, 'OTHER', 'Other');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PRESENTATION', 'Presentation');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PROJECT', 'Project');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REFERENCE', 'Reference');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ROLEPLAY', 'Roleplay');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SIMULATION', 'Simulation');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TEXTBOOK', 'Textbook');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TOOL', 'Tool');
insert into Translation(translationGroup, translationKey, translation) values (3, 'WEBSITE', 'Website');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BOOKMARKSHARINGPLATFORM', 'Bookmark sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'IMAGESHARINGPLATFORM', 'Image sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REFERENCESHARINGPLATFORM', 'Reference sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SOUNDSHARINGPLATFORM', 'Sound sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'VIDEOSHARINGPLATFORM', 'Video sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'WEBLOG', 'Weblog');
insert into Translation(translationGroup, translationKey, translation) values (3, 'WIKI', 'Wiki');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PRESCHOOLEDUCATION', 'Preschool education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BASICEDUCATION', 'Basic education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SECONDARYEDUCATION', 'Secondary education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'HIGHEREDUCATION', 'Higher education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'VOCATIONALEDUCATION', 'Vocational education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CONTINUINGEDUCATION', 'Continuing education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TEACHEREDUCATION', 'Teacher education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SPECIALEDUCATION', 'Special education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_VIEW_LINK_TO_MATERIAL', 'Open material');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PUBLISHER', 'Publisher');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PUBLISHERS', 'Publishers');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH', 'Search');
insert into Translation(translationGroup, translationKey, translation) values (3, 'UNKNOWN', 'Unknown');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ABOUT_PAGE_LINK_TITLE', 'What is eKoolikott?');
insert into Translation(translationGroup, translationKey, translation) values (3, 'HELP_PAGE_LINK_TITLE', 'How to use eKoolikott');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LANDING_PAGE_TITLE_NEWEST', 'Newest');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_ALLRIGHTSRESERVED', 'All rights reserved');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBY', 'CC BY');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYSA', 'CC BY-SA');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYND', 'CC BY-ND');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYNC', 'CC BY-NC');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYNCSA', 'CC BY-NC-SA');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYNCND', 'CC BY-NC-ND');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_OTHER', 'Other');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAIL_VIEW_TAGS', 'Tags');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_NO_RESULT', 'No result found for ');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_PART_1', 'Searching for ');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_PART_2', ' returned ');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_PART_3', ' results.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_1_RESULT_PART_1', 'Searching for ');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_1_RESULT_PART_2', ' returned ');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_1_RESULT_PART_3', ' result.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_EMPTY_QUERY_NO_RESULT', 'No results found.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_EMPTY_QUERY_PART_1', 'Search returned');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_EMPTY_QUERY_PART_2', ' results.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_EMPTY_QUERY_1_RESULT_PART_1', 'Search returned ');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_EMPTY_QUERY_1_RESULT_PART_2', ' result.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'COPYRIGHT_FOOTER', '© 2016 All rights reserved. Ministry of Education and Research');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_PREVIOUS', 'Previous');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_NEXT', 'Next');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_SUBJECT_LABEL', 'Subject');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_SUBJECT_PLACEHOLDER', 'Select or search...');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_RESOURCE_TYPE_LABEL', 'Type');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_RESOURCE_TYPE_PLACEHOLDER', 'Select or search...');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_EDUCATIONAL_CONTEXT_LABEL', 'Educational context');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_EDUCATIONAL_CONTEXT_PLACEHOLDER', 'Select or search...');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_LICENSE_TYPE_LABEL', 'License type');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_LICENSE_TYPE_PLACEHOLDER', 'Select or search...');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_BUTTON_FILTER', 'Filter');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_BUTTON_RESET', 'Reset');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_TITLE', 'Filter');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MYPROFILE_PAGE_TITLE_PORTFOLIOS', 'My portfolios');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MYPROFILE_PAGE_TITLE_MATERIALS', 'My materials');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MYPROFILE_PAGE_TITLE_MY_DATA', 'My data');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PROFILE_PAGE_TITLE_PORTFOLIOS', 'Portfolios');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PROFILE_PAGE_TITLE_MATERIALS', 'Materials');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_CHOOSE_LOGIN_METHOD', 'Choose login method');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_FACEBOOK', 'Facebook');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_GOOGLE', 'Google');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_TAAT', 'TAAT');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_IDCARD', 'ID-card');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_MOBILEID', 'Mobile-ID');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_MOBILEID_CODE', 'Your code is');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_SMS', 'Make sure that the SMS inbox for verification code match that shown on the computer screen.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ERROR_LOGIN_FAILED', 'Login failed');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ERROR_MATERIAL_NOT_FOUND', 'Material not found');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_PAID', 'Paid');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ERROR_PORTFOLIO_NOT_FOUND', 'Portfolio not found');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MY_PROFILE', 'My profile');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ERROR_GETTING_USER_FAILED', 'User not found');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PERSONAL_CODE', 'Personal code');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MESSAGE_ERROR_PERSONAL_CODE_REQUIRED', 'Personal code is required');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MESSAGE_ERROR_PERSONAL_CODE_INVALID', 'Personal code is invalid');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MESSAGE_ERROR_PHONE_NUMBER_REQUIRED', 'Phone number is required');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MESSAGE_ERROR_PHONE_NUMBER_NOT_ESTONIAN', 'Country code must be Estonian');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_OPEN', 'Detailed search');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_TITLE', 'Title');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_DESCRIPTION', 'Description');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_AUTHOR', 'Author');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_SUBMIT', 'Search');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_MATERIALS', 'Materials');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_PORTFOLIOS', 'Portfolios');

-- Material Subject translations
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_ESTONIAN', 'Estonian');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_RUSSIAN', 'Russian');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_LITERATURE', 'Literature');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_ESTONIAN_AS_SECOND_LANGUAGE', 'Estonian as second language');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_ENGLISH_AS_SECOND_LANGUAGE', 'English as second language');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_FRENCH_AS_SECOND_LANGUAGE', 'French as second language');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_GERMAN_AS_SECOND_LANGUAGE', 'German as second language');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_RUSSIAN_AS_SECOND_LANGUAGE', 'Russian as second language');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_SWEDISH_AS_SECOND_LANGUAGE', 'Swedish as second language');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_FINNISH_AS_SECOND_LANGUAGE', 'Finnish as second language');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_LATIN_AS_SECOND_LANGUAGE', 'Latin as second language');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_CHINESE_AS_SECOND_LANGUAGE', 'Chinese as second language');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_JAPANESE_AS_SECOND_LANGUAGE', 'Japanese as second language');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_MATHEMATICS', 'Mathematics');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_SCIENCE', 'Science');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_BIOLOGY', 'Biology');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_GEOGRAPHY', 'Geography');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_PHYSICS', 'Physics');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_CHEMISTRY', 'Chemistry');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_HUMAN_STUDIES', 'Human studies');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_HISTORY', 'History');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_CIVICS_AND_CITIZENSHIP', 'Civics and citizenship');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_ART', 'Art');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_MUSIC', 'Music');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_TECHNOLOGY', 'Technology');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_HANDICRAFT', 'Handicraft');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_HOME_ECONOMICS', 'Home economics');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_EDUCATIONAL_TECHNOLOGY', 'Educational technology');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_PHYSICAL_EDUCATION', 'Physical education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_RELIGIOUS_STUDIES', 'Religious studies');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_INFORMATICS', 'Informatics');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_CAREER_STUDIES', 'Career studies');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_ECONOMICS_AND_BUSINESS_STUDIES', 'Economics and business studies');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_MEDIA_STUDIES', 'Media studies');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_NATIONAL_DEFENCE', 'National defence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_BASICS_OF_INQUIRY', 'Basics of inquiry');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_PHILOSOPHY', 'Philosophy');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_LIFELONG_LEARNING_AND_CAREER_PLANNING', 'Lifelong learning and career planning');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_ENVIRONMENT_AND_SUSTAINABLE_DEVELOPMENT', 'Environment and sustainable development');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_CIVIC_INITIATIVE_AND_ENTREPRENEURSHIP', 'Civic initiative and entrepreneurship');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_CULTURAL_IDENTITY', 'Cultural identity');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_INFORMATION_ENVIRONMENT', 'Information environment');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_TECHNOLOGY_AND_INNOVATION', 'Technology and innovation');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_HEALTH_AND_SAFETY', 'Health and safety');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_VALUES_AND_MORAL', 'Values and moral');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_CULTURAL_AND_VALUE_COMPETENCE', 'Cultural and value competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_SOCIAL_AND_CITIZENSHIP_COMPETENCE', 'Social and citizenship competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_SELF_MANAGEMENT_COMPETENCE', 'Self-management competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_LEARNING_TO_LEARN_COMPETENCE', 'Learning to learn competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_COMMUNICATION_COMPETENCE', 'Communication competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_MATHEMATICS_NATURAL_SCIENCES_AND_TECHNOLOGY_COMPETENCE', 'Mathematics, natural sciences and technology competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_ENTREPRENEURSHIP_COMPETENCE', 'Entrepreneurship competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_DIGITAL_COMPETENCE', 'Digital competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_OTHER', 'Other');
