-- English translations
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN', 'Login');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_VIEW_SUBJECT', 'Subject');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_VIEW_RESOURCE_TYPE', 'Type');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_VIEW_EDUCATIONAL_CONTEXT', 'Educational context');
insert into Translation(translationGroup, translationKey, translation) values (3, 'UPDATED', 'Updated');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CREATED', 'Created');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REPOSITORY_NUMBER', 'Repository number');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_VIEW_LICENSE_TYPE', 'License type');
insert into Translation(translationGroup, translationKey, translation) values (3, 'AUDIO', 'Audio');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DATA', 'Data');
insert into Translation(translationGroup, translationKey, translation) values (3, 'IMAGE', 'Image');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TEXT', 'Text');
insert into Translation(translationGroup, translationKey, translation) values (3, 'VIDEO', 'Video');
insert into Translation(translationGroup, translationKey, translation) values (3, 'APPLICATION', 'Application');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ASSESSEMENT', 'Assessment');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BROADCAST', 'Broadcast');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CASESTUDY', 'Casestudy');
insert into Translation(translationGroup, translationKey, translation) values (3, 'COURSE', 'Course');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DEMONSTRATION', 'Demonstration');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DRILLANDPRACTICE', 'Drill and practice');
insert into Translation(translationGroup, translationKey, translation) values (3, 'EDUCATIONALGAME', 'Educational game');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ENQUIRYORIENTEDACTIVITY', 'Enquiry oriented game');
insert into Translation(translationGroup, translationKey, translation) values (3, 'EXPERIMENT', 'Experiment');
insert into Translation(translationGroup, translationKey, translation) values (3, 'EXPLORATION', 'Exploration');
insert into Translation(translationGroup, translationKey, translation) values (3, 'GLOSSARY', 'Glossary');
insert into Translation(translationGroup, translationKey, translation) values (3, 'GUIDE', 'Guide');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LESSONPLAN', 'Lessonplan');
insert into Translation(translationGroup, translationKey, translation) values (3, 'OPENACTIVITY', 'Open activity');
insert into Translation(translationGroup, translationKey, translation) values (3, 'OTHER', 'Other');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PRESENTATION', 'Presentation');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PROJECT', 'Project');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REFERENCE', 'Reference');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ROLEPLAY', 'Roleplay');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SIMULATION', 'Simulation');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TEXTBOOK', 'Textbook');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TOOL', 'Tool');
insert into Translation(translationGroup, translationKey, translation) values (3, 'WEBSITE', 'Website');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BOOKMARKSHARINGPLATFORM', 'Bookmark sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'IMAGESHARINGPLATFORM', 'Image sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REFERENCESHARINGPLATFORM', 'Reference sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SOUNDSHARINGPLATFORM', 'Sound sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'VIDEOSHARINGPLATFORM', 'Video sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'WEBLOG', 'Weblog');
insert into Translation(translationGroup, translationKey, translation) values (3, 'WIKI', 'Wiki');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PRESCHOOL', 'Preschool');
insert into Translation(translationGroup, translationKey, translation) values (3, 'COMPULSORYEDUCATION', 'Compulsory education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'VOCATIONALEDUCATION', 'Vocational education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'HIGHEREDUCATION', 'Higher education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CONTINUINGEDUCATION', 'Continuing education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PROFESSIONALDEVELOPMENT', 'Professional development');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SPECIALEDUCATION', 'Special education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_VIEW_LINK_TO_MATERIAL', 'Open material');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PUBLISHER', 'Publisher');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PUBLISHERS', 'Publishers');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH', 'Search');
insert into Translation(translationGroup, translationKey, translation) values (3, 'UNKNOWN', 'Unknown');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ABOUT_PAGE_LINK_TITLE', 'What is eKoolikott?');
insert into Translation(translationGroup, translationKey, translation) values (3, 'HELP_PAGE_LINK_TITLE', 'How to use eKoolikott');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LANDING_PAGE_TITLE_NEWEST', 'Newest');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_ALLRIGHTSRESERVED', 'All rights reserved');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBY', 'CC BY');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYSA', 'CC BY-SA');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYND', 'CC BY-ND');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYNC', 'CC BY-NC');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYNCSA', 'CC BY-NC-SA');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYNCND', 'CC BY-NC-ND');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_OTHER', 'Other');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_VIEW_TAGS', 'Tags');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_NO_RESULT', 'No result found for ');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_PART_1', 'Searching for ');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_PART_2', ' returned ');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_PART_3', ' results.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_1_RESULT_PART_1', 'Searching for ');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_1_RESULT_PART_2', ' returned ');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_1_RESULT_PART_3', ' result.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'COPYRIGHT_FOOTER', '© 2016 All rights reserved. Ministry of Education and Research');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_PREVIOUS', 'Previous');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_NEXT', 'Next');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_SUBJECT_LABEL', 'Subject');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_SUBJECT_PLACEHOLDER', 'Select or search...');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_RESOURCE_TYPE_LABEL', 'Type');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_RESOURCE_TYPE_PLACEHOLDER', 'Select or search...');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_BUTTON_FILTER', 'Filter');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_FILTER_BUTTON_RESET', 'Reset');

-- Material Subject translations


insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_SUBJECT_BIOLOGY', 'Biology');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_SUBJECT_MATHEMATICS', 'Mathematics');
