-- English translations
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN', 'Login');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGOUT', 'Log out');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAIL_VIEW_SUBJECT', 'Subject');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_VIEW_RESOURCE_TYPE', 'Type');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAIL_VIEW_EDUCATIONAL_CONTEXT', 'Educational context');
insert into Translation(translationGroup, translationKey, translation) values (3, 'UPDATED', 'Updated');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CREATED', 'Created');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ADDED', 'Added');
insert into Translation(translationGroup, translationKey, translation) values (3, 'AUTHORS', 'Authors');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CREATOR', 'Creator');
insert into Translation(translationGroup, translationKey, translation) values (3, 'VIEW_COUNT', 'Views');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REPOSITORY_NUMBER', 'Repository number');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_VIEW_LICENSE_TYPE', 'License type');
insert into Translation(translationGroup, translationKey, translation) values (3, 'AUDIO', 'Audio');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DATA', 'Data');
insert into Translation(translationGroup, translationKey, translation) values (3, 'IMAGE', 'Image');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TEXT', 'Text');
insert into Translation(translationGroup, translationKey, translation) values (3, 'VIDEO', 'Video');
insert into Translation(translationGroup, translationKey, translation) values (3, 'APPLICATION', 'Application');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ASSESSMENT', 'Assessment');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BROADCAST', 'Broadcast');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CASESTUDY', 'Casestudy');
insert into Translation(translationGroup, translationKey, translation) values (3, 'COURSE', 'Course');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DEMONSTRATION', 'Demonstration');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DRILLANDPRACTICE', 'Drill and practice');
insert into Translation(translationGroup, translationKey, translation) values (3, 'EDUCATIONALGAME', 'Educational game');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ENQUIRYORIENTEDACTIVITY', 'Enquiry oriented game');
insert into Translation(translationGroup, translationKey, translation) values (3, 'EXPERIMENT', 'Experiment');
insert into Translation(translationGroup, translationKey, translation) values (3, 'EXPLORATION', 'Exploration');
insert into Translation(translationGroup, translationKey, translation) values (3, 'GLOSSARY', 'Glossary');
insert into Translation(translationGroup, translationKey, translation) values (3, 'GUIDE', 'Guide');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LESSONPLAN', 'Lessonplan');
insert into Translation(translationGroup, translationKey, translation) values (3, 'OPENACTIVITY', 'Open activity');
insert into Translation(translationGroup, translationKey, translation) values (3, 'OTHER', 'Other');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PRESENTATION', 'Presentation');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PROJECT', 'Project');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REFERENCE', 'Reference');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ROLEPLAY', 'Roleplay');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SIMULATION', 'Simulation');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TEXTBOOK', 'Textbook');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TOOL', 'Tool');
insert into Translation(translationGroup, translationKey, translation) values (3, 'WEBSITE', 'Website');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BOOKMARKSHARINGPLATFORM', 'Bookmark sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'IMAGESHARINGPLATFORM', 'Image sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REFERENCESHARINGPLATFORM', 'Reference sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SOUNDSHARINGPLATFORM', 'Sound sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'VIDEOSHARINGPLATFORM', 'Video sharing platform');
insert into Translation(translationGroup, translationKey, translation) values (3, 'WEBLOG', 'Weblog');
insert into Translation(translationGroup, translationKey, translation) values (3, 'WIKI', 'Wiki');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PRESCHOOLEDUCATION', 'Preschool education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BASICEDUCATION', 'Basic education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SECONDARYEDUCATION', 'Secondary education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'HIGHEREDUCATION', 'Higher education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'VOCATIONALEDUCATION', 'Vocational education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CONTINUINGEDUCATION', 'Continuing education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TEACHEREDUCATION', 'Teacher education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SPECIALEDUCATION', 'Special education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_VIEW_LINK_TO_MATERIAL', 'Open material');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PUBLISHER', 'Publisher');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PUBLISHERS', 'Publishers');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH', 'Search');
insert into Translation(translationGroup, translationKey, translation) values (3, 'UNKNOWN', 'Unknown');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ABOUT_PAGE_LINK_TITLE', 'What is eKoolikott?');
insert into Translation(translationGroup, translationKey, translation) values (3, 'HELP_PAGE_LINK_TITLE', 'How to use eKoolikott');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LANDING_PAGE_TITLE_NEWEST', 'Newest');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_ALLRIGHTSRESERVED', 'All rights reserved');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBY', 'CC BY');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYSA', 'CC BY-SA');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYND', 'CC BY-ND');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYNC', 'CC BY-NC');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYNCSA', 'CC BY-NC-SA');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_CCBYNCND', 'CC BY-NC-ND');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LICENSETYPE_OTHER', 'Other');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAIL_VIEW_TAGS', 'Tags');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_NO_RESULT', 'No results found.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_PART_1', 'Search returned');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_PART_2', ' results.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_1_RESULT_PART_1', 'Search returned ');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_1_RESULT_PART_2', ' result.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'COPYRIGHT_FOOTER', '© 2016 All rights reserved. Ministry of Education and Research');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_PREVIOUS', 'Previous');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SEARCH_RESULT_NEXT', 'Next');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MYPROFILE_PAGE_TITLE_PORTFOLIOS', 'My portfolios');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MYPROFILE_PAGE_TITLE_MATERIALS', 'My materials');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MYPROFILE_PAGE_TITLE_MY_DATA', 'My data');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PROFILE_PAGE_TITLE_PORTFOLIOS', 'Portfolios');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PROFILE_PAGE_TITLE_MATERIALS', 'Materials');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_CHOOSE_LOGIN_METHOD', 'Choose login method');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_FACEBOOK', 'Facebook');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_GOOGLE', 'Google');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_TAAT', 'TAAT');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_IDCARD', 'ID-card');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_MOBILEID', 'Mobile-ID');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_MOBILEID_CODE', 'Your code is');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LOGIN_SMS', 'Make sure that the SMS inbox for verification code match that shown on the computer screen.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ERROR_LOGIN_FAILED', 'Login failed');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ERROR_MATERIAL_NOT_FOUND', 'Material not found');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_PAID', 'Paid');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ERROR_PORTFOLIO_NOT_FOUND', 'Portfolio not found');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MY_PROFILE', 'My profile');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ERROR_GETTING_USER_FAILED', 'User not found');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PERSONAL_CODE', 'Personal code');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MESSAGE_ERROR_PERSONAL_CODE_REQUIRED', 'Personal code is required');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MESSAGE_ERROR_PERSONAL_CODE_INVALID', 'Personal code is invalid');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MESSAGE_ERROR_PHONE_NUMBER_REQUIRED', 'Phone number is required');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MESSAGE_ERROR_PHONE_NUMBER_NOT_ESTONIAN', 'Country code must be Estonian');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_OPEN', 'Detailed search');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_TITLE', 'Title');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_DESCRIPTION', 'Description');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_AUTHOR', 'Author');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_SUBMIT', 'Search');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_MATERIALS', 'Materials');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_PORTFOLIOS', 'Portfolios');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_ALL', 'All');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_MAIN', 'Main');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_ON', 'Yes');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_OFF', 'No');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_INCLUDE_PAID', 'Include Paid');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_TARGET_GROUP', 'Age group');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_ONLY_BOOKS', 'Only books');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_CLIL', 'Content and language integrated learning');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_SPECIAL_EDUCATION', 'Simplified curriculum');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_ISSUE_DATE_FROM', 'Issued from ');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_ISSUE_DATE_OR_LATER', ' or later.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_CROSS_CURRICULAR_THEME', 'Cross-curricular theme');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_KEY_COMPETENCE', 'Key competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_SPECIAL_EDUCATIONAL_NEED', 'Special educational need');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DETAILED_SEARCH_CLEAR', 'Clear');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ADD_PORTFOLIO', 'Add Portfolio');
insert into Translation(translationGroup, translationKey, translation) values (3, 'EDIT_PORTFOLIO', 'Edit portfolio');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_TITLE', 'Title');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_SUMMARY', 'Summary');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_METADATA_TOOLBAR_LABEL', 'Add portfolio basic data');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BUTTON_CANCEL', 'Cancel');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BUTTON_ADD', 'Add');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BUTTON_REMOVE', 'Remove');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BUTTON_CREATE_PORTFOLIO', 'Create portfolio');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BUTTON_CREATE_MATERIAL', 'Create material');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BUTTON_NEXT_STEP', 'Next step');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BUTTON_PREVIOUS_STEP', 'Previous step');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BUTTON_EDIT_PORTFOLIO', 'Save');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_PRESCHOOL', 'Preschool');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_ZERO_FIVE', '0-5');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_SIX_SEVEN', '6-7');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_LEVEL1', 'I school level');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_GRADE1', '1st grade');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_GRADE2', '2nd grade');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_GRADE3', '3rd grade');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_LEVEL2', 'II school level');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_GRADE4', '4th grade');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_GRADE5', '5th grade');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_GRADE6', '6th grade');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_LEVEL3', 'III school level');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_GRADE7', '7th grade');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_GRADE8', '8th grade');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_GRADE9', '9th grade');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TARGET_GROUP_GYMNASIUM', 'Gymnasium');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TABLE_OF_CONTENTS', 'Table of Contents');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ALERT_CONFIRM_POSITIVE', 'Yes');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ALERT_CONFIRM_NEGATIVE', 'No');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_PHOTO_UPLOAD_HELP', 'Drag and drop the picture or choose from your computer');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_PHOTO_PREVIEW', 'Preview');

-- Edit portfolio
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_ENTER_CHAPTER_TITLE', 'Add chapter title');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_ENTER_SUB_CHAPTER_TITLE', 'Add subchapter title');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_CHAPTER_CONTENT', 'Chapter content');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_SUB_CHAPTER_CONTENT', 'Subchapter content');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_ATTACHED_MATERIALS', 'Attached Materials');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_DELETE_CHAPTER', 'Delete');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_DELETE_SUB_CHAPTER', 'Delete');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_CHAPTERS', 'Portfolio chapters');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_SAVE', 'Save portfolio');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_DELETE_CHAPTER_CONFIRM_TITLE', 'Are you sure?');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_DELETE_SUB_CHAPTER_CONFIRM_TITLE', 'Are you sure?');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_DELETE_CHAPTER_CONFIRM_MESSAGE', 'It is not possible to undo this operation');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_DELETE_SUB_CHAPTER_CONFIRM_MESSAGE', 'It is not possible to undo this operation');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_ADD_CHAPTER', 'Add chapter');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_ADD_SUBCHAPTER', 'Add subchapter');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_DEFAULT_NEW_CHAPTER_TITLE', 'New chapter');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_DEFAULT_NEW_SUBCHAPTER_TITLE', 'New subchapter');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_CREATE_NEW_MATERIAL_URL', 'URL for material that does not exists in E-koolikott');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_SAVED', 'Portfolio saved');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_EDIT_METADATA', 'Change Metadata');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_SEND_LINK', 'Send link');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_VISIBILITY_PUBLIC', 'Public');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_VISIBILITY_NOT_LISTED', 'Not listed');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_VISIBILITY_PRIVATE', 'Private');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_VISIBILITY_MAKE_PUBLIC', 'Make public');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_VISIBILITY_MAKE_NOT_LISTED', 'Make not listed');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_VISIBILITY_MAKE_PRIVATE', 'Make private');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_DELETE', 'Delete portfolio');

-- Comment translations
insert into Translation(translationGroup, translationKey, translation) values (3, 'COMMENTS_TITLE', 'Comments');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ADD_COMMENT_TITLE', 'Add a comment');
insert into Translation(translationGroup, translationKey, translation) values (3, 'COMMENT', 'Comment');
insert into Translation(translationGroup, translationKey, translation) values (3, 'ADD_COMMENT_BUTTON', 'Send');

-- Taxon Domain translations
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_ME_AND_THE_ENVIRONMENT', 'Me and the environment');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_LANGUAGE_AND_SPEECH', 'Language and speach');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_ESTONIAN', 'Estonian');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_MATHEMATICS', 'Mathematics');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_ARTS', 'Arts');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_MUSIC', 'Music');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_MOVEMENT', 'Movement');

insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_LANGUAGE_AND_LITERATURE', 'Language and literature');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_FOREIGN_LANGUAGE', 'Foreign language');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_NATURAL_SCIENCES', 'Natural sciences');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_SOCIAL_STUDIES', 'Social studies');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_TECHNOLOGY', 'Technology');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_PHYSICAL_EDUCATION', 'Physical educational');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_ELECTIVES', 'Electives');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_CROSS-CURRICULAR_THEMES', 'Cross-curricular themes');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_KEY_COMPETENCES', 'Key competences');
insert into Translation(translationGroup, translationKey, translation) values (3, 'DOMAIN_COMPUTER_SCIENCE', 'Computer science');

-- Taxon Topic translations
insert into Translation(translationGroup, translationKey, translation) values (3, 'TOPIC_BASIC_HISTORY', 'Basic history');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TOPIC_ESTONIAN_HISTORY', 'Estonian history');

-- Taxon Subject translations
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_ESTONIAN', 'Estonian');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_RUSSIAN', 'Russian');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_LITERATURE', 'Literature');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_ENGLISH', 'English');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_FRENCH', 'French');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_GERMAN', 'German');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_SWEDISH', 'Swedish');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_FINNISH', 'Finnish');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_LATIN', 'Latin');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_CHINESE', 'Chinese');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_JAPANESE', 'Japanese');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_MATHEMATICS', 'Mathematics');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_SCIENCE', 'Science');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_BIOLOGY', 'Biology');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_GEOGRAPHY', 'Geography');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_PHYSICS', 'Physics');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_CHEMISTRY', 'Chemistry');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_HUMAN_STUDIES', 'Human studies');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_HISTORY', 'History');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_CIVICS_AND_CITIZENSHIP', 'Civics and citizenship');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_ART', 'Art');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_MUSIC', 'Music');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_TECHNOLOGY', 'Technology');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_HANDICRAFT', 'Handicraft');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_HOME_ECONOMICS', 'Home economics');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_EDUCATIONAL_TECHNOLOGY', 'Educational technology');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_PHYSICAL_EDUCATION', 'Physical education');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_RELIGIOUS_STUDIES', 'Religious studies');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_INFORMATICS', 'Informatics');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_CAREER_STUDIES', 'Career studies');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_ECONOMICS_AND_BUSINESS_STUDIES', 'Economics and business studies');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_MEDIA_STUDIES', 'Media studies');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_NATIONAL_DEFENCE', 'National defence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_BASICS_OF_INQUIRY', 'Basics of inquiry');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_PHILOSOPHY', 'Philosophy');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_LIFELONG_LEARNING_AND_CAREER_PLANNING', 'Lifelong learning and career planning');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_ENVIRONMENT_AND_SUSTAINABLE_DEVELOPMENT', 'Environment and sustainable development');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_CIVIC_INITIATIVE_AND_ENTREPRENEURSHIP', 'Civic initiative and entrepreneurship');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_CULTURAL_IDENTITY', 'Cultural identity');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_INFORMATION_ENVIRONMENT', 'Information environment');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_TECHNOLOGY_AND_INNOVATION', 'Technology and innovation');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_HEALTH_AND_SAFETY', 'Health and safety');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_VALUES_AND_MORAL', 'Values and moral');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_CULTURAL_AND_VALUE_COMPETENCE', 'Cultural and value competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_SOCIAL_AND_CITIZENSHIP_COMPETENCE', 'Social and citizenship competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_SELF_MANAGEMENT_COMPETENCE', 'Self-management competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_LEARNING_TO_LEARN_COMPETENCE', 'Learning to learn competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_COMMUNICATION_COMPETENCE', 'Communication competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_MATHEMATICS_NATURAL_SCIENCES_AND_TECHNOLOGY_COMPETENCE', 'Mathematics, natural sciences and technology competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_ENTREPRENEURSHIP_COMPETENCE', 'Entrepreneurship competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_DIGITAL_COMPETENCE', 'Digital competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'SUBJECT_OTHER', 'Other');

-- Taxon path
insert into Translation(translationGroup, translationKey, translation) values (3, 'TAXON_PATH_DOMAIN', 'Domain');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TAXON_PATH_SPECIALIZATION', 'Specialization');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TAXON_PATH_MODULE', 'Module');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TAXON_PATH_TOPIC', 'Topic');
insert into Translation(translationGroup, translationKey, translation) values (3, 'TAXON_PATH_SUBTOPIC', 'Subtopic');

-- Cross-curricular theme translations
insert into Translation(translationGroup, translationKey, translation) values (3, 'CROSS_CURRICULAR_THEME_LIFELONG_LEARNING_AND_CAREER_PLANNING', 'Lifelong learning and career planning');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CROSS_CURRICULAR_THEME_ENVIRONMENT_AND_SUSTAINABLE_DEVELOPMENT', 'Environment and sustainable development');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CROSS_CURRICULAR_THEME_CIVIC_INITIATIVE_AND_ENTREPRENEURSHIP', 'Civic initiative and entrepreneurship');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CROSS_CURRICULAR_THEME_CULTURAL_IDENTITY', 'Cultural identity');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CROSS_CURRICULAR_THEME_INFORMATION_ENVIRONMENT', 'Information environment');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CROSS_CURRICULAR_THEME_TECHNOLOGY_AND_INNOVATION', 'Technology and innovation');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CROSS_CURRICULAR_THEME_HEALTH_AND_SAFETY', 'Health and safety');
insert into Translation(translationGroup, translationKey, translation) values (3, 'CROSS_CURRICULAR_THEME_VALUES_AND_MORAL', 'Values and moral');

-- Key competences translations
insert into Translation(translationGroup, translationKey, translation) values (3, 'KEY_COMPETENCE_CULTURAL_AND_VALUE_COMPETENCE', 'Cultural and value competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'KEY_COMPETENCE_SOCIAL_AND_CITIZENSHIP_COMPETENCE', 'Social and citizenship competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'KEY_COMPETENCE_SELF_MANAGEMENT_COMPETENCE', 'Self-management competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'KEY_COMPETENCE_LEARNING_TO_LEARN_COMPETENCE', 'Learning to learn competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'KEY_COMPETENCE_COMMUNICATION_COMPETENCE', 'Communication competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'KEY_COMPETENCE_MATHEMATICS_NATURAL_SCIENCES_AND_TECHNOLOGY_COMPETENCE', 'Mathematics, natural sciences and technology competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'KEY_COMPETENCE_ENTREPRENEURSHIP_COMPETENCE', 'Entrepreneurship competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'KEY_COMPETENCE_DIGITAL_COMPETENCE', 'Digital competence');

-- Language name translations, more can be added using the same conventions for the translation key
insert into Translation(translationGroup, translationKey, translation) values (3, 'LANGUAGE', 'Language');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LANGUAGE_EST', 'Estonian');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LANGUAGE_RUS', 'Russian');
insert into Translation(translationGroup, translationKey, translation) values (3, 'LANGUAGE_ENG', 'English');

-- Add Material translations
insert into Translation(translationGroup, translationKey, translation) values (3, 'ADD_MATERIAL', 'Add material');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_URL', 'Material URL');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_URL_IS_MANDATORY', 'Material URL is required');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_URL_IS_INVALID', 'Material URL is not correct format');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_TITLE_DESCRIPTION', 'Title and description');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_ADDITIONAL_DATA', 'Additional title');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_TITLE', 'Title');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_DESCRIPTION', 'Description');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_PUBLISHER', 'Publisher');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_AUTHOR_NAME', 'Authors firstname');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_AUTHOR_SURNAME', 'Authors lastname');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_TAGS', 'Tags');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_HOW_TO_SAVE_TAG', '*Press Enter to save a tag');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_PHOTO', 'Material picture');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_PHOTO_UPLOAD_HELP', 'Drag picture here or select from computer');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_PHOTO_PREVIEW', 'Preview');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_TAXON', 'Taxonomy');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_ADD_TAG', 'Add tag');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_REMOVE_TAG', 'Remove tag');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_REMOVE_TAG_HINT', 'Click x to remove tag');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_SEARCH_KEY_COMPETENCE', 'Search for a key competence');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_KEY_COMPETENCES', 'Key competences');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_SEARCH_CROSS_CURRICULAR_THEME', 'Search for a cross-curricular theme');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_CROSS_CURRICULAR_THEMES', 'Cross-curricular themes');


-- Add Material tab translations
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_TAB_URL', 'URL');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_TAB_MAIN_DATA', 'Main data');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_TAB_ADDITIONAL_DATA', 'Additional data');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_TAB_TYPE', 'Type');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_TAB_PICTURE', 'Picture');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_TAB_TAXON', 'Taxonomy');

-- Like box translations
insert into Translation(translationGroup, translationKey, translation) values (3, 'RATING_LIKE', 'I like this');
insert into Translation(translationGroup, translationKey, translation) values (3, 'RATING_DISLIKE', 'I dont like this');
insert into Translation(translationGroup, translationKey, translation) values (3, 'RATING_LIKE_REMOVED', 'Like removed');
insert into Translation(translationGroup, translationKey, translation) values (3, 'RATING_DISLIKE_REMOVED', 'Dislike removed');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_LIKED', 'Material liked!');
insert into Translation(translationGroup, translationKey, translation) values (3, 'MATERIAL_DISLIKED', 'Material disliked!');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_LIKED', 'Portfolio liked!');
insert into Translation(translationGroup, translationKey, translation) values (3, 'PORTFOLIO_DISLIKED', 'Portfolio disliked!');

insert into Translation(translationGroup, translationKey, translation) values (3, 'COPY_PORTFOLIO', 'Copy portfolio');
insert into Translation(translationGroup, translationKey, translation) values (3, 'COPY_URL', 'Copy link');

-- Report
insert into Translation(translationGroup, translationKey, translation) values (3, 'REPORT_IMPROPER', 'Notify of improper content');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REPORT_IMPROPER_TITLE', 'Would you like to notify of improper content?');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REPORT_IMPROPER_CONTENT', 'Adminstrator will recive your notification and will take necessary actions.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BUTTON_NOTIFY', 'Notify');

insert into Translation(translationGroup, translationKey, translation) values (3, 'REPORT_BROKEN_LINK', 'Report broken material');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REPORT_BROKEN_LINK_TITLE', 'Would you like to report a broken material?');
insert into Translation(translationGroup, translationKey, translation) values (3, 'REPORT_BROKEN_LINK_CONTENT', 'Adminstrator will recive your notification and will take necessary actions.');
insert into Translation(translationGroup, translationKey, translation) values (3, 'BUTTON_REPORT', 'Report');

insert into Translation(translationGroup, translationKey, translation) values (3, 'RECOMMEND', 'Recommend');
