-- Estonian translations
insert into Translation(translationGroup, translationKey, translation) values (1, 'LOGIN', 'Logi sisse');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LOGOUT', 'Logi välja');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAIL_VIEW_SUBJECT', 'Teema');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MATERIAL_VIEW_RESOURCE_TYPE', 'Tüüp');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAIL_VIEW_EDUCATIONAL_CONTEXT', 'Haridustase');
insert into Translation(translationGroup, translationKey, translation) values (1, 'UPDATED', 'Uuendatud');
insert into Translation(translationGroup, translationKey, translation) values (1, 'CREATED', 'Loodud');
insert into Translation(translationGroup, translationKey, translation) values (1, 'REPOSITORY_NUMBER', 'Repositooriumi number');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MATERIAL_VIEW_LICENSE_TYPE', 'Litsentsi tüüp');
insert into Translation(translationGroup, translationKey, translation) values (1, 'AUDIO', 'Audio');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DATA', 'Andmed');
insert into Translation(translationGroup, translationKey, translation) values (1, 'IMAGE', 'Pilt');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TEXT', 'Tekst');
insert into Translation(translationGroup, translationKey, translation) values (1, 'VIDEO', 'Video');
insert into Translation(translationGroup, translationKey, translation) values (1, 'APPLICATION', 'Rakendus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ASSESSMENT', 'Hinnang');
insert into Translation(translationGroup, translationKey, translation) values (1, 'BROADCAST', 'Saade');
insert into Translation(translationGroup, translationKey, translation) values (1, 'CASESTUDY', 'Juhtumiuuring');
insert into Translation(translationGroup, translationKey, translation) values (1, 'COURSE', 'Kursus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DEMONSTRATION', 'Näide');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DRILLANDPRACTICE', 'Drilli ja harjuta');
insert into Translation(translationGroup, translationKey, translation) values (1, 'EDUCATIONALGAME', 'Hariv mäng');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ENQUIRYORIENTEDACTIVITY', 'Mõtlema panev tegevus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'EXPERIMENT', 'Katse');
insert into Translation(translationGroup, translationKey, translation) values (1, 'EXPLORATION', 'Avastamine');
insert into Translation(translationGroup, translationKey, translation) values (1, 'GLOSSARY', 'Sõnastik');
insert into Translation(translationGroup, translationKey, translation) values (1, 'GUIDE', 'Juhend');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LESSONPLAN', 'Tunniplaan');
insert into Translation(translationGroup, translationKey, translation) values (1, 'OPENACTIVITY', 'Avatud tegevus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'OTHER', 'Muu');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PRESENTATION', 'Ettekanne');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PROJECT', 'Projekt');
insert into Translation(translationGroup, translationKey, translation) values (1, 'REFERENCE', 'Viide');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ROLEPLAY', 'Rollimäng');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SIMULATION', 'Simulatsioon');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TEXTBOOK', 'Õpik');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TOOL', 'Tööriist');
insert into Translation(translationGroup, translationKey, translation) values (1, 'WEBSITE', 'Veebileht');
insert into Translation(translationGroup, translationKey, translation) values (1, 'BOOKMARKSHARINGPLATFORM', 'Järjehoidja jagamise platvorm');
insert into Translation(translationGroup, translationKey, translation) values (1, 'IMAGESHARINGPLATFORM', 'Pildi jagamise platvorm');
insert into Translation(translationGroup, translationKey, translation) values (1, 'REFERENCESHARINGPLATFORM', 'Viite jagamise platvorm');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SOUNDSHARINGPLATFORM', 'Heli jagamise platvorm');
insert into Translation(translationGroup, translationKey, translation) values (1, 'VIDEOSHARINGPLATFORM', 'Video jagamise platvorm');
insert into Translation(translationGroup, translationKey, translation) values (1, 'WEBLOG', 'veebilogi');
insert into Translation(translationGroup, translationKey, translation) values (1, 'WIKI', 'viki');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PRESCHOOLEDUCATION', 'Eelkooli haridus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'BASICEDUCATION', 'Põhiharidus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SECONDARYEDUCATION', 'Keskharidus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'HIGHEREDUCATION', 'Kõrgharidus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'VOCATIONALEDUCATION', 'Kutseharidus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'CONTINUINGEDUCATION', 'Täiendõpe');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TEACHEREDUCATION', 'Õpetajaharidus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SPECIALEDUCATION', 'Eripdagoogika');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MATERIAL_VIEW_LINK_TO_MATERIAL', 'Ava õppematerjal');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PUBLISHER', 'Kirjastaja');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PUBLISHERS', 'Kirjastajad');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SEARCH', 'Otsi');
insert into Translation(translationGroup, translationKey, translation) values (1, 'UNKNOWN', 'Teadmata');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ABOUT_PAGE_LINK_TITLE', 'Mis see on?');
insert into Translation(translationGroup, translationKey, translation) values (1, 'HELP_PAGE_LINK_TITLE', 'Kuidas eKoolikotti kasutada?');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LANDING_PAGE_TITLE_NEWEST', 'Uusimad');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_ALLRIGHTSRESERVED', 'Kõik õigused kaitstud');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_CCBY', 'CC BY');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_CCBYSA', 'CC BY-SA');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_CCBYND', 'CC BY-ND');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_CCBYNC', 'CC BY-NC');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_CCBYNCSA', 'CC BY-NC-SA');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_CCBYNCND', 'CC BY-NC-ND');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LICENSETYPE_OTHER', 'Muu');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAIL_VIEW_TAGS', 'Võtmesõnad');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SEARCH_RESULT_NO_RESULT', 'Ühtegi vastust ei leitud.');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SEARCH_RESULT_PART_1', 'Otsingule leidus ');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SEARCH_RESULT_PART_2', ' vastet.');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SEARCH_RESULT_1_RESULT_PART_1', 'Otsingule leidus ');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SEARCH_RESULT_1_RESULT_PART_2', ' vaste.');
insert into Translation(translationGroup, translationKey, translation) values (1, 'COPYRIGHT_FOOTER', '© 2016 Kõik õigused kaitstud. Haridus- ja Teadusministeerium');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SEARCH_RESULT_PREVIOUS', 'Eelmine');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SEARCH_RESULT_NEXT', 'Järgmine');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MYPROFILE_PAGE_TITLE_PORTFOLIOS', 'Minu õpimapid');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MYPROFILE_PAGE_TITLE_MATERIALS', 'Minu materjalid');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MYPROFILE_PAGE_TITLE_MY_DATA', 'Minu andmed');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PROFILE_PAGE_TITLE_PORTFOLIOS', 'Õpimapid');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PROFILE_PAGE_TITLE_MATERIALS', 'Materjalid');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LOGIN_CHOOSE_LOGIN_METHOD', 'Vali sisenemise moodus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LOGIN_FACEBOOK', 'Facebook');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LOGIN_GOOGLE', 'Google');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LOGIN_TAAT', 'TAAT');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LOGIN_IDCARD', 'ID-kaart');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LOGIN_MOBILEID', 'Mobiil-ID');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LOGIN_MOBILEID_CODE', 'Sinu kood on');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LOGIN_SMS', 'Kontrollige, et SMSi teel saabunud kontrollkood ühtiks arvutiekraanil näidatuga.');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ERROR_LOGIN_FAILED', 'Sisselogimine ebaõnnestus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ERROR_MATERIAL_NOT_FOUND', 'Materjali ei leitud');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MATERIAL_PAID', 'Tasuline');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ERROR_PORTFOLIO_NOT_FOUND', 'Õpimappi ei leitud');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MY_PROFILE', 'Minu profiil');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ERROR_GETTING_USER_FAILED', 'Kasutajat ei leitud');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PERSONAL_CODE', 'Isikukood');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MESSAGE_ERROR_PERSONAL_CODE_REQUIRED', 'Isikukood on nõutud');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MESSAGE_ERROR_PERSONAL_CODE_INVALID', 'Isikukood ei ole korrektne');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MESSAGE_ERROR_PHONE_NUMBER_REQUIRED', 'Telefoninumber on nõutud');
insert into Translation(translationGroup, translationKey, translation) values (1, 'MESSAGE_ERROR_PHONE_NUMBER_NOT_ESTONIAN', 'Telefoninumber peab olema Eesti koodiga');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAILED_SEARCH_OPEN', 'Täppis- otsing');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAILED_SEARCH_TITLE', 'Pealkiri');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAILED_SEARCH_DESCRIPTION', 'Kirjeldus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAILED_SEARCH_AUTHOR', 'Autor');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAILED_SEARCH_SUBMIT', 'Otsi');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAILED_SEARCH_MATERIALS', 'Materjalid');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAILED_SEARCH_PORTFOLIOS', 'Portfooliod');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAILED_SEARCH_ALL', 'Kõik');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAILED_SEARCH_MAIN', 'Põhiväli');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAILED_SEARCH_ON', 'Jah');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAILED_SEARCH_OFF', 'Ei');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAILED_SEARCH_INCLUDE_PAID', 'Kaasa tasulised');
insert into Translation(translationGroup, translationKey, translation) values (1, 'DETAILED_SEARCH_TARGET_GROUP', 'Vanuserühm');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ADD_PORTFOLIO', 'Lisa portfolio');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PORTFOLIO_TITLE', 'Pealkiri');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PORTFOLIO_SUMMARY', 'Kokkuvõte');
insert into Translation(translationGroup, translationKey, translation) values (1, 'PORTFOLIO_METADATA_TOOLBAR_LABEL', 'Lisa portfolio põhiandmed');
insert into Translation(translationGroup, translationKey, translation) values (1, 'BUTTON_CANCEL', 'Katkesta');
insert into Translation(translationGroup, translationKey, translation) values (1, 'BUTTON_CREATE_PORTFOLIO', 'Loo portfolio');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TARGET_GROUP_ZERO_FIVE', '0-5');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TARGET_GROUP_SIX_SEVEN', '6-7');

-- Taxon Domain translations
insert into Translation(translationGroup, translationKey, translation) values (1, 'DOMAIN_LANGUAGE_AND_SPEECH', 'Keel ja kõne');

-- Taxon Topic translations
insert into Translation(translationGroup, translationKey, translation) values (1, 'TOPIC_BASIC_HISTORY', 'Ajaloo algõpetus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TOPIC_ESTONIAN_HISTORY', 'Eesti ajalugu');

-- Material Subject translations
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_ESTONIAN', 'Eesti keel');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_RUSSIAN', 'Vene keel');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_LITERATURE', 'Kirjandus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_ENGLISH', 'Inglise keel');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_FRENCH', 'Prantsuse keel');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_GERMAN', 'Saksa keel');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_SWEDISH', 'Rootsi keel');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_FINNISH', 'Soome keel');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_LATIN', 'Ladina keel');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_CHINESE', 'Hiina keel');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_JAPANESE', 'Jaapani keel');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_MATHEMATICS', 'Matemaatika');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_SCIENCE', 'Loodusõpetus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_BIOLOGY', 'Bioloogia');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_GEOGRAPHY', 'Geograafia');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_PHYSICS', 'Füüsika');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_CHEMISTRY', 'Keemia');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_HUMAN_STUDIES', 'Inimeseõpetus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_HISTORY', 'Ajalugu');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_CIVICS_AND_CITIZENSHIP', 'Ühiskonnaõpetus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_ART', 'Kunst');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_MUSIC', 'Muusika');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_TECHNOLOGY', 'Töö- ja tehnoloogiaõpetus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_HANDICRAFT', 'Käsitöö');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_HOME_ECONOMICS', 'Kodundus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_EDUCATIONAL_TECHNOLOGY', 'Haridustehnoloogia');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_PHYSICAL_EDUCATION', 'Kehaline kasvatus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_RELIGIOUS_STUDIES', 'Usundiõpetus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_INFORMATICS', 'Informaatika');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_CAREER_STUDIES', 'Karjääriõpe');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_ECONOMICS_AND_BUSINESS_STUDIES', 'Majandus ja ettevõtlus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_MEDIA_STUDIES', 'Meediaõpetus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_NATIONAL_DEFENCE', 'Riigikaitse');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_BASICS_OF_INQUIRY', 'Uurimise alused');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_PHILOSOPHY', 'Filosoofia');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_LIFELONG_LEARNING_AND_CAREER_PLANNING', 'Elukestev õpe ja karjääriplaneerimine');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_ENVIRONMENT_AND_SUSTAINABLE_DEVELOPMENT', 'Keskkond ja säästev areng');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_CIVIC_INITIATIVE_AND_ENTREPRENEURSHIP', 'Kodanikualgatus ja ettevõtlikkus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_CULTURAL_IDENTITY', 'Kultuuriline identiteet');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_INFORMATION_ENVIRONMENT', 'Informatsioonikeskkond');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_TECHNOLOGY_AND_INNOVATION', 'Tehnoloogia ja innovatsioon');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_HEALTH_AND_SAFETY', 'Tervis ja ohutus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_VALUES_AND_MORAL', 'Väärtused ja moraal');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_CULTURAL_AND_VALUE_COMPETENCE', 'Kultuuri- ja väärtuste pädevus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_SOCIAL_AND_CITIZENSHIP_COMPETENCE', 'Sotsiaal- ja kodakondsuse pädevus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_SELF_MANAGEMENT_COMPETENCE', 'Enesejuhtimise pädevus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_LEARNING_TO_LEARN_COMPETENCE', 'Õpipädevus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_COMMUNICATION_COMPETENCE', 'Suhtluspädevus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_MATHEMATICS_NATURAL_SCIENCES_AND_TECHNOLOGY_COMPETENCE', 'Matemaatika-, loodusteaduste- ja tehnoloogiapädevus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_ENTREPRENEURSHIP_COMPETENCE', 'Ettevõtluspädevus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_DIGITAL_COMPETENCE', 'Infotehnoloogiline pädevus');
insert into Translation(translationGroup, translationKey, translation) values (1, 'SUBJECT_OTHER', 'Muu');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TABLE_OF_CONTENTS', 'Sisukord');

-- Comment translations
insert into Translation(translationGroup, translationKey, translation) values (1, 'COMMENTS_TITLE', 'Kommentaarid');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ADD_COMMENT_TITLE', 'Lisa kommentaar');
insert into Translation(translationGroup, translationKey, translation) values (1, 'COMMENT', 'Kommentaar');
insert into Translation(translationGroup, translationKey, translation) values (1, 'ADD_COMMENT_BUTTON', 'Saada');

-- Taxon path

insert into Translation(translationGroup, translationKey, translation) values (1, 'TAXON_PATH_DOMAIN', 'Domeen');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TAXON_PATH_SPECIALIZATION', 'Eriala');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TAXON_PATH_MODULE', 'Moodul');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TAXON_PATH_TOPIC', 'Teema');
insert into Translation(translationGroup, translationKey, translation) values (1, 'TAXON_PATH_SUBTOPIC', 'Alamteema');

-- Language name translations, more can be added using the same conventions for the translation key
insert into Translation(translationGroup, translationKey, translation) values (1, 'LANGUAGE_ESTONIAN', 'Eesti');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LANGUAGE_RUSSIAN', 'Vene');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LANGUAGE_ENGLISH', 'Inglise');
insert into Translation(translationGroup, translationKey, translation) values (1, 'LANGUAGE_NORTHERN_SAMI', 'Põhjasaami');
