USE dop;

-- LanguageTable

insert into LanguageTable(id, name, code) values (1, 'Estonian', 'est');
insert into LanguageTable(id, name, code) values (2, 'Russian', 'rus');
insert into LanguageTable(id, name, code) values (3, 'English', 'eng');

insert into LanguageTable(id, name, code) values (4, 'Abkhaz', 'abk');
insert into LanguageTable(id, name, code) values (5, 'Afar', 'aar');
insert into LanguageTable(id, name, code) values (6, 'Afrikaans', 'afr');
insert into LanguageTable(id, name, code) values (7, 'Akan', 'aka');
insert into LanguageTable(id, name, code) values (8, 'Albanian', 'alb');
insert into LanguageTable(id, name, code) values (9, 'Amharic', 'amh');
insert into LanguageTable(id, name, code) values (10, 'Arabic', 'ara');
insert into LanguageTable(id, name, code) values (11, 'Aragonese', 'arg');
insert into LanguageTable(id, name, code) values (12, 'Armenian', 'arm');
insert into LanguageTable(id, name, code) values (13, 'Assamese', 'asm');
insert into LanguageTable(id, name, code) values (14, 'Avaric', 'ava');
insert into LanguageTable(id, name, code) values (15, 'Avestan', 'ave');
insert into LanguageTable(id, name, code) values (16, 'Aymara', 'aym');
insert into LanguageTable(id, name, code) values (17, 'Azerbaijani', 'aze');
insert into LanguageTable(id, name, code) values (18, 'Bambara', 'bam');
insert into LanguageTable(id, name, code) values (19, 'Bashkir', 'bak');
insert into LanguageTable(id, name, code) values (20, 'Basque', 'baq');
insert into LanguageTable(id, name, code) values (21, 'Belarusian', 'bel');
insert into LanguageTable(id, name, code) values (22, 'Bengali', 'ben');
insert into LanguageTable(id, name, code) values (23, 'Bihari', 'bih');
insert into LanguageTable(id, name, code) values (24, 'Bislama', 'bis');
insert into LanguageTable(id, name, code) values (25, 'Bosnian', 'bos');
insert into LanguageTable(id, name, code) values (26, 'Breton', 'bre');
insert into LanguageTable(id, name, code) values (27, 'Bulgarian', 'bul');
insert into LanguageTable(id, name, code) values (28, 'Burmese', 'bur');
insert into LanguageTable(id, name, code) values (29, 'Catalan', 'cat');
insert into LanguageTable(id, name, code) values (30, 'Chamorro', 'cha');
insert into LanguageTable(id, name, code) values (31, 'Chechen', 'che');
insert into LanguageTable(id, name, code) values (32, 'Chichewa', 'nya');
insert into LanguageTable(id, name, code) values (33, 'Chinese', 'chi');
insert into LanguageTable(id, name, code) values (34, 'Chuvash', 'chv');
insert into LanguageTable(id, name, code) values (35, 'Cornish', 'cor');
insert into LanguageTable(id, name, code) values (36, 'Corsican', 'cos');
insert into LanguageTable(id, name, code) values (37, 'Cree', 'cre');
insert into LanguageTable(id, name, code) values (38, 'Croatian', 'hrv');
insert into LanguageTable(id, name, code) values (39, 'Czech', 'cze');
insert into LanguageTable(id, name, code) values (40, 'Danish', 'dan');
insert into LanguageTable(id, name, code) values (41, 'Divehi', 'div');
insert into LanguageTable(id, name, code) values (42, 'Dutch', 'dut');
insert into LanguageTable(id, name, code) values (43, 'Dzongkha', 'dzo');
insert into LanguageTable(id, name, code) values (44, 'Esperanto', 'epo');
insert into LanguageTable(id, name, code) values (45, 'Ewe', 'ewe');
insert into LanguageTable(id, name, code) values (46, 'Faroese', 'fao');
insert into LanguageTable(id, name, code) values (47, 'Fijian', 'fij');
insert into LanguageTable(id, name, code) values (48, 'Finnish', 'fin');
insert into LanguageTable(id, name, code) values (49, 'French', 'fre');
insert into LanguageTable(id, name, code) values (50, 'Fula', 'ful');
insert into LanguageTable(id, name, code) values (51, 'Galician', 'glg');
insert into LanguageTable(id, name, code) values (52, 'Georgian', 'geo');
insert into LanguageTable(id, name, code) values (53, 'German', 'ger');
insert into LanguageTable(id, name, code) values (54, 'Greek', 'gre');
insert into LanguageTable(id, name, code) values (55, 'Guaraní', 'grn');
insert into LanguageTable(id, name, code) values (56, 'Gujarati', 'guj');
insert into LanguageTable(id, name, code) values (57, 'Haitian', 'hat');
insert into LanguageTable(id, name, code) values (58, 'Hausa', 'hau');
insert into LanguageTable(id, name, code) values (59, 'Hebrew', 'heb');
insert into LanguageTable(id, name, code) values (60, 'Herero', 'her');
insert into LanguageTable(id, name, code) values (61, 'Hindi', 'hin');
insert into LanguageTable(id, name, code) values (62, 'Hiri Motu', 'hmo');
insert into LanguageTable(id, name, code) values (63, 'Hungarian', 'hun');
insert into LanguageTable(id, name, code) values (64, 'Interlingua', 'ina');
insert into LanguageTable(id, name, code) values (65, 'Indonesian', 'ind');
insert into LanguageTable(id, name, code) values (66, 'Interlingue', 'ile');
insert into LanguageTable(id, name, code) values (67, 'Irish', 'gle');
insert into LanguageTable(id, name, code) values (68, 'Igbo', 'ibo');
insert into LanguageTable(id, name, code) values (69, 'Inupiaq', 'ipk');
insert into LanguageTable(id, name, code) values (70, 'Ido', 'ido');
insert into LanguageTable(id, name, code) values (71, 'Icelandic', 'ice');
insert into LanguageTable(id, name, code) values (72, 'Italian', 'ita');
insert into LanguageTable(id, name, code) values (73, 'Inuktitut', 'iku');
insert into LanguageTable(id, name, code) values (74, 'Japanese', 'jpn');
insert into LanguageTable(id, name, code) values (75, 'Javanese', 'jav');
insert into LanguageTable(id, name, code) values (76, 'Kalaallisut', 'kal');
insert into LanguageTable(id, name, code) values (77, 'Kannada', 'kan');
insert into LanguageTable(id, name, code) values (78, 'Kanuri', 'kau');
insert into LanguageTable(id, name, code) values (79, 'Kashmiri', 'kas');
insert into LanguageTable(id, name, code) values (80, 'Kazakh', 'kaz');
insert into LanguageTable(id, name, code) values (81, 'Khmer', 'khm');
insert into LanguageTable(id, name, code) values (82, 'Kikuyu', 'kik');
insert into LanguageTable(id, name, code) values (83, 'Kinyarwanda', 'kin');
insert into LanguageTable(id, name, code) values (84, 'Kyrgyz', 'kir');
insert into LanguageTable(id, name, code) values (85, 'Komi', 'kom');
insert into LanguageTable(id, name, code) values (86, 'Kongo', 'kon');
insert into LanguageTable(id, name, code) values (87, 'Korean', 'kor');
insert into LanguageTable(id, name, code) values (88, 'Kurdish', 'kur');
insert into LanguageTable(id, name, code) values (89, 'Kwanyama', 'kua');
insert into LanguageTable(id, name, code) values (90, 'Latin', 'lat');
insert into LanguageTable(id, name, code) values (91, 'Luxembourgish', 'ltz');
insert into LanguageTable(id, name, code) values (92, 'Ganda', 'lug');
insert into LanguageTable(id, name, code) values (93, 'Limburgish', 'lim');
insert into LanguageTable(id, name, code) values (94, 'Lingala', 'lin');
insert into LanguageTable(id, name, code) values (95, 'Lao', 'lao');
insert into LanguageTable(id, name, code) values (96, 'Lithuanian', 'lit');
insert into LanguageTable(id, name, code) values (97, 'Luba-Katanga', 'lub');
insert into LanguageTable(id, name, code) values (98, 'Latvian', 'lav');
insert into LanguageTable(id, name, code) values (99, 'Manx', 'glv');
insert into LanguageTable(id, name, code) values (100, 'Macedonian', 'mac');
insert into LanguageTable(id, name, code) values (101, 'Malagasy', 'mlg');
insert into LanguageTable(id, name, code) values (102, 'Malay', 'may');
insert into LanguageTable(id, name, code) values (103, 'Malayalam', 'mal');
insert into LanguageTable(id, name, code) values (104, 'Maltese', 'mlt');
insert into LanguageTable(id, name, code) values (105, 'Māori', 'mao');
insert into LanguageTable(id, name, code) values (106, 'Marathi', 'mar');
insert into LanguageTable(id, name, code) values (107, 'Marshallese', 'mah');
insert into LanguageTable(id, name, code) values (108, 'Mongolian', 'mon');
insert into LanguageTable(id, name, code) values (109, 'Nauru', 'nau');
insert into LanguageTable(id, name, code) values (110, 'Navajo', 'nav');
insert into LanguageTable(id, name, code) values (111, 'Northern Ndebele', 'nde');
insert into LanguageTable(id, name, code) values (112, 'Nepali', 'nep');
insert into LanguageTable(id, name, code) values (113, 'Ndonga', 'ndo');
insert into LanguageTable(id, name, code) values (114, 'Norwegian Bokmål', 'nob');
insert into LanguageTable(id, name, code) values (115, 'Norwegian Nynorsk', 'nno');
insert into LanguageTable(id, name, code) values (116, 'Norwegian', 'nor');
insert into LanguageTable(id, name, code) values (117, 'Nuosu', 'iii');
insert into LanguageTable(id, name, code) values (118, 'Southern Ndebele', 'nbl');
insert into LanguageTable(id, name, code) values (119, 'Occitan', 'oci');
insert into LanguageTable(id, name, code) values (120, 'Ojibwe', 'oji');
insert into LanguageTable(id, name, code) values (121, 'Old Church Slavonic', 'chu');
insert into LanguageTable(id, name, code) values (122, 'Oromo', 'orm');
insert into LanguageTable(id, name, code) values (123, 'Oriya', 'ori');
insert into LanguageTable(id, name, code) values (124, 'Ossetian', 'oss');
insert into LanguageTable(id, name, code) values (125, 'Panjabi', 'pan');
insert into LanguageTable(id, name, code) values (126, 'Pāli', 'pli');
insert into LanguageTable(id, name, code) values (127, 'Persian', 'per');
insert into LanguageTable(id, name, code) values (128, 'Polish', 'pol');
insert into LanguageTable(id, name, code) values (129, 'Pashto', 'pus');
insert into LanguageTable(id, name, code) values (130, 'Portuguese', 'por');
insert into LanguageTable(id, name, code) values (131, 'Quechua', 'que');
insert into LanguageTable(id, name, code) values (132, 'Romansh', 'roh');
insert into LanguageTable(id, name, code) values (133, 'Kirundi', 'run');
insert into LanguageTable(id, name, code) values (134, 'Romanian', 'rum');
insert into LanguageTable(id, name, code) values (135, 'Sanskrit', 'san');
insert into LanguageTable(id, name, code) values (136, 'Sardinian', 'srd');
insert into LanguageTable(id, name, code) values (137, 'Sindhi', 'snd');
insert into LanguageTable(id, name, code) values (138, 'Northern Sami', 'sme');
insert into LanguageTable(id, name, code) values (139, 'Samoan', 'smo');
insert into LanguageTable(id, name, code) values (140, 'Sango', 'sag');
insert into LanguageTable(id, name, code) values (141, 'Serbian', 'srp');
insert into LanguageTable(id, name, code) values (142, 'Scottish Gaelic', 'gla');
insert into LanguageTable(id, name, code) values (143, 'Shona', 'sna');
insert into LanguageTable(id, name, code) values (144, 'Sinhala', 'sin');
insert into LanguageTable(id, name, code) values (145, 'Slovak', 'slo');
insert into LanguageTable(id, name, code) values (146, 'Slovene', 'slv');
insert into LanguageTable(id, name, code) values (147, 'Somali', 'som');
insert into LanguageTable(id, name, code) values (148, 'Southern Sotho', 'sot');
insert into LanguageTable(id, name, code) values (149, 'Spanish', 'spa');
insert into LanguageTable(id, name, code) values (150, 'Sundanese', 'sun');
insert into LanguageTable(id, name, code) values (151, 'Swahili', 'swa');
insert into LanguageTable(id, name, code) values (152, 'Swati', 'ssw');
insert into LanguageTable(id, name, code) values (153, 'Swedish', 'swe');
insert into LanguageTable(id, name, code) values (154, 'Tamil', 'tam');
insert into LanguageTable(id, name, code) values (155, 'Telugu', 'tel');
insert into LanguageTable(id, name, code) values (156, 'Tajik', 'tgk');
insert into LanguageTable(id, name, code) values (157, 'Thai', 'tha');
insert into LanguageTable(id, name, code) values (158, 'Tigrinya', 'tir');
insert into LanguageTable(id, name, code) values (159, 'Tibetan Standard', 'tib');
insert into LanguageTable(id, name, code) values (160, 'Turkmen', 'tuk');
insert into LanguageTable(id, name, code) values (161, 'Tagalog', 'tgl');
insert into LanguageTable(id, name, code) values (162, 'Tswana', 'tsn');
insert into LanguageTable(id, name, code) values (163, 'Tonga', 'ton');
insert into LanguageTable(id, name, code) values (164, 'Turkish', 'tur');
insert into LanguageTable(id, name, code) values (165, 'Tsonga', 'tso');
insert into LanguageTable(id, name, code) values (166, 'Tatar', 'tat');
insert into LanguageTable(id, name, code) values (167, 'Twi', 'twi');
insert into LanguageTable(id, name, code) values (168, 'Tahitian', 'tah');
insert into LanguageTable(id, name, code) values (169, 'Uyghur', 'uig');
insert into LanguageTable(id, name, code) values (170, 'Ukrainian', 'ukr');
insert into LanguageTable(id, name, code) values (171, 'Urdu', 'urd');
insert into LanguageTable(id, name, code) values (172, 'Uzbek', 'uzb');
insert into LanguageTable(id, name, code) values (173, 'Venda', 'ven');
insert into LanguageTable(id, name, code) values (174, 'Vietnamese', 'vie');
insert into LanguageTable(id, name, code) values (175, 'Volapük', 'vol');
insert into LanguageTable(id, name, code) values (176, 'Walloon', 'wln');
insert into LanguageTable(id, name, code) values (177, 'Welsh', 'wel');
insert into LanguageTable(id, name, code) values (178, 'Wolof', 'wol');
insert into LanguageTable(id, name, code) values (179, 'Western Frisian', 'fry');
insert into LanguageTable(id, name, code) values (180, 'Xhosa', 'xho');
insert into LanguageTable(id, name, code) values (181, 'Yiddish', 'yid');
insert into LanguageTable(id, name, code) values (182, 'Yoruba', 'yor');
insert into LanguageTable(id, name, code) values (183, 'Zhuang', 'zha');
insert into LanguageTable(id, name, code) values (184, 'Zulu', 'zul');


-- LanguageKeyCodes

insert into LanguageKeyCodes(lang, code) values (1, 'et');
insert into LanguageKeyCodes(lang, code) values (2, 'ru');
insert into LanguageKeyCodes(lang, code) values (3, 'en');

insert into LanguageKeyCodes(lang, code) values (4, 'ab');
insert into LanguageKeyCodes(lang, code) values (5, 'aa');
insert into LanguageKeyCodes(lang, code) values (6, 'af');
insert into LanguageKeyCodes(lang, code) values (7, 'ak');
insert into LanguageKeyCodes(lang, code) values (8, 'sq');
insert into LanguageKeyCodes(lang, code) values (9, 'am');
insert into LanguageKeyCodes(lang, code) values (10, 'ar');
insert into LanguageKeyCodes(lang, code) values (11, 'an');
insert into LanguageKeyCodes(lang, code) values (12, 'hy');
insert into LanguageKeyCodes(lang, code) values (13, 'as');
insert into LanguageKeyCodes(lang, code) values (14, 'av');
insert into LanguageKeyCodes(lang, code) values (15, 'ae');
insert into LanguageKeyCodes(lang, code) values (16, 'ay');
insert into LanguageKeyCodes(lang, code) values (17, 'az');
insert into LanguageKeyCodes(lang, code) values (18, 'bm');
insert into LanguageKeyCodes(lang, code) values (19, 'ba');
insert into LanguageKeyCodes(lang, code) values (20, 'eu');
insert into LanguageKeyCodes(lang, code) values (21, 'be');
insert into LanguageKeyCodes(lang, code) values (22, 'bn');
insert into LanguageKeyCodes(lang, code) values (23, 'bh');
insert into LanguageKeyCodes(lang, code) values (24, 'bi');
insert into LanguageKeyCodes(lang, code) values (25, 'bs');
insert into LanguageKeyCodes(lang, code) values (26, 'br');
insert into LanguageKeyCodes(lang, code) values (27, 'bg');
insert into LanguageKeyCodes(lang, code) values (28, 'my');
insert into LanguageKeyCodes(lang, code) values (29, 'ca');
insert into LanguageKeyCodes(lang, code) values (30, 'ch');
insert into LanguageKeyCodes(lang, code) values (31, 'ce');
insert into LanguageKeyCodes(lang, code) values (32, 'ny');
insert into LanguageKeyCodes(lang, code) values (33, 'zh');
insert into LanguageKeyCodes(lang, code) values (34, 'cv');
insert into LanguageKeyCodes(lang, code) values (35, 'kw');
insert into LanguageKeyCodes(lang, code) values (36, 'co');
insert into LanguageKeyCodes(lang, code) values (37, 'cr');
insert into LanguageKeyCodes(lang, code) values (38, 'hr');
insert into LanguageKeyCodes(lang, code) values (39, 'cs');
insert into LanguageKeyCodes(lang, code) values (40, 'da');
insert into LanguageKeyCodes(lang, code) values (41, 'dv');
insert into LanguageKeyCodes(lang, code) values (42, 'nl');
insert into LanguageKeyCodes(lang, code) values (43, 'dz');
insert into LanguageKeyCodes(lang, code) values (44, 'eo');
insert into LanguageKeyCodes(lang, code) values (45, 'ee');
insert into LanguageKeyCodes(lang, code) values (46, 'fo');
insert into LanguageKeyCodes(lang, code) values (47, 'fj');
insert into LanguageKeyCodes(lang, code) values (48, 'fi');
insert into LanguageKeyCodes(lang, code) values (49, 'fr');
insert into LanguageKeyCodes(lang, code) values (50, 'ff');
insert into LanguageKeyCodes(lang, code) values (51, 'gl');
insert into LanguageKeyCodes(lang, code) values (52, 'ka');
insert into LanguageKeyCodes(lang, code) values (53, 'de');
insert into LanguageKeyCodes(lang, code) values (54, 'el');
insert into LanguageKeyCodes(lang, code) values (55, 'gn');
insert into LanguageKeyCodes(lang, code) values (56, 'gu');
insert into LanguageKeyCodes(lang, code) values (57, 'ht');
insert into LanguageKeyCodes(lang, code) values (58, 'ha');
insert into LanguageKeyCodes(lang, code) values (59, 'he');
insert into LanguageKeyCodes(lang, code) values (60, 'hz');
insert into LanguageKeyCodes(lang, code) values (61, 'hi');
insert into LanguageKeyCodes(lang, code) values (62, 'ho');
insert into LanguageKeyCodes(lang, code) values (63, 'hu');
insert into LanguageKeyCodes(lang, code) values (64, 'ia');
insert into LanguageKeyCodes(lang, code) values (65, 'id');
insert into LanguageKeyCodes(lang, code) values (66, 'ie');
insert into LanguageKeyCodes(lang, code) values (67, 'ga');
insert into LanguageKeyCodes(lang, code) values (68, 'ig');
insert into LanguageKeyCodes(lang, code) values (69, 'ik');
insert into LanguageKeyCodes(lang, code) values (70, 'io');
insert into LanguageKeyCodes(lang, code) values (71, 'is');
insert into LanguageKeyCodes(lang, code) values (72, 'it');
insert into LanguageKeyCodes(lang, code) values (73, 'iu');
insert into LanguageKeyCodes(lang, code) values (74, 'ja');
insert into LanguageKeyCodes(lang, code) values (75, 'jv');
insert into LanguageKeyCodes(lang, code) values (76, 'kl');
insert into LanguageKeyCodes(lang, code) values (77, 'kn');
insert into LanguageKeyCodes(lang, code) values (78, 'kr');
insert into LanguageKeyCodes(lang, code) values (79, 'ks');
insert into LanguageKeyCodes(lang, code) values (80, 'kk');
insert into LanguageKeyCodes(lang, code) values (81, 'km');
insert into LanguageKeyCodes(lang, code) values (82, 'ki');
insert into LanguageKeyCodes(lang, code) values (83, 'rw');
insert into LanguageKeyCodes(lang, code) values (84, 'ky');
insert into LanguageKeyCodes(lang, code) values (85, 'kv');
insert into LanguageKeyCodes(lang, code) values (86, 'kg');
insert into LanguageKeyCodes(lang, code) values (87, 'ko');
insert into LanguageKeyCodes(lang, code) values (88, 'ku');
insert into LanguageKeyCodes(lang, code) values (89, 'kj');
insert into LanguageKeyCodes(lang, code) values (90, 'la');
insert into LanguageKeyCodes(lang, code) values (91, 'lb');
insert into LanguageKeyCodes(lang, code) values (92, 'lg');
insert into LanguageKeyCodes(lang, code) values (93, 'li');
insert into LanguageKeyCodes(lang, code) values (94, 'ln');
insert into LanguageKeyCodes(lang, code) values (95, 'lo');
insert into LanguageKeyCodes(lang, code) values (96, 'lt');
insert into LanguageKeyCodes(lang, code) values (97, 'lu');
insert into LanguageKeyCodes(lang, code) values (98, 'lv');
insert into LanguageKeyCodes(lang, code) values (99, 'gv');
insert into LanguageKeyCodes(lang, code) values (100, 'mk');
insert into LanguageKeyCodes(lang, code) values (101, 'mg');
insert into LanguageKeyCodes(lang, code) values (102, 'ms');
insert into LanguageKeyCodes(lang, code) values (103, 'ml');
insert into LanguageKeyCodes(lang, code) values (104, 'mt');
insert into LanguageKeyCodes(lang, code) values (105, 'mi');
insert into LanguageKeyCodes(lang, code) values (106, 'mr');
insert into LanguageKeyCodes(lang, code) values (107, 'mh');
insert into LanguageKeyCodes(lang, code) values (108, 'mn');
insert into LanguageKeyCodes(lang, code) values (109, 'na');
insert into LanguageKeyCodes(lang, code) values (110, 'nv');
insert into LanguageKeyCodes(lang, code) values (111, 'nd');
insert into LanguageKeyCodes(lang, code) values (112, 'ne');
insert into LanguageKeyCodes(lang, code) values (113, 'ng');
insert into LanguageKeyCodes(lang, code) values (114, 'nb');
insert into LanguageKeyCodes(lang, code) values (115, 'nn');
insert into LanguageKeyCodes(lang, code) values (116, 'no');
insert into LanguageKeyCodes(lang, code) values (117, 'ii');
insert into LanguageKeyCodes(lang, code) values (118, 'nr');
insert into LanguageKeyCodes(lang, code) values (119, 'oc');
insert into LanguageKeyCodes(lang, code) values (120, 'oj');
insert into LanguageKeyCodes(lang, code) values (121, 'cu');
insert into LanguageKeyCodes(lang, code) values (122, 'om');
insert into LanguageKeyCodes(lang, code) values (123, 'or');
insert into LanguageKeyCodes(lang, code) values (124, 'os');
insert into LanguageKeyCodes(lang, code) values (125, 'pa');
insert into LanguageKeyCodes(lang, code) values (126, 'pi');
insert into LanguageKeyCodes(lang, code) values (127, 'fa');
insert into LanguageKeyCodes(lang, code) values (128, 'pl');
insert into LanguageKeyCodes(lang, code) values (129, 'ps');
insert into LanguageKeyCodes(lang, code) values (130, 'pt');
insert into LanguageKeyCodes(lang, code) values (131, 'qu');
insert into LanguageKeyCodes(lang, code) values (132, 'rm');
insert into LanguageKeyCodes(lang, code) values (133, 'rn');
insert into LanguageKeyCodes(lang, code) values (134, 'ro');
insert into LanguageKeyCodes(lang, code) values (135, 'sa');
insert into LanguageKeyCodes(lang, code) values (136, 'sc');
insert into LanguageKeyCodes(lang, code) values (137, 'sd');
insert into LanguageKeyCodes(lang, code) values (138, 'se');
insert into LanguageKeyCodes(lang, code) values (139, 'sm');
insert into LanguageKeyCodes(lang, code) values (140, 'sg');
insert into LanguageKeyCodes(lang, code) values (141, 'sr');
insert into LanguageKeyCodes(lang, code) values (142, 'gd');
insert into LanguageKeyCodes(lang, code) values (143, 'sn');
insert into LanguageKeyCodes(lang, code) values (144, 'si');
insert into LanguageKeyCodes(lang, code) values (145, 'sk');
insert into LanguageKeyCodes(lang, code) values (146, 'sl');
insert into LanguageKeyCodes(lang, code) values (147, 'so');
insert into LanguageKeyCodes(lang, code) values (148, 'st');
insert into LanguageKeyCodes(lang, code) values (149, 'es');
insert into LanguageKeyCodes(lang, code) values (150, 'su');
insert into LanguageKeyCodes(lang, code) values (151, 'sw');
insert into LanguageKeyCodes(lang, code) values (152, 'ss');
insert into LanguageKeyCodes(lang, code) values (153, 'sv');
insert into LanguageKeyCodes(lang, code) values (154, 'ta');
insert into LanguageKeyCodes(lang, code) values (155, 'te');
insert into LanguageKeyCodes(lang, code) values (156, 'tg');
insert into LanguageKeyCodes(lang, code) values (157, 'th');
insert into LanguageKeyCodes(lang, code) values (158, 'ti');
insert into LanguageKeyCodes(lang, code) values (159, 'bo');
insert into LanguageKeyCodes(lang, code) values (160, 'tk');
insert into LanguageKeyCodes(lang, code) values (161, 'tl');
insert into LanguageKeyCodes(lang, code) values (162, 'tn');
insert into LanguageKeyCodes(lang, code) values (163, 'to');
insert into LanguageKeyCodes(lang, code) values (164, 'tr');
insert into LanguageKeyCodes(lang, code) values (165, 'ts');
insert into LanguageKeyCodes(lang, code) values (166, 'tt');
insert into LanguageKeyCodes(lang, code) values (167, 'tw');
insert into LanguageKeyCodes(lang, code) values (168, 'ty');
insert into LanguageKeyCodes(lang, code) values (169, 'ug');
insert into LanguageKeyCodes(lang, code) values (170, 'uk');
insert into LanguageKeyCodes(lang, code) values (171, 'ur');
insert into LanguageKeyCodes(lang, code) values (172, 'uz');
insert into LanguageKeyCodes(lang, code) values (173, 've');
insert into LanguageKeyCodes(lang, code) values (174, 'vi');
insert into LanguageKeyCodes(lang, code) values (175, 'vo');
insert into LanguageKeyCodes(lang, code) values (176, 'wa');
insert into LanguageKeyCodes(lang, code) values (177, 'cy');
insert into LanguageKeyCodes(lang, code) values (178, 'wo');
insert into LanguageKeyCodes(lang, code) values (179, 'fy');
insert into LanguageKeyCodes(lang, code) values (180, 'xh');
insert into LanguageKeyCodes(lang, code) values (181, 'yi');
insert into LanguageKeyCodes(lang, code) values (182, 'yo');
insert into LanguageKeyCodes(lang, code) values (183, 'za');
insert into LanguageKeyCodes(lang, code) values (184, 'zu');

/* Manually added keycodes */
insert into LanguageKeyCodes(lang, code) values (130, 'pt-br');

