package ee.netgroup.hm.helpers;

import ee.netgroup.hm.tests.SeleniumUser;

public class Arrays extends SeleniumUser{
	
	public static String[] portfolioTitlesArray = {"Language Arts", "Mathematics", "Science", "Health", "Handwriting", "Personal Organization", 
			"Physical Education (P.E.)", "Social Skills", "Career Planning", "Instrumental Music and specific instrument", "Movement or Eurythmy", 
			"Handwork or handcrafts", "Life Lab or gardening", "Dramatics", "Art", "Greek and Roman History", "Martial Arts", "Ice Skating",
			"Music", "Dance", "Personal Finance and Investing", "Aerobics", "Yoga", "Figure skating", "Spanish or other foreign language", "Leadership", 
			"Special Education Day Class", "Driver�s Education", "Resource Program", "Statistics", "World Religions", "Cycling", "Bowling", "Keyboarding", 
			"Computer Repair", "Speech", "Adaptive P.E.", "Trigonometry", "Economics", "Physical Fitness", "Computer Graphics", "Occupational Therapy", 
			"Astronomy", "Political Science", "Digital Arts", "Photoshop", "Programming", "Reading", "Meteorology", "Equine Science", "Gymnastics",
			"Outdoor Survival Skills", "Speech and Debate", "Animal Science", "Ecology", "Golf", "Rock Climbing", "Desktop Publishing", "English", 
			"Oceanography", "Veterinary Science", "Environmental Science", "Web Design", "Basic Math", "Botany", "Geology", "Forensic Science", 
			"Critical Thinking", "Rhetoric", "Pre-algebra", "Physics", "Chemistry", "Organic Chemistry", "Biology", "Zoology", "Basic Yard Care",
			"Financial Management", "Consumer Math", "Small Engine Mechanics", "Auto Mechanics", "Marine Biology", "Algebra", "Geometry", "Gardening", 
			"Japanese", "German", "Latin", "Culinary Arts", "Life Science", "Earth Science", "Food Science", "Anthropology", "Home Management", 
			"Physical Science", "Computer Aided Design (Digital Media)", "Photography", "Home Organization", "Social Studies", "Performing Arts", 
			"Theatre Arts", "Genealogy", "Geography", "Ancient Civilizations", "Leather Working", "Philosophy", "Logic", "Medieval and Renaissance", 
			"Sports", "Sculpture", "Ceramics", "Pottery", "Music History", "Music Theory", "Music Fundamentals", "U.S. History and Government",
			"French / Spanish / Latin", "Photojournalism", "Yearbook", "Art History", "Drawing", "Painting", "Computer Science or Lab", "Home Economics", 
			"Instrumental Music", "Band", "Choir", "Drama", "Physical Education", "Woodshop", "Metal Shop", "Business Technology", "English as second language",
			"World Literature", "Ancient Literature", "Medieval Literature", "Renaissance Literature", "Modern Literature", "British Literature", 
			"American Literature", "Composition", "Creative Writing", "Poetry", "Grammar", "Vocabulary", "Debate", "Journalism", "Publishing Skills"};
	
	public static String[] descriptionArray = {"The road to feminism is simple: it’s about awareness.",
			"You know, fear is a funny thing on an investigation. There seems to be a difference between imagination running away from you, what you call “true fear”, and what I think could be the change in the environment from a spirit presence.",
			"Her stories touch a raw nerve every woman will resonate with—about how hard it is for us to be taken seriously.",
			"You learn to be inspired by challenges, not afraid of them.", 
			"When you get an adrenaline rush from cleaning your apartment.",
			"The greatest gift is getting to be yourself day in and day out.", "More information within.",
			"What matters now is who you are in this moment and what you’re doing right now.",
			"Whenever I follow this rule, my life gets exponentially better very quickly.",
			"Remind yourself that Churchill lead a country while battling depression.",
			"A record number of murders have occurred in Anchorage this year, with over half of them unsolved.",
			"When all else fails, just breathe. You are surviving. And sometimes, that is all you can do. And that’s ok.",
			"In a Romeo and Juliet-esque situation, there was some kind of apparent feud between the family of the bride and groom.",
			"When you have a lot to juggle, the most valuable thing in the world is energy.",
			"Dreams are an aspiration of who we truly are. ", "It’s the least I can do. Keep the conversation going.",
			"Perfection, the ultimate goal. We all want it. We chase it. And we’re disappointed when we don’t get there. ",
			"This is not a political post. Or a revolutionary one. Or a socialist one. Or a whatever. It’s just facts. ",
			"I am Bipolar, and I am capable – but this does not mean I want to be Bipolar. My disorder isn’t a means to an end, a method of manipulation, or a way to demand the attention of those around me.",
			"School starts tomorrow, which means it’s time to say goodbye",
			"The quality of your rest. This is the main determinant of your long-term productivity and efficiency of your work. Good rest is a concrete foundation and prerequisite for exceptional performance.",
			"Here’s an unpopular truth: people who post less are actually those who lead amazing lives. And guess what? They don’t need to prove it.",
			"Entry Level means years of experience. When you read the title “entry level” for a position, you automatically assume that this may be an option for you.",
			"Music note: You know how to play at least one instrument, and you always have your earbuds in.",
			"Nothing is worth it if you aren’t happy", "I woke up to the sound of knocking on glass. I assumed it was the window, but as I checked, I heard it again, from the mirror.",
			"I think you should stop worrying about reasons why it won’t work and only focus on the reasons why it will.",
			"New iPhones. Each new model is basically the same as the previous one", "Delete your time-wasting apps. The ones you always get stuck playing when you should be working.",
			"New York City isn’t a magical place where you instantaneously find yourself.",
			"Class of 2020, no matter where you are, stay focused and enjoy every moment. This isn’t just a phase. It’s your future, your dreams and your life.",
			"How can you be sure that your red isn’t someone else’s blue?",
			"There are plenty of fish in the sea, and as long as you keep focusing on you and your own growth, the right ones will come to you.",
			"It’s okay to be scared. Being scared means we’re concerned enough to realize that there might be something wrong, that there might be something worth fixing.",
			"Most people are not strategic. They are reactive."};
	
	public static String[] materialTitlesArray = {"ALTERNATE UNIVERSE", "ALIEN RACE OF COLORED WAX", "TRENDING PURPLE", "AFRICAN CONGLOMERATE", "AFRAID OF THE FUTURE", 
			"AGE OF AQUARIUS", "AGORAPHOBIA", "ABANDON IN PLACE", "ABSOLUTE PANIC", "ACCORDING TO HINDU MYTH", "AKEELAH AND THE BEE", "ALIENS ARE COMING", 
			"ALL ABOUT THE OWLS", "ALL NIGHT LONG", "ALL THINGS CONSIDERED", "THE ALLEGORY OF THE TRILOBITE", "ALTERNATIVE ENERGY SOURCES", "ALWAYS DELICIOUS",
			"AN APPLE A DAY", "ANAGRAMS", "ANCIENT CHINESE SECRET", "ANTI STAR TREK", "APOLLO 1", "ARCHITECTURAL STRUCTURE", "BACK IN TIME", "BALLROOM DANCING", 
			"BAPHOMET", "BE LIKE NEWTON", "BERSERKERS", "BEYOND THE MECHANICAL UNIVERSE", "BOILING WATER", "CAN-DO ATTITUDE", "CANADIAN EDEN", "CATALYST", 
			"CIVIL PROTECTION", "COLD SALVATION", "COMPARE AND CONTRAST", "COSMIC RAYS", "COSTUMES FROM CATS", "THE CRISIS ON INFINITE EARTHS", "DAYLIGHT SAVINGS TIME", 
			"DEEP IMPACT", "DEEP SPACE AMBASSADOR", "DEFINITELY YES", "DEFORMITY", "DEFYING PHYSICAL LAW", "DIAGONALIZATION", "DNA DOESN'T LIE", "DNA EVIDENCE", 
			"DRAWING THE LINE", "DREAM BLENDER", "EGYPTIAN STORK", "ENOUGH WITH THE ZOMBIES", "ERGONOMIC KEYBOARD", "EVERY SNOWFLAKE IS DIFFERENT", "FALLOUT SHELTER", 
			"FREEDOM ISN'T FREE", "FROM THE MIND OF MINOLTA", "FROSTY THE SNOWMAN", "GENDER ROLES", "GENERIC NAMES", "GLOBAL GEOPOLITICS IN THE THERMONUCLEAR AGE",
			"GLOBAL WARMING", "GRAPES OF WRATH", "GREAT THINGS ABOUT BEING", "HEAVY METAL POISONING", "HINDU LABYRINTH", "HOLIDAY DECORATIONS", "HOME INVASION", 
			"IDEAS WORTH", "THE IMPACT ON JUPITER", "IMAGINE THE POSSIBILITIES", "INSIDE MACINTOSH", "INTELLIGENT DESIGN", "JIGSAW PUZZLE", "LIKE A FOUNTAIN",
			"LILITH FAIR", "THE LION IN WINTER", "LOCKED BOX", "LOCKER ROOM", "LOGIC GATES", "LONDON KEYS", "LORD ALIVE", "LORD OF THE RINGS GOES COMMERCIAL", 
			"LUNAR ECLIPSE", "LYING ABOUT AT LEAST ONE OF THESE THINGS", "MAGNETIC NORTH", "MAKE IT END", "MAN IN THE MOON", "MASS EFFECT CONCLUSION", "MATH IS HARD", 
			"MAY DAY", "A MAZE OF TWISTY LITTLE PASSAGES", "MAZE TIME","MEDITATION RETREAT", "MENTAL HEALTH BREAK", "MERCURY ORBITZ", "MILLION MAN MARCH", 
			"MISSED HALLOWEEN", "MORE THAN YOU COULD POSSIBLY BELIEVE", "MOST DISTURBING UNIVERSE", "MOUNTAIN DEW PYRAMID", "THE NASA UNICORN", "NATURE'S GOLD", 
			"NEED TO KNOW BASIS","NEPTUNE SPEAKS", "NEURODIVERSE CULTURE", "A NEW BARYON HAS BEEN DISCOVERED", "NIGHT LANDING", "NOT A FIGHTER", "NUCLEAR SECRETS", 
			"OCEAN SOUNDS", "OLD SCHOOL", "ONE OF THESE DAYS", "OPENING STATEMENT", "OPEN WINDOWS", "OPTICAL ILLUSION", "OUT OF THE CELLAR", "PART OF THE SOLUTION",
			"PERSONAL TIME MACHINE", "PHONE BOOTH", "PLUTO SYMBOL", "POLAR VORTEX", "POSSIBLE RADIATION HAZARD", "PROTESTER CHANT", "PROTESTING THE WAR", 
			"RADIO TELESCOPE", "THE RAINDROP REVOLUTION", "READING RAINBOW", "RELIGIOUS TOLERANCE", "RIGHT THING, WRONG NAME", "ROOT CAUSES", "SAMURAI'S PRIDE", 
			"SCIENTIFIC METHOD", "SEARCHING NEAR AND FAR", "SELF-INVOKING GODWIN'S LAW", "SEMANTIC ARGUMENTS", "SET IT FREE", "SEWING MACHINE", "SKEPTICAL ACTIVIST", 
			"SOCIAL NETWORKS", "STAIRWAY TO HEAVEN", "STAY GREEN", "STILL LIFE", "STOPPING TRAFFIC", "TACTICAL INTERVENTION", "TEMPORAL PRIME DIRECTIVE",
			"TEST DRIVE", "THIRD ROCK FROM THE SUN", "THOSE BEES", "TIGER WOODS","TIME ZONES", "TO THE LIONS", "TORTURE DEVICE", "TRUE FORM", "UNBELIEVABLE TOOL", 
			"VISITING JAPAN", "WE ARE COLOR BLIND", "WE MUST BELIEVE IN MAGIC", "WHAT BUGS IS HOLDING", "WHAT TO DO IN THE EVENT OF A BIOLOGICAL ATTACK",
			"WILD THING", "WORDS ARE HARD", "WRATH OF THE KING", "WRONG DIRECTION", "YODA REMINISCES"};
	
	public static String[] firstNamesArray = {"Amina", "Alfred", "Alma", "Almond", "Alvin", "Amanda", "Anastasia", "Ash", "Ashley", "Audrey", "Bailey", "Ballard", 
			"Barbara", "Barclay", "Bartley", "Beatrice", "Beverly", "Aisha", "Akela", "Blossom", "Boston", "Bradley", "Brandon", "Byron", "Camellia", "Camilla", 
			"Cannon", "Cassandra", "Abbigail", "Adelle", "Agatha", "Aliah", "Alison", "Alix", "Anna", "Belynda", "Djamila", "Beth", "Bridget", "Briony", "Brianna", 
			"Cara", "Cedar'", "Charis", "Charleen", "Chloe", "Chris", "Cilla", "Clara", "Cornelia", "Cressida", "Dakota", "Danielle", "Daphne", "Darian", "Deborah",
			"Denice", "Gamila", "Diana", "Dina", "Donna", "Dorean", "Ebony", "Eda", "Eden", "Edith", "Eireen", "Eleanor", "Hala", "Elba", "Hana", "Elfrida", "Ella", 
			"Eliza", "Elly", "Elmira", "Eloise", "Elvina", "Emelie", "Emerald", "Emmy", "Erica", "Erin", "Eve", "Fay", "Ismat", "Flor", "Frea", "Jamila", "Gabi", 
			"Gabriella", "Gaila", "Geena", "Gemma", "Gwendolen", "Harper", "Haven", "Hazel", "Kismat", "Laila", "Helga", "Lamia", "Latifa", "Ida", "Layla", "Leena", 
			"Lina", "Idelle", "Ilean", "India", "Malika", "Irma", "Irmagard", "Irene", "Iris", "Irma", "Isabel", "Isadora", "Isolde", "Iva", "Ivy", "Jade", "Jane", 
			"Jasmin", "Jemma", "Jennifer", "Jinny", "Nora", "Julia", "June", "Karly", "Kelly", "Kenzie", "Keisha", "Kiara", "Kim", "Ranya", "Kimberly", "Klara", 
			"Ladonna", "Lacy", "Lana", "Lara", "Laura", "Laureen", "Laura", "Lea", "Leanna", "Lee", "Lenora", "Leona", "Lilian", "Lilith", "Linda", "Sameera", 
			"Lindsay", "Lora", "Loreen", "Sana", "Lyda", "Mabella", "Lyssa", "Madalyn", "Maddie", "Madge", "Shakira", "Maddison", "Mae", "Marcie", "Marian", "Tahira", 
			"Mariel", "Marta", "Thalulah", "Melicent", "Thamina", "Meredith", "Milla", "Mira", "Miriam", "Mona", "Mya", "Nadia", "Natalie", "Nelle", "Nicole", "Yasmin",
			"Nina", "Noah", "Olive", "Ophelia", "Paula", "Retha", "Rhonda", "Zara", "Riona", "Rosa", "Rosheen", "Roxane", "Amal", "Amber", "Rubie", "Sabina", "Elham", 
			"Sabrina", "Salome", "Iesha", "Samantha", "Ishtar", "Saranna", "Lila", "Scarlet", "Selina", "Shania", "Shannon", "Oma", "Sheree", "Sofia", "Rihanna", 
			"Saffron", "Stepfanie", "Sybilla", "Tara", "Thea", "Tiana", "Tiara", "Trish", "Uma", "Valarie", "Vanessa", "Vianne", "Virginia", "Yolanda", "Zoe", "Aaron", 
			"Adam", "Aleena", "Alika", "Alma", "Alvina", "Adrian", "Alban", "Alen", "Amelia", "Alex", "Alfie", "Allan", "Allister", "Aston", "Barret", "Bart", "Bennet", 
			"Bradley", "Brennan", "Brian", "Anousha", "Brooke", "Bruno", "Ariana", "Aribah", "Cedric", "Chad", "Chandler", "Clifton", "Arya", "Colin", "Dallas", "Dan", 
			"Dalton", "Daniel", "Dave", "David", "Dean", "Deon", "Earl", "Eamon", "Eber", "Edwin", "Elbie", "Elden", "Eliah", "Eliot", "Chandi", "Elvin", "Emil", 
			"Emmet", "Esmond", "Evan", "Fabian", "Fred", "Gabriel", "Gail", "Gareth", "George", "Gerry", "Eliza", "Gilbert", "Glen", "Gordon", "Ermina", "Graham", 
			"Griffin", "Hank", "Hardy", "Harry", "Harvey", "Hartley", "Haward", "Hecktor", "Herman", "Holden", "Humbert", "Imanuel", "Ingram", "Isador", "Jack", 
			"James", "Jared", "Jason", "Jeff", "Joel", "John", "Joseph", "Julian", "Kay", "Keith", "Kendall", "Kenneth", "Kent", "Kevin", "Kian", "Kimberley", 
			"Lambart", "Lanford", "Lark", "Larry", "Lenard", "Lennie", "Leon", "Leroi", "Lester", "Lewis", "Lionel", "Lucas", "Malone", "Mark", "Marlon", "Marvin", 
			"Mason", "Matthias", "Max", "Mayson", "Melvin", "Merlin", "Milton", "Monty", "Morrissey", "Murphy", "Nash", "Ned", "Neil", "Neo", "Nevil", "Nick", "Noel", 
			"Nolan", "Norman", "Norton", "Oberon", "Oliver", "Patrick", "Paul", "Percy", "Peter", "Maysa", "Phil", "Ralph", "Randy", "Raymond", "Redd", "Mishel", 
			"Richard", "Mona", "Rocky", "Rolland", "Roman", "Ronald", "Ross", "Nadia", "Ryan", "Samuel", "Sander", "Sean", "Simon", "Nargis", "Stan", "Stephen", 
			"Steve", "Taylor", "Thomas", "Tim", "Tommie", "Travis", "Troy", "Tyron", "Vergil", "Victor", "Vincent", "Walter", "William", "Wilmot",  "Sonia"};
	
	public static String[] SurnamesArray = {"Smith", "Hall", "Stewart", "Johnson", "Allen", "Bennett", "Morris", "Wood", "Brown", "King", "Ross", "Davis", "Miller", 
			"Morgan", "Coleman", "Hill", "Bell", "Moore", "Murphy", "Taylor", "Green", "Bailey", "Powell", "Adams", "Long", "River", "Baker", "White", "Nelson", 
			"Carter", "Howard", "Martin", "Mitchell", "Simmons", "Gray", "Foster", "Lewis", "Collins", "Hayes", "Kelly", "Evans", "Ryan", "Graham", "Gibbs", "Hoffman", 
			"Shelton", "Griffin", "York", "Berry", "Blair", "Lyon", "Russo", "Finch", "Maxwell", "Fanning", "Clifford", "Black", "Underwood", "Pearson", "Craig", 
			"Lane", "Norris", "Donnelly", "May", "Finn", "Dalton", "Garrett", "Newman", "Chandler", "Melton", "Baxter", "Hill", "Carter", "Leblanc", "Larsen", "Snow", 
			"Lloyd", "Day", "Lamont", "Flores", "Zion", "Woody", "Wolf", "Winston", "Wilton", "Topher", "Trafford", "Vortigern", "Walker", "Wayne", "Weston", "Shannon",
			"Shelby", "Shelton", "Sherwood", "Sky", "Storm", "Taffy", "Tyrrell", "Thomas", "Ray", "Rigby", "Ronald", "Ross", "Ruby"};
	
	public static String[] tagsArray = {"life", "school", "followback", "art", "fashion", "sky", "beauty", "noir", "ink", "design", "craft", "beatles", "antique", 
			"monoart", "architect", "linedesign", "style", "classical", "vintage", "vector", "focus", "exposure", "usa", "sport", "brand", "fancy", "france", "bag", 
			"free", "musthave", "look", "foundation", "lookbook", "december", "every", "can", "people", "movingforward", "decoration", "cold", "morning", "sleepy", 
			"plot", "story", "readinglist", "imagine", "trip", "festival", "instrument", "musicnotes", "key", "rock", "mozart", "green", "summer", "reflection",
			"sand", "seaside", "landscape", "bloom", "mountains", "ocean", "skyfall", "cloud9", "outside", "worldwide", "winter", "forest", "fall", "foliage", "orange",
			"crowd", "team", "workout", "yoga", "geometry", "composition", "urban", "grammar", "home", "music", "done", "friends", "reality", "algebra", "workshop", 
			"more", "unknown", "future", "contest", "famous", "addict", "memories", "road", "motivation", "plants", "textbook", "abstract", "acorn", "acronym", 
			"ad lib", "adept", "adobe", "aeon", "aerostat", "africa", "agenda", "agile", "aircraft", "alpha"};

}
