SET foreign_key_checks = 0;

insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_JALAKÄIJA_OHUTU_LIIKLEMINE', 'Jalakäija ohutu liiklemine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_JALAKÄIJA_OHUTU_LIIKLEMINE', 'Pedestrian traffic safety');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_IGAPÄEVAELU_ÕPPIMINE_TÖÖ', 'Igapäevaelu õppimine töö');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_IGAPÄEVAELU_ÕPPIMINE_TÖÖ','Everydaylife learning work');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_GLOBAALSED_KESKKONNAPROBLEEMID_JA_NENDE_MÕJU_ERI_REGIOONIDELE', 'Globaalsed keskkonnaprobleemid ja nende mõju eri regiooonidele');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_GLOBAALSED_KESKKONNAPROBLEEMID_JA_NENDE_MÕJU_ERI_REGIOONIDELE','Global environment problems and their impact to different regions');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_GRAMMATIKA', 'Grammatika');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_GRAMMATIKA', 'Grammar');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_KAARDI_MATEMAATILINE_ALUS', 'Kaardi matemaatiline alus');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_KAARDI_MATEMAATILINE_ALUS','Mathematical basis of chart');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_LUGEMISE_EESMÄRGISTAMINE', 'Lugemise eesmärgistamine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_LUGEMISE_EESMÄRGISTAMINE', 'Reading targeting');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_PEREKOND_JA_SUGULASED', 'Perekond ja sugulased');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_PEREKOND_JA_SUGULASED', 'Family and relatives');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_KEHALISE_KASVATUSE_ALASED_TEADMISED', 'Kehalise kasvatuse alased teadmised');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_KEHALISE_KASVATUSE_ALASED_TEADMISED', 'Knowledge of physical education');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_MUUTUSED_LOODUSES', 'Muutused looduses');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_MUUTUSED_LOODUSES','Changes in nature');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_HARIDUS_JA_TÖÖ', 'Haridus ja töö');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_HARIDUS_JA_TÖÖ', 'Education and work');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_LOETUD_TEOSE_ÜHISARUTELU', 'Loetud teose ühisarutelu');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_LOETUD_TEOSE_ÜHISARUTELU','Discussion of read book');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_ESITAMISE_EESMÄRGISTAMINE', 'Esitamise eesmärgistamine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_ESITAMISE_EESMÄRGISTAMINE', 'Submission targeting');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_EHITISED', 'Ehitised');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_EHITISED','Buildings');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_KODUKOHT_EESTI', 'Kodukoht Eesti');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_KODUKOHT_EESTI','Homeland Estonia');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_EESTI_RAHVA_TÄHTPÄEVAD', 'Eesti rahva tähtpäevad');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_EESTI_RAHVA_TÄHTPÄEVAD','Estonian anniversaries');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_TRANSPORDIVAHENDID', 'Transpordivahendid');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_TRANSPORDIVAHENDID', 'Means of transport');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_PIIBLILOOD', 'Piiblilood');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_PIIBLILOOD', 'Bible stories');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_KUULAMINE', 'Kuulamine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_KUULAMINE',  'Listening');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_SEIKLUSJUTT_JA_AJALOOLINE_JUTUSTUS', 'Seiklusjutt ja ajalooline jutustus');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_SEIKLUSJUTT_JA_AJALOOLINE_JUTUSTUS', 'Adventure and historical story ');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_RAHVASTIKUPROTSESSIDE_MÕJU_ÜHISKONNA_ARENGULE', 'Rahvastikuprotsesside mõju ühiskonna arengule');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_RAHVASTIKUPROTSESSIDE_MÕJU_ÜHISKONNA_ARENGULE','Impact of demographic processes on social development');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_OHUTUS', 'Ohutus');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_OHUTUS', 'Safety');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_LIIKUMISMÄNGUD', 'Liiklusmängud');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_LIIKUMISMÄNGUD','Traffic games');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_LUGEMISTEHNIKA', 'Lugemistehnika');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_LUGEMISTEHNIKA', 'Reading technique');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_TANTS_JA_RÜTMIKA', 'Tants ja rütmika');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_TANTS_JA_RÜTMIKA', 'Dance and rhythm');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_KUJUNDLIK_MÕTLEMINE', 'Kujundlik mõtlemine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_KUJUNDLIK_MÕTLEMINE','Abstract thinking');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_KERGETÖÖSTUS', 'Kergetööstus');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_KERGETÖÖSTUS', 'Light industry');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_INIMKEHA', 'Inimkeha');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_INIMKEHA','Human body');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_JÄÄTMED', 'Jäätmed');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_JÄÄTMED', 'Wastes');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_EPITEET_JA_VÕRDLUS', 'Epiteet ja võrdlus');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_EPITEET_JA_VÕRDLUS','Epithet and comparison');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_ERINEVAD_MEEDIAD', 'Erinevad meediad');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_ERINEVAD_MEEDIAD','Different medias');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_LAPSED_MUJAL_MAAILMAS', 'Lapsed mujal maailmas');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_LAPSED_MUJAL_MAAILMAS','Children in the world');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_LASTEAED', 'Lasteaed');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_LASTEAED', 'Kindergarten');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_KUJUNDAMINE', 'Kujundamine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_KUJUNDAMINE', 'Design');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_MUISTENDID', 'Muistendid');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_MUISTENDID', 'Legends');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_RIIM', 'Riim');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_RIIM', 'Rhyme');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_TEHISKESKKOND', 'Tehiskeskkond');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_TEHISKESKKOND', 'Artificial environment');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_TEKSTI_KAVASTAMINE', 'Teksti kavastamine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_TEKSTI_KAVASTAMINE', 'Planning of text');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_TEKSTI_TEEMA_JA_PEAMÕTE', 'Teksti teema ja peamõte');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_TEKSTI_TEEMA_JA_PEAMÕTE',  'Point of text and main idea');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBJECT_ROOTSI_KEEL', 'Rootsi keel');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBJECT_ROOTSI_KEEL', 'Swedish');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_INIMENE_JA_ÜHISKOND', 'Inimene ja ühiskond');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_INIMENE_JA_ÜHISKOND','Human and society');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_ESITUSTEHNIKAD', 'Esitustehnikad');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_ESITUSTEHNIKAD','Perfomance techniques');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_KÕRVA,_KUULMIS-_JA_TASAKAALUMEEL', 'Kõrva, kuulmis- ja tasakaalumeel');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_KÕRVA,_KUULMIS-_JA_TASAKAALUMEEL', 'Hearing and balance sensation');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_INIMESE_MÕJU_LOODUSELE', 'Inimese mõju loodusele');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_INIMESE_MÕJU_LOODUSELE', 'Human impact to nature');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_KAUBANDUSE_JA_TARBIMISEGA_SEOTUD_KONFLIKTID', 'Kaubanduse ja tarbimise seotud konfliktid');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_KAUBANDUSE_JA_TARBIMISEGA_SEOTUD_KONFLIKTID', 'Trade and consumption related conflicts');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_LOODUSRESSURSSIDE_KASUTAMINE_JA_SELLE_MÕJU_KESKKONNALE','Loodusressursside kasutamine ja selle mõju keskkonnale');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_LOODUSRESSURSSIDE_KASUTAMINE_JA_SELLE_MÕJU_KESKKONNALE','Use of nature resources and their impact to environment');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_KODUTEHNIKA', 'Kodutehnika');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_KODUTEHNIKA', 'Home technics');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_KUJUTAMINE_JA_VÄLJENDAMINE', 'Kujutamine ja väljendamine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_KUJUTAMINE_JA_VÄLJENDAMINE', 'Imagination and expression');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_TEGELASTE_PROBLEEMID_JA_SUHTED', 'Tegelaste probleemid ja suhted');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_TEGELASTE_PROBLEEMID_JA_SUHTED',  'Characters problems and relations');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_MEISTERDAMINE', 'Meisterdamine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_MEISTERDAMINE', 'Crafting');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_TEISED_RAHVUSED_EESTIS', 'Teised rahvused eestis');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_TEISED_RAHVUSED_EESTIS', 'Other nations in Estonia');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_ERINEVAD_SPORDIALAD', 'Erinevad spordialad');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_ERINEVAD_SPORDIALAD', 'Different sports');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_MINA', 'Mina');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_MINA', 'Me');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_TEHNILISED_OSKUSED', 'Tehnilised oskused');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_TEHNILISED_OSKUSED','Technical skills');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_HÄÄLDAMINE', 'Hääldamine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_HÄÄLDAMINE', 'Pronunciation');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_KULTUUR_JA_LOOMING', 'Kultuur ja looming');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_KULTUUR_JA_LOOMING','Culture and creation');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_KOMPOSITSIOONIST_LÄHTUDES', 'Kompositsioonist lähtudes');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_KOMPOSITSIOONIST_LÄHTUDES', 'Originate from composition');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_KODUKOHA_LOODUS', 'Kodukoha loodus');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_KODUKOHA_LOODUS', 'Home place nature');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_KODUMAA', 'Kodumaa');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_KODUMAA', 'Homeland');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_VESTLUSTEEMAD', 'Vestlusteemad');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_VESTLUSTEEMAD', 'Topics of discussion');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBJECT_SOOME_KEEL', 'Soome keel');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBJECT_SOOME_KEEL', 'Finnish');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_KESKKOND_JA_TEHNOLOOGIA', 'Keskkond ja tehnoloogia');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_KESKKOND_JA_TEHNOLOOGIA','Environment and technology');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_GISI_ANALÜÜSID', 'Gis-i analüüsid');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_GISI_ANALÜÜSID', 'Gis analysis');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_ERINEVUSED_REGIOONIDE_JA_RIIKIDE_VAHEL', 'Erinevused regioonide ja riikide vahel');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_ERINEVUSED_REGIOONIDE_JA_RIIKIDE_VAHEL','Differencies between regions and countries');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_SÜNDMUSED', 'Sündmused');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_SÜNDMUSED','Events');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_RAHVASTE_MÜÜDID', 'Rahvaste tüübid');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_RAHVASTE_MÜÜDID', 'Types of nations');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_TERVISE_VÄÄRTUSTAMINE', 'Tervise väärtustamine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_TERVISE_VÄÄRTUSTAMINE','Health valuation');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_SOTSIAALNE_KESKKOND', 'Sotsiaalne keskkond');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_SOTSIAALNE_KESKKOND', 'Social environment');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_MUUSIKALIS_RÜTMILINE_LIIKUMINE', 'Muusikalis rütmiline liikumine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_MUUSIKALIS_RÜTMILINE_LIIKUMINE','Musical rhythmic movement');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_LOODUSKESKKOND', 'Looduskeskkond');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_LOODUSKESKKOND', 'Natural environment');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_VÄÄRTUSED_JA_KÄITUMISREEGLID', 'Väärtused ja käitumisreeglid');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_VÄÄRTUSED_JA_KÄITUMISREEGLID','Values and rules of behaviour');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_SUURUSED_JA_MÕÕTMINE', 'Suurused ja mõõtmine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_SUURUSED_JA_MÕÕTMINE',  'Measures and measuring');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_TURVAVARUSTUS', 'Turvavarustus');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_TURVAVARUSTUS', 'Safety equipment');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_KEELEKASUTUS', 'Keelekasutus');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_KEELEKASUTUS', 'Use of language');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_OMALOOMING', 'Omalooming');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_OMALOOMING', 'Selfcreation');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_SÕNAVARA_RIKASTAMINE', 'Sõnavara rikastamine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_SÕNAVARA_RIKASTAMINE', 'Enriching vocabulary');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_TEKSTILÄHEDASELT', 'Tekstilähedaselt');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_TEKSTILÄHEDASELT','Close to text');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_TEKSTI_KUI_TERVIKU_MÕISTMINE', 'Teksti kui terviku mõistmine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_TEKSTI_KUI_TERVIKU_MÕISTMINE', 'Understanding the text as a whole');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_VANASÕNAD_JA_KÕNEKÄÄNUD', 'Vanasõnad ja kõnekäänud');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_VANASÕNAD_JA_KÕNEKÄÄNUD', 'Proverbs');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_KODU_JA_LÄHIÜMBRUS', 'Kodu ja lähiümbrus');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_KODU_JA_LÄHIÜMBRUS', 'Home and surroundings');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_GISI_MÕISTE,_KOMPONENDID_JA_KASUTUSVALDKONNAD', 'Gisi mõiste komponendid ja kasutusvaldkonnad');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_GISI_MÕISTE,_KOMPONENDID_JA_KASUTUSVALDKONNAD', 'GIS components and field of use');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_GEOMEETRILISED_KUJUNDID', 'Geomeetrilised kujundid');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_GEOMEETRILISED_KUJUNDID', 'Geometric shapes');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_HULGAD_LOENDAMINE_JA_ARVUD_ARVUTAMINE', 'Hulgad,loendamine ja arvutamine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_HULGAD_LOENDAMINE_JA_ARVUD_ARVUTAMINE','Sets,counting and calculation');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_TEEMAKAARDI_KOOSTAMINE', 'Teemakaardi koostamine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_TEEMAKAARDI_KOOSTAMINE', 'Compilation of thematic map');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_KUNSTITEOSE_VAATLEMINE_JA_VESTLUS', 'Kunstiteose vaatlemine ja vestlus');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_KUNSTITEOSE_VAATLEMINE_JA_VESTLUS', 'Observation of art and conversation');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_KÕNELEMINE', 'Kõnelemine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_KÕNELEMINE', 'Speaking');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_EESTI_KULTUURI_TUTVUSTAMINE', 'Eesti kultuuri tutvustus');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_EESTI_KULTUURI_TUTVUSTAMINE', 'Introduction of Estonian culture');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_MUINASJUTUD', 'Muinasjutud');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_MUINASJUTUD', 'Fairytales');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_RIIGID_JA_NENDE_KULTUUR', 'Riigid ja nende kultuur');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_RIIGID_JA_NENDE_KULTUUR',  'Countries and their culture');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_LUGEMINE_JA_KIRJUTAMINE_LASTEKIRJANDUS', 'Lugemine ja kirjutamine lastekirjandus');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_LUGEMINE_JA_KIRJUTAMINE_LASTEKIRJANDUS','Reading and  writing children literature');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_EESTI_JA_MAAILM', 'Eesti ja maailm');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_EESTI_JA_MAAILM', 'Estonia and world');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_KIRJANDUSTEOSE_LEIDMINE', 'Kirjandusteose leidmine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_KIRJANDUSTEOSE_LEIDMINE','Finding literature');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_VIRTUAALKESKKOND', 'Virtuaalkeskkond');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_VIRTUAALKESKKOND','Virtual environment');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_ROLLIMÄNG', 'Rollimäng');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_ROLLIMÄNG', 'Role play');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_OHUALLIKAD_JA_OHUTU_KÄITUMINE', 'Ohuallikad ja ohutu käitumine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_OHUALLIKAD_JA_OHUTU_KÄITUMINE', 'Sources of danger and safe behaviour');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_SUHTLEMINE_JUTUSTAMINE_JA_KUULAMINE', 'Suhtlemine, jutustamine ja kuulamine');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_SUHTLEMINE_JUTUSTAMINE_JA_KUULAMINE', 'Communication,narration and listening');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'SUBTOPIC_MINA_JA_TEISED', 'Mina ja teised');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'SUBTOPIC_MINA_JA_TEISED', 'Me and others');
insert ignore into Translation(translationGroup, translationKey, translation) values (2,'TOPIC_PÕHILIIKUMISED', 'Põhiliikumised');
insert ignore into Translation(translationGroup, translationKey, translation) values (3,'TOPIC_PÕHILIIKUMISED', 'Main movements');


SET foreign_key_checks = 1;
