call update_translations('ABOUT_TAB', 'E-koolikotist','About', 'E-koolikotist (RU)');
call update_translations('ABOUT_PAGE_LINK_TITLE', 'Mis on E-koolikott?', 'What is E-koolikott?', 'Что такое E-koolikott?');
call update_translations('ERROR_LOGIN_FAILED_EKOOL', 'Sisselogimine ebaõnnestus. eKoolis oled registreeritud kasutaja, kelle infost puudub isikukood. Logi sisse eKooli, salvesta sealse konto infosse oma isikukood ja tule siis E-koolikotti tagasi. E-koolikotti saad sisse logida ka ID-kaardi ja mID-ga.',
                         'Login failed. You are a registered user of eKool whose info is missing social security number. Login to eKool, save your social security number in you profile and return to E-koolikott. You can also login to E-koolikott with ID-card and mID.',
                         'Sisselogimine ebaõnnestus. eKoolis oled registreeritud kasutaja, kelle infost puudub isikukood. Logi sisse eKooli, salvesta sealse konto infosse oma isikukood ja tule siis E-koolikotti tagasi. E-koolikotti saad sisse logida ka ID-kaardi ja mID-ga. (RU)');
call update_translations('ERROR_LOGIN_FAILED_HARID', 'Sisselogimine ebaõnnestus. Oled HarID-s kasutaja, kellel puudub isikukood. HarID kaudu E-koolikotti sisenemiseks logi esmalt HarID-sse sisse ning salvesta oma kontole isikukood. Seejärel sulge browseri aken ja logi uues aknas E-koolikotti HarID konto kaudu.',
                         'Login failed. You are a registered user of HarID whose info is missing personal ID code. Login to HarID, save your personal ID code in you profile, close browser and return to E-koolikott in new browser window with HarID.',
                         'Sisselogimine ebaõnnestus. Oled HarID-s kasutaja, kellel puudub isikukood. HarID kaudu E-koolikotti sisenemiseks logi esmalt HarID-sse sisse ning salvesta oma kontole isikukood. Seejärel sulge browseri aken ja logi uues aknas E-koolikotti HarID konto kaudu. (RU)');
call update_translations('ERROR_LOGIN_FAILED_STUUDIUM', 'Sisselogimine ebaõnnestus. Stuudiumis oled registreeritud kasutaja, kelle infost puudub isikukood. Logi sisse Stuudiumisse, salvesta sealse konto infosse oma isikukood ja tule siis E-koolikotti tagasi. E-koolikotti saad sisse logida ka ID-kaardi ja mID-ga.',
                         'Login failed. You are a registered user of Stuudium whose info is missing social security number. Login to Stuudium, save your social security number in you profile and return to E-koolikott. You can also login to E-koolikott with ID-card and mID.',
                         'Sisselogimine ebaõnnestus. Stuudiumis oled registreeritud kasutaja, kelle infost puudub isikukood. Logi sisse Stuudiumisse, salvesta sealse konto infosse oma isikukood ja tule siis E-koolikotti tagasi. E-koolikotti saad sisse logida ka ID-kaardi ja mID-ga. (RU)');
call update_translations('FEED_ID', 'E-koolikott:et', 'E-koolikott:en', 'E-koolikott:ru');
call update_translations('FEED_TITLE', 'E-koolikott - Uudised', 'E-koolikott - News', 'E-koolikott - Новости');
call update_translations('FEEDBACK_ABOUT_EKOOLIKOTT_SUBJECT', 'Tagasiside E-koolikotist', 'Feedback about E-koolikott', 'Обратная связь о E-koolikott');
call update_translations('GIVE_FEEDBACK_LINK', 'Anna tagasisidet E-koolikoti kohta', 'Give feedback about E-koolikott', 'Дайте обратную связь о E-koolikott');
call update_translations('HELP_PAGE_LINK_TITLE', 'Kuidas E-koolikotti kasutada?', 'How to use E-koolikott', 'Как использовать E-koolikott');
call update_translations('HTML_META_DESCRIPTION', 'E-koolikott on õppimiseks loodud veebikeskkond, kus õppekavade materjalid on jaotatud märksõnade järgi. Veebikeskkond võimaldab otsida materjale erinevatest digitaalsetest kogumikest. E-koolikoti eesmärk on võimaldada kasutajal pääseda ligi digitaalsetele õppimismaterjalidele ühest kohast – kasutaja ei pea otsima materjale enam erinevatest veebikeskkondadest.',
                         'E-koolikott is a single web environment comprising digital learning material arranged by keywords on the basis of the curriculum. The portal allows finding educational materials located in different digital tool collections. The primary purpose of E-koolikott is to allow accessing digital learning materials from a single point - the user no longer needs to search for materials in different portals.',
                         'E-koolikott on õppimiseks loodud veebikeskkond, kus õppekavade materjalid on jaotatud märksõnade järgi. Veebikeskkond võimaldab otsida materjale erinevatest digitaalsetest kogumikest. E-koolikoti eesmärk on võimaldada kasutajal pääseda ligi digitaalsetele õppimismaterjalidele ühest kohast – kasutaja ei pea otsima materjale enam erinevatest veebikeskkondadest. (RU)');
call update_translations('SEND_EMAIL_NO_CREATOR_EMAIL', 'Süsteemis puudub õppevara looja/koostaja e-post. Täiendavate küsimuste esitamiseks pöörduge kasutajatoe poole <span style="white-space:nowrap"><strong>e-koolikott@hitsa.ee</strong></span>.',
                         'Creator does not have an e-mail address in E-koolikott. For further assistance contact customer support',
                         'Süsteemis puudub õppevara looja/koostaja e-post. Täiendavate küsimuste esitamiseks pöörduge kasutajatoe poole <span style="white-space:nowrap"><strong>e-koolikott@hitsa.ee</strong></span>. (RU)');
call update_translations('USER_PROFILE_FIRST_LOGIN_NOTICE', 'Parema kasutajakogemuse tagamiseks palume Sul esmakordsel sisselogimisel täita oma profiil E-koolikotis.',
                         'Please fill in Your profile on first login for better user experience.',
                         'Parema kasutajakogemuse tagamiseks palume Sul esmakordsel sisselogimisel täita oma profiil E-koolikotis. (RU)');
call update_translations('USER_PROFILE_ROLE', 'Vali roll, kellena E-koolikotti peamiselt kasutad',
                         'Role',
                         'Vali roll, kellena E-koolikotti peamiselt kasutad (RU)');
call update_translations('TOUR_HELP', 'Küsimärgi alt saad sama tuuri uuesti avada ning anda tagasisidet E-koolikoti kohta ning vastavalt sisse- või väljalogida',
                         'You can watch the tour again by clicking on the question mark',
                         'Под вопросительным знаком вы можете снова открыть тот же виртуальный тур  и оставить отзыв о E-koolikott, а также войти или выйти соответственно.');
update Translation set translation = 'To use E-koolikott you are giving your personal data to digital learning object platform. Please read information page and give your response' where translationKey = 'AGREEMENT_DIALOG_TEXT' and translationGroup = 3;
