SET foreign_key_checks = 0;

call update_translations('PORTFOLIOS_SET_TO_PRIVATE_TEXT', 'Osad Sinu kogumikud on muudetud privaatseks, sest need sisaldavad teiste autorite materjale, mille litsents või autoriõigused ei luba neid avalikes kogumikes kuvada.<br><br>Neid kogumikke saad avalikustada alles siis, kui neis olevad materjalid omavad litsentsi CC BY-SA 3.0 (mida saab lisada materjali omanik) või kui oled kokkusobimatud materjalid oma kogumikust eemaldanud.',
                                                           'Some of your portfolios have been set to private because they contain materials by other creators which have invalid licenses for publishing.<br><br>These portfolios can not be published before these materials have CC BY-SA 3.0 license (which can be set by the owner of the material) or the materials are removed from portfolio.',
                                                           'Osad Sinu kogumikud on muudetud privaatseks, sest need sisaldavad teiste autorite materjale, mille litsents või autoriõigused ei luba neid avalikes kogumikes kuvada.<br><br>Neid kogumikke saad avalikustada alles siis, kui neis olevad materjalid omavad litsentsi CC BY-SA 3.0 (mida saab lisada materjali omanik) või kui oled kokkusobimatud materjalid oma kogumikust eemaldanud.');

call update_translations('LICENSE_AGREEMENT_DIALOG_TEXT', 'Et võimaldada kogumike avaldamist, ühtlustab E-Koolikott keskkonnas kasutatavat litsentsi. <strong>Ühtseks litsentsiks on CC BY-SA 3.0.</strong> Litsentsi kokkuvõte asub <a href="https://creativecommons.org/licenses/by-sa/3.0/ee/" target="_blank">SIIN</a>, litsentsi täistekst asub <a href="https://creativecommons.org/licenses/by-sa/3.0/ee/legalcode" target="_blank">SIIN</a>.<br><br><strong>Nõustumisel muudame automaatselt kõigi Sinu materjalide ja kogumike litsentsi</strong> -  loeme, et oled selleks määranud CC BY-SA 3.0.<br><br><strong>Mittenõustumisel</strong> muutuvad kõik Sinu materjalid ja kogumikud privaatseks, välja arvatud, kui neil on juba varem CC BY-SA või CC BY litsents. Saad privaatsetele materjalidele ja kogumikele uue litsentsi hiljem ükshaaval käsitsi määrata ja need hiljem taas avalikuks muuta.<br><br><strong>NB! Litsents ei laiene sisule, mis asub E-koolikoti keskkonnast väljaspool (lingitud sisu). Litsents kehtib otse E-koolikotti laaditud või kirjutatud (sh kopeeritud) sisule.</strong>',
                                                           'In order to enable the publication of collections, E-Koolikott standardizes the license for the environment. <strong>The unified license is CC BY-SA 3.0.</strong> The license summary is located <a href="https://creativecommons.org/licenses/by-sa/3.0/en/" target="_blank">HERE</a>, the full text of the license can be found <a href="https://creativecommons.org/licenses/by-sa/3.0/en/legalcode" target="_blank">HERE</a>.<br><br><strong>If you accept, we will automatically change the license for all of your materials and collections</strong> - we assume that you have designated CC BY-SA 3.0.<br><br><strong>If you do not agree</strong>, all your materials and collections will become private unless they have CC BY-SA or CC BY license. You can manually assign a new license to individual materials and collections one at a time and re-publish them later.<br><br><strong>NB! The license does not extend to content located outside the E-Koolikott environment (linked content). The license applies to content uploaded or written (including copied) directly into the E-Koolikott.</strong>',
                                                           'Et võimaldada kogumike avaldamist, ühtlustab E-Koolikott keskkonnas kasutatavat litsentsi. <strong>Ühtseks litsentsiks on CC BY-SA 3.0.</strong> Litsentsi kokkuvõte asub <a href="https://creativecommons.org/licenses/by-sa/3.0/ee/" target="_blank">SIIN</a>, litsentsi täistekst asub <a href="https://creativecommons.org/licenses/by-sa/3.0/ee/legalcode" target="_blank">SIIN</a>.<br><br><strong>Nõustumisel muudame automaatselt kõigi Sinu materjalide ja kogumike litsentsi</strong> -  loeme, et oled selleks määranud CC BY-SA 3.0.<br><br><strong>Mittenõustumisel</strong> muutuvad kõik Sinu materjalid ja kogumikud privaatseks, välja arvatud, kui neil on juba varem CC BY-SA või CC BY litsents. Saad privaatsetele materjalidele ja kogumikele uue litsentsi hiljem ükshaaval käsitsi määrata ja need hiljem taas avalikuks muuta.<br><br><strong>NB! Litsents ei laiene sisule, mis asub E-koolikoti keskkonnast väljaspool (lingitud sisu). Litsents kehtib otse E-koolikotti laaditud või kirjutatud (sh kopeeritud) sisule.</strong>');

call update_translations ('PORTFOLIO_PRIVATE_FROM', 'kogumikust (privaatne)', 'portfolio (private)', 'kogumikust (privaatne) (RU)');
call update_translations ('PORTFOLIO_DELETED_FROM', 'kogumikust (kustutatud)', 'portfolio (kustutatud)', 'kogumikust (kustutatud) (RU)');

SET foreign_key_checks = 1;