SET foreign_key_checks = 0;

INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (1, 'LICENSE_AGREEMENT_DIALOG_HEADER', 'Nõusolek minu materjalide ja kogumike litsentsi muutmiseks');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'LICENSE_AGREEMENT_DIALOG_HEADER', 'Agreement to change the licenses of my materials and portfolios');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (2, 'LICENSE_AGREEMENT_DIALOG_HEADER', 'Nõusolek minu materjalide ja kogumike litsentsi muutmiseks');

INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (1, 'LICENSE_AGREEMENT_DIALOG_TEXT', 'Et võimaldada kogumike avaldamist, ühtlustab E-Koolikott keskkonnas kasutatavat litsentsi. <strong>Ühtseks litsentsiks on CC BY-SA 3.0.</strong> Litsentsi kokkuvõte asub <a href="https://creativecommons.org/licenses/by-sa/3.0/ee/">SIIN</a>, litsentsi täistekst asub <a href="https://creativecommons.org/licenses/by-sa/3.0/ee/legalcode">SIIN</a>.<br><strong>Nõustumisel muudame automaatselt kõigi Sinu materjalide ja kogumike litsentsi</strong> -  loeme, et oled selleks määranud CC BY-SA 3.0.<br><strong>Mittenõustumisel</strong> muutuvad kõik Sinu materjalid ja kogumikud privaatseks, välja arvatud, kui neil on juba varem CC BY-SA või CC BY litsents. Saad privaatsetele materjalidele ja kogumikele uue litsentsi hiljem ükshaaval käsitsi määrata ja need hiljem taas avalikuks muuta.<br><strong>NB! Litsents ei laiene sisule, mis asub E-koolikoti keskkonnast väljaspool (lingitud sisu). Litsents kehtib otse E-koolikotti laaditud või kirjutatud (sh kopeeritud) sisule.</strong>');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'LICENSE_AGREEMENT_DIALOG_TEXT', 'In order to enable the publication of collections, E-Koolikott standardizes the license for the environment. <strong>The unified license is CC BY-SA 3.0.</strong> The license summary is located <a href="https://creativecommons.org/licenses/by-sa/3.0/en/">HERE</a>, the full text of the license can be found <a href="https://creativecommons.org/licenses/by-sa/3.0/en/legalcode">HERE</a>.<br><strong>If you accept, we will automatically change the license for all of your materials and collections</strong> - we assume that you have designated CC BY-SA 3.0.<br><strong>If you do not agree</strong>, all your materials and collections will become private unless they have CC BY-SA or CC BY license. You can manually assign a new license to individual materials and collections one at a time and re-publish them later.<br><strong>NB! The license does not extend to content located outside the E-Koolikott environment (linked content). The license applies to content uploaded or written (including copied) directly into the E-Koolikott.</strong>');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (2, 'LICENSE_AGREEMENT_DIALOG_TEXT', 'Et võimaldada kogumike avaldamist, ühtlustab E-Koolikott keskkonnas kasutatavat litsentsi. <strong>Ühtseks litsentsiks on CC BY-SA 3.0.</strong> Litsentsi kokkuvõte asub <a href="https://creativecommons.org/licenses/by-sa/3.0/ee/">SIIN</a>, litsentsi täistekst asub <a href="https://creativecommons.org/licenses/by-sa/3.0/ee/legalcode">SIIN</a>.<br><strong>Nõustumisel muudame automaatselt kõigi Sinu materjalide ja kogumike litsentsi</strong> -  loeme, et oled selleks määranud CC BY-SA 3.0.<br><strong>Mittenõustumisel</strong> muutuvad kõik Sinu materjalid ja kogumikud privaatseks, välja arvatud, kui neil on juba varem CC BY-SA või CC BY litsents. Saad privaatsetele materjalidele ja kogumikele uue litsentsi hiljem ükshaaval käsitsi määrata ja need hiljem taas avalikuks muuta.<br><strong>NB! Litsents ei laiene sisule, mis asub E-koolikoti keskkonnast väljaspool (lingitud sisu). Litsents kehtib otse E-koolikotti laaditud või kirjutatud (sh kopeeritud) sisule.</strong>');

INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (1, 'LICENSE_AGREEMENT_DIALOG_ACTION_NO', 'Ei nõustu');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'LICENSE_AGREEMENT_DIALOG_ACTION_NO', 'Disagree');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (2, 'LICENSE_AGREEMENT_DIALOG_ACTION_NO', 'Ei nõustu');

INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (1, 'LICENSE_AGREEMENT_DIALOG_ACTION_YES', 'Nõustun ja sisenen');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'LICENSE_AGREEMENT_DIALOG_ACTION_YES', 'Agree and enter');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (2, 'LICENSE_AGREEMENT_DIALOG_ACTION_YES', 'Nõustun ja sisenen');

INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (1, 'LICENSE_AGREEMENT_DIALOG_ACTION_EXIT', 'Väljun');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'LICENSE_AGREEMENT_DIALOG_ACTION_EXIT', 'Exit');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (2, 'LICENSE_AGREEMENT_DIALOG_ACTION_EXIT', 'Väljun');

SET foreign_key_checks = 1;