SET foreign_key_checks = 0;

call update_translations('LICENSE_AGREEMENT_DIALOG_TEXT', 'Kogumike avalikustamiseks ühtlustame E-koolikotis kasutatavat litsentsi, milleks on <strong>CC BY-SA 3.0.</strong> Litsentsi kokkuvõte asub <a href="https://creativecommons.org/licenses/by-sa/3.0/ee/" target="_blank">SIIN</a> ja täistekst <a href="https://creativecommons.org/licenses/by-sa/3.0/ee/legalcode" target="_blank">SIIN</a>.<br><br><strong>Nõustumisel muudame automaatselt kõigi Sinu materjalide ja kogumike litsentsiks CC BY-SA 3.0.</strong><br><strong>Mittenõustumisel</strong> muutuvad kõik Sinu materjalid ja kogumikud, millel ei ole CC BY-SA 3.0 litsentsi, privaatseks (st mitte avalikuks). Privaatsetele materjalidele ja kogumikele saad uue litsentsi hiljem ükshaaval käsitsi määrata ja need taas avalikuks muuta.<br><br><strong>NB! Litsents ei laiene sisule, mis asub E-koolikotist väljaspool (nt lingitud sisu). Litsents kehtib otse E-koolikotti laaditud või kirjutatud (sh kopeeritud) sisule.</strong>',
    'We are applying changes to the current system of licenses in E-schoolbag and moving over to the use of only one licence - <strong>CC BY-SA 3.0.</strong> You can find the summary of the license <a href="https://creativecommons.org/licenses/by-sa/3.0/ee/" target="_blank">HERE</a> and read the full version <a href="https://creativecommons.org/licenses/by-sa/3.0/ee/legalcode" target="_blank">HERE</a>.<br><br> We would like to help make this process easier and faster for you and ask for your consent to apply the change to all of your materials and portfolios at once.<br><strong>If you accept, then we will automatically change the licenses of all of your materials and portfolios to CC BY-SA 3.0.</strong><br><strong>If you do not accept</strong>, all of your materials which do not already have the CC BY-SA 3.0 license will be made private (visible only to you). These materials can later be published only after you have accepted the new license on each of them one by one.<br><br><strong>NB! The license does not extend to content which is located outside of E-schoolbag (e.g. linked content). The license applies to content which is uploaded or written (also copied) directly into E-schoolbag.</strong>',
    'Kogumike avalikustamiseks ühtlustame E-koolikotis kasutatavat litsentsi, milleks on <strong>CC BY-SA 3.0.</strong> Litsentsi kokkuvõte asub <a href="https://creativecommons.org/licenses/by-sa/3.0/ee/" target="_blank">SIIN</a> ja täistekst <a href="https://creativecommons.org/licenses/by-sa/3.0/ee/legalcode" target="_blank">SIIN</a>.<br><br><strong>Nõustumisel muudame automaatselt kõigi Sinu materjalide ja kogumike litsentsiks CC BY-SA 3.0.</strong><br><strong>Mittenõustumisel</strong> muutuvad kõik Sinu materjalid ja kogumikud, millel ei ole CC BY-SA 3.0 litsentsi, privaatseks (st mitte avalikuks). Privaatsetele materjalidele ja kogumikele saad uue litsentsi hiljem ükshaaval käsitsi määrata ja need taas avalikuks muuta.<br><br><strong>NB! Litsents ei laiene sisule, mis asub E-koolikotist väljaspool (nt lingitud sisu). Litsents kehtib otse E-koolikotti laaditud või kirjutatud (sh kopeeritud) sisule.</strong>');

call update_translations('PORTFOLIOS_SET_TO_PRIVATE_TEXT', 'Osad Sinu kogumikud (loetelu allpool) on muudetud privaatseks, sest need sisaldavad teiste autorite materjale, mille litsents või autoriõigused ei luba neid kogumikus avalikustada.<br><br>Selliseid kogumikke saad avalikustada alles siis, kui neis olevad materjalid on litsentsiga CC BY-SA 3.0 (mida saab lisada materjali omanik) või kui eemaldad sobimatu litsentsiga materjalid oma kogumikust.',
                          'Some of your portfolios (see the list below) have been made private because these portfolios include materials from other authors without the new CC BY-SA 3.0 license. Portfolios containing materials without the correct license can not be made public in E-schoolbag.<br><br>You can publish these portfolios after the CC BY-SA 3.0 license has been added to all materials included in them (licenses can be changed by the material’s owner) or you have removed all materials without the correct license from the portfolio.',
                          'Osad Sinu kogumikud (loetelu allpool) on muudetud privaatseks, sest need sisaldavad teiste autorite materjale, mille litsents või autoriõigused ei luba neid kogumikus avalikustada.<br><br>Selliseid kogumikke saad avalikustada alles siis, kui neis olevad materjalid on litsentsiga CC BY-SA 3.0 (mida saab lisada materjali omanik) või kui eemaldad sobimatu litsentsiga materjalid oma kogumikust.');

call update_translations('MATERIAL_LICENSE_WARNING', 'Ühtlustame E-koolikotis kasutatavat litsentsi. Kuna materjalil puudub <strong>CC BY-SA 3.0 litsents</strong> (või sellega kokku sobiv CC BY 3.0 litsents), ei saa materjali hetkel avalikustada.<br><br>Materjali avalikustamine on võimalik vaid juhul, kui nõustud nimetatud litsentsiga (litsents ei kehti lingitud sisule, mis asub E-koolikotist väljas). Selleks ava materjali muutmise vaade ja kinnita litsentsiga nõusolek.',
                          'We are applying changes to the license system in E-schoolbag. Please review and add the CC BY-SA 3.0 (or a compatible CC BY 3.0) license to the material if you wish to publish it.<br><br>Publishing the material is possible only after the required license has been added to it (the license does not apply to materials which are located outside E-Schoolbag). To do that, open edit mode and fill the checkbox to accept the new license.',
                          'Ühtlustame E-koolikotis kasutatavat litsentsi. Kuna materjalil puudub <strong>CC BY-SA 3.0 litsents</strong> (või sellega kokku sobiv CC BY 3.0 litsents), ei saa materjali hetkel avalikustada.<br><br>Materjali avalikustamine on võimalik vaid juhul, kui nõustud nimetatud litsentsiga (litsents ei kehti lingitud sisule, mis asub E-koolikotist väljas). Selleks ava materjali muutmise vaade ja kinnita litsentsiga nõusolek.');

SET foreign_key_checks = 1;
