SET foreign_key_checks = 0;

INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_AJAKIRJANDUS_JA_INFOLEVI', 'Journalism and Information') ON DUPLICATE KEY UPDATE translation='Journalism and Information';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_ARHITEKTUUR_JA_EHITUS', 'Architecture and Building') ON DUPLICATE KEY UPDATE translation='Architecture and Building';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_ÄRINDUS_JA_HALDUS', 'Business and Management') ON DUPLICATE KEY UPDATE translation='Business and Management';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_ARVUTITEADUSED', 'Information and Communication Technologies') ON DUPLICATE KEY UPDATE translation='Information and Communication Technologies';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_BIOLOOGIA_JA_SELLEGA_SEOTUD_TEADUSED', 'Biology and Related Sciences') ON DUPLICATE KEY UPDATE translation='Biology and Related Sciences';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_BIOTEADUSED', 'Biological and Related Sciences') ON DUPLICATE KEY UPDATE translation='Biological and Related Sciences';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_EESTI_KEEL_KUI_TEINE_KEEL', 'Estonian as a Second Language') ON DUPLICATE KEY UPDATE translation='Estonian as a Second Language';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_FÜÜSIKALISED_LOODUSTEADUSED', 'Physical Sciences') ON DUPLICATE KEY UPDATE translation='Physical Sciences';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_HÜGIEEN_JA_TÖÖTERVISHOID', 'Hygiene and Occupational Health') ON DUPLICATE KEY UPDATE translation='Hygiene and Occupational Health';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_INFORMAATIKA_JA_INFOTEHNOLOOGIA', 'Computer Science') ON DUPLICATE KEY UPDATE translation='Computer Science';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_INFORMATSIOONI-_JA_KOMMUNIKATSIOONITEHNOLOOGIAD', 'Information- and Communication Technologies') ON DUPLICATE KEY UPDATE translation='Information- and Communication Technologies';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_ISIKUTEENINDUS', 'Personal Care') ON DUPLICATE KEY UPDATE translation='Personal Care';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_KEEL_JA_KIRJANDUS', 'Language and Literature') ON DUPLICATE KEY UPDATE translation='Language and Literature';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_KEEL_JA_KÕNE', 'Language and Speech') ON DUPLICATE KEY UPDATE translation='Language and Speech';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_KEHALINE_KASVATUS', 'Physical Education') ON DUPLICATE KEY UPDATE translation='Physical Education';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_KESKKONNAKAITSE', 'Environmental Protection') ON DUPLICATE KEY UPDATE translation='Environmental Protection';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_KUNSTIAINED', 'Art Subjects') ON DUPLICATE KEY UPDATE translation='Art Subjects';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_KUNSTID', 'Art') ON DUPLICATE KEY UPDATE translation='Art';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_LOODUSAINED', 'Natural Sciences') ON DUPLICATE KEY UPDATE translation='Natural Sciences';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_MATEMAATIKA', 'Mathematics') ON DUPLICATE KEY UPDATE translation='Mathematics';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_MATEMAATIKA_JA_STATISTIKA', 'Mathematics and Statistics') ON DUPLICATE KEY UPDATE translation='Mathematics and Statistics';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_MINA_JA_KESKKOND', 'The Environment and Me') ON DUPLICATE KEY UPDATE translation='The Environment and Me';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_NÄITEKUNST', 'Performing Arts') ON DUPLICATE KEY UPDATE translation='Performing Arts';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_NOORSOOTÖÖ', 'Youth Work') ON DUPLICATE KEY UPDATE translation='Youth Work';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_ÕPETAJAKOOLITUS_JA_KASVATUSTEADUSED', 'Teacher Training and Educational Science') ON DUPLICATE KEY UPDATE translation='Teacher Training and Educational Science';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_PÕLLUMAJANDUS_METSANDUS_JA_KALANDUS', 'Agriculture, Forestry and Fishery') ON DUPLICATE KEY UPDATE translation='Agriculture, Forestry and Fishery';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_RIIGIKAITSE', 'National Defence') ON DUPLICATE KEY UPDATE translation='National Defence';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_SISEKAITSE', 'Internal Security') ON DUPLICATE KEY UPDATE translation='Internal Security';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_SOTSIAAL-_JA_KÄITUMISTEADUSED', 'Social and Behavioral Science') ON DUPLICATE KEY UPDATE translation='Social and Behavioral Science';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_SOTSIAALAINED', 'Social Sciences') ON DUPLICATE KEY UPDATE translation='Social Sciences';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_SOTSIAALTEENUSED', 'Social Services') ON DUPLICATE KEY UPDATE translation='Social Services';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_TEHNIKA_TOOTMINE_JA_TEHNOLOOGIA', 'Engineering, Production and Technology') ON DUPLICATE KEY UPDATE translation='Engineering, Production and Technology';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_TEHNIKAALAD', 'Engineering Disciplines') ON DUPLICATE KEY UPDATE translation='Engineering Disciplines';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_TEHNOLOOGIA', 'Technology') ON DUPLICATE KEY UPDATE translation='Technology';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_TOOTMINE_JA_TÖÖTLEMINE', 'Manufacturing and Processing') ON DUPLICATE KEY UPDATE translation='Manufacturing and Processing';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_TRANSPORDITEENUSED', 'Transport Services') ON DUPLICATE KEY UPDATE translation='Transport Services';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_TURVAMINE', 'Security Services') ON DUPLICATE KEY UPDATE translation='Security Services';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_TURVATEENUSED', 'Security Services') ON DUPLICATE KEY UPDATE translation='Security Services';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_VALIKÕPPEAINED', 'Electives') ON DUPLICATE KEY UPDATE translation='Electives';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_VÕÕRKEELED', 'Foreign Languages') ON DUPLICATE KEY UPDATE translation='Foreign Languages';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_AJALUGU', 'History') ON DUPLICATE KEY UPDATE translation='History';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_BIOLOOGIA', 'Biology') ON DUPLICATE KEY UPDATE translation='Biology';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_EESTI_KEEL', 'Estonian') ON DUPLICATE KEY UPDATE translation='Estonian';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_EESTI_KEEL_TEISE_KEELENA', 'Estonian as a Second Language') ON DUPLICATE KEY UPDATE translation='Estonian as a Second Language';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_ETTEVÕTLUSÕPETUS', 'Entrepreneurship') ON DUPLICATE KEY UPDATE translation='Entrepreneurship';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_FILOSOOFIA', 'Philosophy') ON DUPLICATE KEY UPDATE translation='Philosophy';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_FÜÜSIKA', 'Physics') ON DUPLICATE KEY UPDATE translation='Physics';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_GEOGRAAFIA', 'Geography') ON DUPLICATE KEY UPDATE translation='Geography';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_INFORMAATIKA', 'Computer Science') ON DUPLICATE KEY UPDATE translation='Computer Science';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_INGLISE_KEEL', 'English') ON DUPLICATE KEY UPDATE translation='English';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_INIMESEÕPETUS', 'Personal, Social and Health Education') ON DUPLICATE KEY UPDATE translation='Personal, Social and Health Education';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_KARJÄÄRIÕPETUS', 'Career Planning') ON DUPLICATE KEY UPDATE translation='Career Planning';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_KÄSITÖÖ', 'Handicraft') ON DUPLICATE KEY UPDATE translation='Handicraft';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_KEEMIA', 'Chemistry') ON DUPLICATE KEY UPDATE translation='Chemistry';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_KEHALINE_KASVATUS', 'Physical Education') ON DUPLICATE KEY UPDATE translation='Physical Education';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_KIRJANDUS', 'Literature') ON DUPLICATE KEY UPDATE translation='Literature';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_KODUNDUS', 'Home Economics') ON DUPLICATE KEY UPDATE translation='Home Economics';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_KÜBERKAITSE', 'Cyber Security') ON DUPLICATE KEY UPDATE translation='Cyber Security';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_KUNST', 'Art') ON DUPLICATE KEY UPDATE translation='Art';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_LOODUSÕPETUS', 'Natural Sciences') ON DUPLICATE KEY UPDATE translation='Natural Sciences';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_MAJANDUS-_JA_ETTEVÕTLUSÕPE', 'Economics and Entrepreneurship') ON DUPLICATE KEY UPDATE translation='Economics and Entrepreneurship';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_MATEMAATIKA', 'Mathematics') ON DUPLICATE KEY UPDATE translation='Mathematics';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_MUU_VÕÕRKEEL', 'Other Foreign Language') ON DUPLICATE KEY UPDATE translation='Other Foreign Language';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_MUUD_VALIKÕPPEAINED', 'Other Electives') ON DUPLICATE KEY UPDATE translation='Other Electives';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_MUUSIKA', 'Music') ON DUPLICATE KEY UPDATE translation='Music';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_PRANTSUSE_KEEL', 'French') ON DUPLICATE KEY UPDATE translation='French';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_RIIGIKAITSE', 'National Defence') ON DUPLICATE KEY UPDATE translation='National Defence';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_SAKSA_KEEL', 'German') ON DUPLICATE KEY UPDATE translation='German';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_TEHNOLOOGIAÕPETUS', 'Technology') ON DUPLICATE KEY UPDATE translation='Technology';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_TÖÖÕPETUS', 'Woodworking') ON DUPLICATE KEY UPDATE translation='Woodworking';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_ÜHISKONNAÕPETUS', 'Civics and Citizenship Education') ON DUPLICATE KEY UPDATE translation='Civics and Citizenship Education';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_USUNDIÕPETUS', 'Religious Studies') ON DUPLICATE KEY UPDATE translation='Religious Studies';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_UURIMISTÖÖ_ALUSED', 'Basics of Research') ON DUPLICATE KEY UPDATE translation='Basics of Research';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_VALIKKURSUSED', 'Electives') ON DUPLICATE KEY UPDATE translation='Electives';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_VENE_KEEL', 'Russian') ON DUPLICATE KEY UPDATE translation='Russian';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'SUBJECT_VENE_KEEL_EMAKEELENA', 'Russian as a First Language') ON DUPLICATE KEY UPDATE translation='Russian as a First Language';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_LANGUAGE_AND_SPEECH', 'Language and Speech') ON DUPLICATE KEY UPDATE translation='Language and Speech';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_ME_AND_THE_ENVIRONMENT', 'The Environment and Me') ON DUPLICATE KEY UPDATE translation='The Environment and Me';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'DOMAIN_COMPUTER_SCIENCE', 'Computer Science') ON DUPLICATE KEY UPDATE translation='Computer Science';
UPDATE Translation SET translation = 'Preschool Education' WHERE translationGroup = 3 AND translationKey = 'PRESCHOOLEDUCATION';
UPDATE Translation SET translation = 'Basic Education' WHERE translationGroup = 3 AND translationKey = 'BASICEDUCATION';
UPDATE Translation SET translation = 'Secondary Education' WHERE translationGroup = 3 AND translationKey = 'SECONDARYEDUCATION';
UPDATE Translation SET translation = 'Vocational Education' WHERE translationGroup = 3 AND translationKey = 'VOCATIONALEDUCATION';
UPDATE Translation SET translation = 'Nonformal Education' WHERE translationGroup = 3 AND translationKey = 'NONFORMALEDUCATION';
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (1, 'OR', 'või');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (3, 'OR', 'or');
INSERT INTO Translation (translationGroup, translationKey, translation) VALUES (2, 'OR', 'või');

SET foreign_key_checks = 1;